# Generated by Django 4.2.3 on 2023-07-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='Sample Username', max_length=200),
        ),
    ]
