# Generated by Django 4.2.3 on 2023-10-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_users_alter_member_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
