# Generated by Django 4.2.3 on 2023-10-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_login_delete_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='type',
            field=models.CharField(default='logging in', max_length=50),
        ),
    ]
