# Generated by Django 4.2.3 on 2023-10-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_login_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('subscribed', models.CharField(default='No', max_length=50)),
            ],
        ),
    ]
