# Generated by Django 4.2.3 on 2023-10-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_premium_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='customer_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
