# Generated by Django 4.2.3 on 2023-10-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_users_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium_member',
            name='customer_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
