# Generated by Django 4.2.3 on 2023-10-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_premium_member_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premium_member',
            old_name='customer_id',
            new_name='stripe_customer_id',
        ),
    ]
