# Generated by Django 4.2.3 on 2023-10-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_customer_id_premium_member_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium_member',
            name='email',
        ),
        migrations.AddField(
            model_name='premium_member',
            name='customer_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='premium_member',
            name='stripe_customer_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
