# Generated by Django 4.2.3 on 2023-10-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_premium_member_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Premium_Members',
            fields=[
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.users')),
                ('subscribed', models.CharField(default='No', max_length=50)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Premium_Member',
            new_name='Premium_Members',
        ),
    ]
