# Generated by Django 4.2.3 on 2023-10-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_deleted_premium_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Premium_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default=0, max_length=20)),
                ('subscribed', models.CharField(default='No', max_length=50)),
                ('registration_date', models.DateTimeField(blank=True, default=0, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Deleted_Premium_Members',
        ),
    ]
