# Generated by Django 4.2.3 on 2023-10-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_deleted_premium_users_delete_deleted_premium_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
