# Generated by Django 4.2 on 2024-04-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_users_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cricket_AI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("sent_date", models.DateTimeField(auto_now_add=True)),
                ("essay_type", models.CharField(max_length=200)),
                ("subject_level", models.CharField(max_length=200)),
                ("essay_length", models.CharField(max_length=200)),
            ],
        ),
    ]
