# Generated by Django 5.0.6 on 2024-05-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_cricket_ai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uni_Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('uni_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
