# Generated by Django 5.0.6 on 2024-05-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='passwd2',
            field=models.CharField(default='Sample Username', max_length=50),
        ),
    ]
