# Generated by Django 5.0.6 on 2024-05-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_member_passwd2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='passwd',
        ),
        migrations.RemoveField(
            model_name='member',
            name='passwd2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='duration',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='language',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='program_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='uni_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
