# Generated by Django 5.0.6 on 2024-05-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_member_email_remove_member_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='program_name',
        ),
    ]
