# Generated by Django 5.0.6 on 2024-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_member_program_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uni_database',
            name='language',
        ),
        migrations.AddField(
            model_name='uni_database',
            name='attendance',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='uni_database',
            name='degree_type',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='uni_database',
            name='description',
            field=models.CharField(default='none', max_length=20000),
        ),
        migrations.AddField(
            model_name='uni_database',
            name='ib_requirements',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='uni_database',
            name='link',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='uni_database',
            name='study_mode',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='uni_database',
            name='tuition_fee_euro',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='uni_database',
            name='tuition_fee_original',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
