# Generated by Django 5.0.6 on 2024-05-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_uni_database_language_uni_database_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni_database',
            name='ib_requirements',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
