# Generated by Django 5.0.6 on 2024-05-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_uni_database_ib_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_database',
            name='discipline',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='uni_database',
            name='ib_requirements',
            field=models.IntegerField(default=0),
        ),
    ]
