# Generated by Django 5.0.6 on 2024-05-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_uni_database_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni_database',
            name='link',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
