# Generated by Django 5.0.6 on 2024-06-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_uni_database_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(default='No', max_length=100)),
            ],
        ),
    ]
