# Generated by Django 5.0.6 on 2024-06-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_ip_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip_addresses',
            old_name='ip_address',
            new_name='email',
        ),
    ]
