# Generated by Django 5.0.6 on 2024-06-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_rename_ip_address_ip_addresses_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IP_addresses',
            new_name='Home_Visits',
        ),
    ]
