# Generated by Django 5.0.6 on 2024-07-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_rename_ip_addresses_home_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_visits',
            name='ip_address',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
