# Generated by Django 5.0.6 on 2024-09-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_home_visits_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_visits',
            name='city',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='home_visits',
            name='country',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
