# Generated by Django 5.0.6 on 2024-09-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('subjects_1', models.CharField(max_length=255)),
                ('subjects_2', models.CharField(max_length=255)),
                ('subjects_3', models.CharField(max_length=255)),
                ('countries_1', models.CharField(max_length=255)),
                ('countries_2', models.CharField(max_length=255)),
                ('countries_3', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
