# Generated by Django 5.0.6 on 2024-09-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_survey_response_delete_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_database',
            name='ib_requirements_long',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='uni_database_free',
            name='ib_requirements_long',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='uni_database_registered',
            name='ib_requirements_long',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='survey_response',
            name='phone_number',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
