# Generated by Django 5.0.6 on 2024-09-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_uni_database_ib_requirements_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uni_database',
            name='ib_requirements_long',
        ),
    ]
