# Generated by Django 5.0.6 on 2024-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_remove_uni_database_ib_requirements_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_database',
            name='ib_requirements_long',
            field=models.CharField(default='Average IB requirements for this course. The official ones may differ by around 2-3 points in either way.', max_length=500),
        ),
    ]
