# Generated by Django 5.0.6 on 2024-10-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_uni_database_ib_requirements_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('customer_id', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
