# Generated by Django 5.0.6 on 2024-10-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('journey_path', models.JSONField()),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField()),
            ],
        ),
    ]
