# Generated by Django 5.0.6 on 2024-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_userjourney'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('journey_path', models.JSONField()),
                ('date_created', models.DateTimeField()),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserJourney',
        ),
    ]
