# Generated by Django 5.0.6 on 2024-11-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_user_journey_delete_userjourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_journey',
            name='ip_address',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
