# Generated by Django 5.0.6 on 2024-11-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_user_journey_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_journey',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user_journey',
            name='journey_path',
        ),
        migrations.RemoveField(
            model_name='user_journey',
            name='session_end',
        ),
        migrations.RemoveField(
            model_name='user_journey',
            name='session_start',
        ),
    ]
