# Generated by Django 5.0.6 on 2024-11-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_remove_user_journey_date_created_and_more'),
    ]


