# Generated by Django 5.0.6 on 2024-11-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_user_journey_date_created_user_journey_journey_path_and_more'),
    ]


