# Generated by Django 5.0.6 on 2024-11-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_delete_user_journey'),
    ]


