# Generated by Django 5.0.6 on 2024-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_user_journey'),
    ]

