# Generated by Django 5.0.6 on 2024-11-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_user_journey2_delete_user_journey'),
    ]
