# Generated by Django 5.0.6 on 2024-11-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_alter_journey_platform_journey_path'),
    ]

