# Generated by Django 5.0.6 on 2024-11-14 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_alter_journey_platform_date_created_and_more'),
    ]

