# Generated by Django 5.0.6 on 2024-11-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_alter_journey_platform_date_created_and_more'),
    ]

