# Generated by Django 5.0.6 on 2024-11-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_delete_journey_platform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Journey',
        ),
    ]
