# Generated by Django 5.0.6 on 2024-11-14 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_delete_user_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('ip_address', models.CharField(default='null', max_length=255)),
                ('journey_path', models.JSONField(default=dict)),
                ('session_start', models.DateTimeField(default=datetime.datetime.now)),
                ('session_end', models.DateTimeField(default=datetime.datetime.now)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
