# Generated by Django 5.0.6 on 2024-11-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_user_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_journey',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_journey',
            name='journey_path',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='user_journey',
            name='session_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_journey',
            name='session_start',
            field=models.DateTimeField(),
        ),
    ]
