# Generated by Django 5.0.6 on 2024-11-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_alter_user_journey_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_entries', models.CharField(max_length=100)),
            ],
        ),
    ]
