# Generated by Django 5.0.6 on 2024-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_total_entries'),
    ]


