# Generated by Django 5.0.6 on 2024-11-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_uni_database_free_blurred'),
    ]

