# Generated by Django 5.0.6 on 2024-11-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_alter_uni_database_free_blurred'),
    ]

