# Generated by Django 5.0.6 on 2024-11-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_uni_database_free2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uni_Database_Free',
        ),
    ]
