# Generated by Django 5.0.6 on 2024-11-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_delete_uni_database_free'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uni_Database_Registered',
        ),
    ]
