# Generated by Django 5.0.6 on 2024-11-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_delete_uni_database_registered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uni_Database',
        ),
    ]
