# Generated by Django 5.0.6 on 2024-11-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_delete_uni_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uni_Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('uni_name', models.CharField(max_length=200)),
                ('tuition_fee_original', models.CharField(default='none', max_length=200)),
                ('degree_type', models.CharField(default='none', max_length=200)),
                ('study_mode', models.CharField(default='none', max_length=200)),
                ('attendance', models.CharField(default='none', max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('description', models.CharField(default='none', max_length=20000)),
                ('ib_requirements', models.IntegerField(default=0)),
                ('ib_requirements_long', models.CharField(default='none', max_length=500)),
                ('tuition_fee_euro', models.FloatField(default=0, max_length=200)),
                ('link', models.CharField(default='none', max_length=500)),
                ('discipline', models.CharField(default='none', max_length=200)),
                ('blurred', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
