# Generated by Django 5.0.6 on 2024-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_uni_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_entries',
            old_name='total_entries',
            new_name='total_entries_home',
        ),
        migrations.AddField(
            model_name='total_entries',
            name='full_journey',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='total_entries',
            name='unique_ip_addresses',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
