# Generated by Django 5.0.6 on 2024-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0067_rename_total_entries_total_entries_total_entries_home_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="total_entries",
            old_name="unique_ip_addresses",
            new_name="unique_ip_addresses_all",
        ),
        migrations.AddField(
            model_name="total_entries",
            name="unique_ip_addresses_all_no_db",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AddField(
            model_name="total_entries",
            name="unique_ip_addresses_home",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
