# Generated by Django 5.0.6 on 2024-12-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_rename_unique_ip_addresses_total_entries_unique_ip_addresses_all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Past_Paper_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='null', max_length=100)),
                ('time_zone', models.CharField(default='null', max_length=100)),
                ('paper', models.CharField(default='null', max_length=100)),
                ('question', models.CharField(default='null', max_length=100)),
                ('topic1', models.CharField(default='null', max_length=100)),
                ('topic2', models.CharField(default='null', max_length=100)),
                ('topic3', models.CharField(default='null', max_length=100)),
                ('link', models.CharField(default='null', max_length=200)),
            ],
        ),
    ]
