# Generated by Django 5.0.6 on 2024-12-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_past_paper_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_paper_videos',
            name='month',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='past_paper_videos',
            name='year',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
