# Generated by Django 5.0.6 on 2024-12-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_past_paper_videos_month_past_paper_videos_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_paper_videos',
            name='abbreviation_month',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='past_paper_videos',
            name='abbreviation_year',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
