# Generated by Django 5.0.6 on 2025-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0071_past_paper_videos_abbreviation_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Response_Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('math', models.CharField(max_length=255)),
                ('science', models.CharField(max_length=255)),
                ('subject_3', models.CharField(max_length=255)),
                ('subject_4', models.CharField(max_length=255)),
                ('subject_5', models.CharField(max_length=255)),
                ('subject_6', models.CharField(max_length=255)),
            ],
        ),
    ]
