# Generated by Django 5.0.6 on 2025-01-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_survey_response_subjects'),
    ]

    operations = [

    ]
