# Generated by Django 5.0.6 on 2025-01-06 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_survey_response_subjects_date'),
    ]

    operations = [
    ]
