# Generated by Django 5.0.6 on 2025-01-06 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_alter_survey_response_subjects_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_response_subjects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
