# Generated by Django 5.0.6 on 2025-01-10 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0075_survey_response_subjects_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Generated_Number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                ("number", models.CharField(max_length=255)),
            ],
        ),
    ]
