# Generated by Django 5.0.6 on 2025-01-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_qr_code_free_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code_free_call',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
