# Generated by Django 5.0.6 on 2025-02-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_past_paper_videos_ai_hl'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='code',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
