# Generated by Django 5.0.6 on 2025-02-03 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_users_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium_members',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
