# Generated by Django 5.0.6 on 2025-02-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_premium_members_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium_members',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
