# Generated by Django 5.0.6 on 2025-02-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0082_alter_premium_members_subscription_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Past_Paper_Videos_AA_SL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='null', max_length=100)),
                ('month', models.CharField(default='null', max_length=100)),
                ('year', models.CharField(default='null', max_length=100)),
                ('abbreviation_month', models.CharField(default='null', max_length=100)),
                ('abbreviation_year', models.CharField(default='null', max_length=100)),
                ('time_zone', models.CharField(default='null', max_length=100)),
                ('paper', models.CharField(default='null', max_length=100)),
                ('question', models.CharField(default='null', max_length=100)),
                ('topic1', models.CharField(default='null', max_length=100)),
                ('topic2', models.CharField(default='null', max_length=100)),
                ('topic3', models.CharField(default='null', max_length=100)),
                ('link', models.CharField(default='null', max_length=200)),
            ],
        ),
    ]
