# Generated by Django 5.0.6 on 2025-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0083_past_paper_videos_aa_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='codes_used',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='personal_code',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
