# Generated by Django 5.0.6 on 2025-02-28 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_users_codes_used_users_personal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fillout_Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('first_name', models.CharField(max_length=255)),
                ('math_score', models.CharField(max_length=255)),
            ],
        ),
    ]
