# Generated by Django 5.0.6 on 2025-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0085_fillout_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillout_survey',
            name='math_score',
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='economics_score',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='engineering_score',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='law_score',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='medicine_score',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
