# Generated by Django 5.0.6 on 2025-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0086_remove_fillout_survey_math_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillout_survey',
            name='email',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
