# Generated by Django 5.0.6 on 2025-03-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0087_fillout_survey_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillout_survey',
            name='architecture_score',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='creative_score',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='funding',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='grades',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='humanities_score',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='sciences_score',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='soc_sciences_score',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='uni_cost',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='uni_language',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='fillout_survey',
            name='uni_setting',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
