# Generated by Django 5.0.6 on 2025-03-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0088_fillout_survey_architecture_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_database',
            name='discipline_survey',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
