# Generated by Django 5.0.6 on 2025-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0089_uni_database_discipline_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Math_AI_SL_Questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('paper', models.CharField(max_length=50)),
                ('video', models.TextField()),
                ('chapter', models.CharField(max_length=100)),
            ],
        ),
    ]
