# Generated by Django 5.0.6 on 2025-05-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_math_ai_sl_questionbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math_ai_sl_questionbank',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10),
        ),
    ]
