# Generated by Django 5.0.6 on 2025-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0091_alter_math_ai_sl_questionbank_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math_ai_sl_questionbank',
            name='chapter',
            field=models.CharField(choices=[('number_skills', 'Number Skills'), ('seq_series', 'Sequences & Series'), ('systems_lin_eq', 'Systems of Linear Equations'), ('lin_eq_graphs', 'Linear Equations & Graphs')], max_length=200),
        ),
        migrations.AlterField(
            model_name='math_ai_sl_questionbank',
            name='paper',
            field=models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2'), ('paper3', 'Paper 3')], max_length=20),
        ),
    ]
