# Generated by Django 5.0.6 on 2025-05-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0092_alter_math_ai_sl_questionbank_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='math_ai_sl_questionbank',
            name='marks',
            field=models.TextField(default='null'),
        ),
    ]
