# Generated by Django 5.0.6 on 2025-05-29 12:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0093_math_ai_sl_questionbank_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math_ai_sl_questionbank',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
