# Generated by Django 5.0.6 on 2025-05-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0094_alter_math_ai_sl_questionbank_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math_ai_sl_questionbank',
            name='question',
            field=models.TextField(),
        ),
    ]
