# Generated by Django 5.0.6 on 2025-06-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0095_alter_math_ai_sl_questionbank_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Math_AI_HL_Questionbank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "paper",
                    models.CharField(
                        choices=[
                            ("paper1", "Paper 1"),
                            ("paper2", "Paper 2"),
                            ("paper3", "Paper 3"),
                        ],
                        max_length=20,
                    ),
                ),
                ("video", models.TextField()),
                (
                    "chapter",
                    models.CharField(
                        choices=[
                            ("number_skills", "Number Skills"),
                            ("seq_series", "Sequences & Series"),
                            ("systems_lin_eq", "Systems of Linear Equations"),
                            ("lin_eq_graphs", "Linear Equations & Graphs"),
                        ],
                        max_length=200,
                    ),
                ),
                ("marks", models.TextField(default="null")),
            ],
        ),
    ]
