# Generated by Django 5.0.6 on 2025-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0096_math_ai_hl_questionbank"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="avatar",
            field=models.CharField(default="avatar1.png", max_length=200),
        ),
    ]
