# Generated by Django 5.0.6 on 2025-06-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0097_users_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="school_name",
            field=models.CharField(default="No School Name Given", max_length=200),
        ),
    ]
