# Generated by Django 5.0.6 on 2025-06-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0098_users_school_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="avatar",
            field=models.CharField(default="1.png", max_length=200),
        ),
    ]
