# Generated by Django 5.0.6 on 2025-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0099_alter_users_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="avatar",
            field=models.CharField(default="avatar1.png", max_length=200),
        ),
    ]
