# Generated by Django 5.0.6 on 2025-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0100_alter_users_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_journey",
            name="country",
            field=models.CharField(default="null", max_length=255),
        ),
        migrations.AddField(
            model_name="user_journey",
            name="device",
            field=models.CharField(default="null", max_length=255),
        ),
    ]
