# Generated by Django 5.0.6 on 2025-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0101_user_journey_country_user_journey_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="exam_session",
            field=models.CharField(default="None", max_length=200),
        ),
    ]
