# Generated by Django 5.0.6 on 2025-06-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0102_users_exam_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="math_ai_hl_questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("number_skills", "Number Skills"),
                    ("seq_series", "Sequences & Series"),
                    ("systems_lin_eq", "Systems of Linear Equations"),
                    ("lin_eq_graphs", "Linear Equations & Graphs"),
                    ("hypothesis_testing", "Hypothesis Testing"),
                    ("trigonometry", "Trigonometry"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="math_ai_sl_questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("number_skills", "Number Skills"),
                    ("seq_series", "Sequences & Series"),
                    ("systems_lin_eq", "Systems of Linear Equations"),
                    ("lin_eq_graphs", "Linear Equations & Graphs"),
                    ("hypothesis_testing", "Hypothesis Testing"),
                    ("trigonometry", "Trigonometry"),
                    ("applications_of_functions", "Applications of Functions"),
                    ("voronoi_diagrams", "Voronoi Diagrams"),
                    ("probability", "Probability"),
                    ("properties_of_functions", "Properties of Functions"),
                    ("integration", "Integration"),
                    ("distributions", "Distributions"),
                    ("geometry_shapes", "Geometry & Shapes"),
                    ("descriptive_stats", "Descriptive Statistics"),
                    ("differentiation", "Differentiation"),
                    ("bivariate_statistics", "Bivariate Statistics"),
                ],
                max_length=200,
            ),
        ),
    ]
