# Generated by Django 5.0.6 on 2025-06-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0103_alter_math_ai_hl_questionbank_chapter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="math_ai_hl_questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("number_skills", "Number Skills"),
                    ("seq_series", "Sequences & Series"),
                    ("complex_numbers", "Complex Numbers"),
                    ("matrices", "Matrices"),
                    ("systems_lin_eq", "Systems of Linear Equations"),
                    ("lin_eq_graphs", "Linear Equations & Graphs"),
                    ("applications_of_functions", "Applications of Functions"),
                    ("properties_of_functions", "Properties of Functions"),
                    ("function_transformations", "Function Transformations"),
                    ("geometry_shapes", "Geometry & Shapes"),
                    ("trigonometry", "Trigonometry"),
                    ("trigonometric_functions", "Trigonometric Functions"),
                    ("geometric_transformations", "Geometric Transformations"),
                    ("voronoi_diagrams", "Voronoi Diagrams"),
                    ("graph_theory", "Graph Theory"),
                    ("vectors", "Vectors"),
                    ("descriptive_stats", "Descriptive Statistics"),
                    ("bivariate_statistics", "Bivariate Statistics"),
                    ("hypothesis_testing", "Hypothesis Testing"),
                    ("probability", "Probability"),
                    (
                        "estimations_and_confidence_intervals",
                        "Estimation & Confidence Intervals",
                    ),
                    ("distributions", "Distributions"),
                    ("integration", "Integration"),
                    ("differentiation", "Differentiation"),
                    ("kinematics", "Kinematics"),
                    ("differential_equations", "Differential Equations"),
                ],
                max_length=200,
            ),
        ),
    ]
