# Generated by Django 5.0.6 on 2025-06-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0104_alter_math_ai_hl_questionbank_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='math_ai_sl_questionbank',
            name='type',
            field=models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='free', max_length=10),
        ),
    ]
