# Generated by Django 5.0.6 on 2025-06-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0105_math_ai_sl_questionbank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='math_ai_hl_questionbank',
            name='type',
            field=models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='registered', max_length=10),
        ),
    ]
