# Generated by Django 5.0.6 on 2025-06-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0106_math_ai_hl_questionbank_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Math_AA_SL_Questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('paper', models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2'), ('paper3', 'Paper 3')], max_length=20)),
                ('video', models.TextField()),
                ('chapter', models.CharField(choices=[('number_skills', 'Number Skills'), ('seq_series', 'Sequences & Series'), ('complex_numbers', 'Complex Numbers'), ('matrices', 'Matrices'), ('systems_lin_eq', 'Systems of Linear Equations'), ('lin_eq_graphs', 'Linear Equations & Graphs'), ('applications_of_functions', 'Applications of Functions'), ('properties_of_functions', 'Properties of Functions'), ('function_transformations', 'Function Transformations'), ('geometry_shapes', 'Geometry & Shapes'), ('trigonometry', 'Trigonometry'), ('trigonometric_functions', 'Trigonometric Functions'), ('geometric_transformations', 'Geometric Transformations'), ('voronoi_diagrams', 'Voronoi Diagrams'), ('graph_theory', 'Graph Theory'), ('vectors', 'Vectors'), ('descriptive_stats', 'Descriptive Statistics'), ('bivariate_statistics', 'Bivariate Statistics'), ('hypothesis_testing', 'Hypothesis Testing'), ('probability', 'Probability'), ('estimations_and_confidence_intervals', 'Estimation & Confidence Intervals'), ('distributions', 'Distributions'), ('integration', 'Integration'), ('differentiation', 'Differentiation'), ('kinematics', 'Kinematics'), ('differential_equations', 'Differential Equations')], max_length=200)),
                ('marks', models.TextField(default='null')),
                ('type', models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='registered', max_length=10)),
            ],
        ),
    ]
