# Generated by Django 5.0.6 on 2025-06-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0108_alter_math_aa_sl_questionbank_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Math_AA_HL_Questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('paper', models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2'), ('paper3', 'Paper 3')], max_length=20)),
                ('video', models.TextField()),
                ('chapter', models.CharField(choices=[('seq_series', 'Sequences & Series'), ('exp_and_logs', 'Exponentials and Logarithms'), ('binomial_expansion', 'Binomial Expansion'), ('proofs', 'Proofs'), ('properties_of_functions', 'Properties of Functions'), ('quadratic_functions', 'Quadratic Functions'), ('rational_functions', 'Rational Functions'), ('exp_and_logs_functions', 'Exponential and Logarithmic Functions'), ('function_transformations', 'Function Transformations'), ('geometry', 'Geometry'), ('trig_functions', 'Trigonometric Functions'), ('statistics', 'Statistics'), ('bivariate_stats', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('integration', 'Integration'), ('differentiation', 'Differentiation'), ('kinematics', 'Kinematics')], max_length=200)),
                ('marks', models.TextField(default='null')),
                ('type', models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='registered', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='math_aa_sl_questionbank',
            name='chapter',
            field=models.CharField(choices=[('seq_series', 'Sequences & Series'), ('exp_and_logs', 'Exponentials and Logarithms'), ('binomial_expansion', 'Binomial Expansion'), ('proofs', 'Proofs'), ('properties_of_functions', 'Properties of Functions'), ('quadratic_functions', 'Quadratic Functions'), ('rational_functions', 'Rational Functions'), ('exp_and_logs_functions', 'Exponential and Logarithmic Functions'), ('function_transformations', 'Function Transformations'), ('geometry', 'Geometry'), ('trig_functions', 'Trigonometric Functions'), ('statistics', 'Statistics'), ('bivariate_stats', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('integration', 'Integration'), ('differentiation', 'Differentiation'), ('kinematics', 'Kinematics')], max_length=200),
        ),
    ]
