# Generated by Django 5.0.6 on 2025-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0110_biology_sl_questionbank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology_sl_questionbank',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='biology_sl_questionbank',
            name='marks',
            field=models.TextField(default='4'),
        ),
    ]
