# Generated by Django 5.0.6 on 2025-06-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0111_alter_biology_sl_questionbank_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology_sl_questionbank',
            name='chapter',
            field=models.CharField(choices=[('water', 'Water'), ('nucleic_acids', 'Nucleic Acids'), ('cell_structure', 'Cell Structure'), ('diversity_of_organisms', 'Diversity of Organisms'), ('evolution_and_speciation', 'Evolution and Speciation'), ('conservation_of_biodiversity', 'Conservation of Biodiversity'), ('carbohydrates_and_lipids', 'Carbohydrates & Lipids'), ('proteins', 'Proteins'), ('membranes_and_membrane_transport', 'Membranes and Membrane Transport'), ('organelles_and_compartmentalization', 'Organelles and Compartmentalization'), ('cell_specialization', 'Cell Specialization'), ('gas_exchange', 'Gas Exchange'), ('transport', 'Transport'), ('adaptation_to_environment', 'Adaptation to Environment'), ('ecological_niches', 'Ecological Niches')], max_length=200),
        ),
    ]
