# Generated by Django 5.0.6 on 2025-06-23 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0112_alter_biology_sl_questionbank_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinars_Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Smith', max_length=255)),
                ('description', models.CharField(default='null', max_length=2000)),
                ('webinar_date', models.DateTimeField()),
                ('image_mentor', models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='mateusz2.png', max_length=100)),
                ('image_main', models.CharField(default='mateusz2.png', max_length=1000)),
                ('link', models.CharField(default='https://ik.imagekit.io/zwtwkrbaj/Biology%20SL/Water/q1.png?updatedAt=1750678394169', max_length=2000)),
            ],
        ),
    ]
