# Generated by Django 5.0.6 on 2025-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0113_webinars_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars_live',
            name='title',
            field=models.CharField(default='Studying in the UK', max_length=2000),
        ),
        migrations.AlterField(
            model_name='webinars_live',
            name='description',
            field=models.CharField(default='In this webinar we will described what it is like to study in the UK.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='webinars_live',
            name='image_main',
            field=models.CharField(default='https://ik.imagekit.io/zwtwkrbaj/Biology%20SL/Water/q1.png?updatedAt=1750678394169', max_length=1000),
        ),
        migrations.AlterField(
            model_name='webinars_live',
            name='link',
            field=models.CharField(default='meet.google.com/cpp-whaa-xgi', max_length=2000),
        ),
    ]
