# Generated by Django 5.0.6 on 2025-06-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0114_webinars_live_title_alter_webinars_live_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinars_live',
            name='image_mentor',
            field=models.CharField(choices=[('fiorella2.jpg', 'Fiorella'), ('registered', 'registered'), ('premium', 'premium')], default='mateusz2.png', max_length=100),
        ),
    ]
