# Generated by Django 5.0.6 on 2025-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0115_alter_webinars_live_image_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinars_live',
            name='image_main',
            field=models.CharField(default='https://ik.imagekit.io/zwtwkrbaj/Webinars%20Live/Thumbnail-2.png?updatedAt=1750690040092', max_length=1000),
        ),
        migrations.AlterField(
            model_name='webinars_live',
            name='image_mentor',
            field=models.CharField(choices=[('fiorella2.jpg', 'Fiorella'), ('mateusz.jpg', 'Mateusz'), ('mike2.jpg', 'Michal'), ('anubha.png', 'Anubha')], default='mateusz2.png', max_length=100),
        ),
    ]
