# Generated by Django 5.0.6 on 2025-06-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0116_alter_webinars_live_image_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physics_SL_Questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('paper', models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2'), ('paper3', 'Paper 3')], max_length=20)),
                ('video', models.TextField()),
                ('chapter', models.CharField(choices=[('kinematics', 'Kinematics'), ('forces_and_momentum', 'Forces and Momentum'), ('work_energy_power', 'Work, Energy, and Power'), ('simple_harmonic_motion', 'Simple Harmonic Motion'), ('wave_motion', 'Wave Motion'), ('electric_currents', 'Electric Currents'), ('electric_circuits', 'Electric Circuits'), ('electric_fields', 'Electric Fields')], max_length=200)),
                ('marks', models.TextField(default='null')),
                ('type', models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='registered', max_length=10)),
            ],
        ),
    ]
