# Generated by Django 5.0.6 on 2025-06-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0117_physics_sl_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='physics_sl_questionbank',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='physics_sl_questionbank',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='physics_sl_questionbank',
            name='marks',
            field=models.TextField(default='4'),
        ),
        migrations.AlterField(
            model_name='physics_sl_questionbank',
            name='paper',
            field=models.CharField(choices=[('paper1A', 'Paper 1A'), ('paper1B', 'Paper 1B'), ('paper2', 'Paper 2')], default='paper1A', max_length=20),
        ),
        migrations.AlterField(
            model_name='physics_sl_questionbank',
            name='video',
            field=models.TextField(default='none'),
        ),
    ]
