# Generated by Django 5.0.6 on 2025-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0118_physics_sl_questionbank_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physics_sl_questionbank',
            name='paper',
            field=models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2')], default='paper1A', max_length=20),
        ),
    ]
