# Generated by Django 5.0.6 on 2025-06-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0119_alter_physics_sl_questionbank_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology_sl_questionbank',
            name='marks',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='physics_sl_questionbank',
            name='marks',
            field=models.TextField(default='1'),
        ),
    ]
