# Generated by Django 5.0.6 on 2025-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0120_alter_biology_sl_questionbank_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physics_sl_questionbank',
            name='chapter',
            field=models.CharField(choices=[('kinematics', 'Kinematics'), ('forces_and_momentum', 'Forces and Momentum'), ('work_energy_power', 'Work, Energy, and Power'), ('simple_harmonic_motion', 'Simple Harmonic Motion'), ('wave_motion', 'Wave Motion'), ('electric_currents', 'Electric Currents'), ('electric_circuits', 'Electric Circuits'), ('electric_fields', 'Electric Fields'), ('simple_harmonic_motion', 'Simple Harmonic Motion'), ('wave_model', 'Wave Model'), ('wave_phenomena', 'Wave Phenomena'), ('standing_waves', 'Standing Wave and Resonance'), ('doppler_effect', 'Doppler Effect'), ('gravitational_fields', 'Gravitational Fields'), ('electric_magnetic_fields', 'Electric and Magnetic Fields'), ('motion_in_fields', 'Motion in Electromagnetic Fields'), ('structure_atom', 'Structure of the Atom'), ('radioactive_decay', 'Radioactive Decay'), ('fission', 'Fission'), ('fusion_and_stars', 'Fusion and Stars')], max_length=200),
        ),
    ]
