# Generated by Django 5.0.6 on 2025-06-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0122_alter_physics_sl_questionbank_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Past_Paper_Videos_AA_HL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('May', 'May'), ('November', 'November')], default='May', max_length=10)),
                ('year', models.CharField(default='2024', max_length=10)),
                ('time_zone', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='1', max_length=10)),
                ('paper', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=10)),
                ('question', models.CharField(default='1', max_length=100)),
                ('abbreviation_month', models.CharField(default='null', max_length=100)),
                ('abbreviation_year', models.CharField(default='null', max_length=100)),
                ('topic1', models.CharField(default='null', max_length=100)),
                ('topic2', models.CharField(default='null', max_length=100)),
                ('topic3', models.CharField(default='null', max_length=100)),
                ('link', models.CharField(default='null', max_length=200)),
            ],
        ),
    ]
