# Generated by Django 5.0.6 on 2025-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0124_alter_past_paper_videos_aa_hl_topic1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_paper_videos_aa_hl',
            name='topic1',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('exp_and_logs', 'Exponentials and Logarithms'), ('binomial_expansion', 'Binomial Expansion'), ('proofs', 'Proofs'), ('counting_principles', 'Counting Principles'), ('complex_numbers', 'Complex Numbers'), ('systems_of_equations', 'Systems of Equations'), ('properties_of_functions', 'Properties of Functions'), ('quadratic_functions', 'Quadratic Functions'), ('rational_functions', 'Rational Functions'), ('exp_and_logs_functions', 'Exponential and Logarithmic Functions'), ('function_transformations', 'Function Transformations'), ('polynomials', 'Polynomials'), ('modulus_inequalities', 'Modulus Inequalities'), ('geometry', 'Geometry'), ('trig_functions', 'Trigonometric Functions'), ('vectors', 'Vectors'), ('statistics', 'Statistics'), ('bivariate_stats', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('integral_calculus', 'Integral Calculus'), ('differential_calculus', 'Differential Calculus'), ('kinematics', 'Kinematics'), ('maclaurin_series', 'MacLaurin Series'), ('differential_equations', 'Differential Equations')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_aa_hl',
            name='topic2',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('exp_and_logs', 'Exponentials and Logarithms'), ('binomial_expansion', 'Binomial Expansion'), ('proofs', 'Proofs'), ('counting_principles', 'Counting Principles'), ('complex_numbers', 'Complex Numbers'), ('systems_of_equations', 'Systems of Equations'), ('properties_of_functions', 'Properties of Functions'), ('quadratic_functions', 'Quadratic Functions'), ('rational_functions', 'Rational Functions'), ('exp_and_logs_functions', 'Exponential and Logarithmic Functions'), ('function_transformations', 'Function Transformations'), ('polynomials', 'Polynomials'), ('modulus_inequalities', 'Modulus Inequalities'), ('geometry', 'Geometry'), ('trig_functions', 'Trigonometric Functions'), ('vectors', 'Vectors'), ('statistics', 'Statistics'), ('bivariate_stats', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('integral_calculus', 'Integral Calculus'), ('differential_calculus', 'Differential Calculus'), ('kinematics', 'Kinematics'), ('maclaurin_series', 'MacLaurin Series'), ('differential_equations', 'Differential Equations')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_aa_hl',
            name='topic3',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('exp_and_logs', 'Exponentials and Logarithms'), ('binomial_expansion', 'Binomial Expansion'), ('proofs', 'Proofs'), ('counting_principles', 'Counting Principles'), ('complex_numbers', 'Complex Numbers'), ('systems_of_equations', 'Systems of Equations'), ('properties_of_functions', 'Properties of Functions'), ('quadratic_functions', 'Quadratic Functions'), ('rational_functions', 'Rational Functions'), ('exp_and_logs_functions', 'Exponential and Logarithmic Functions'), ('function_transformations', 'Function Transformations'), ('polynomials', 'Polynomials'), ('modulus_inequalities', 'Modulus Inequalities'), ('geometry', 'Geometry'), ('trig_functions', 'Trigonometric Functions'), ('vectors', 'Vectors'), ('statistics', 'Statistics'), ('bivariate_stats', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('integral_calculus', 'Integral Calculus'), ('differential_calculus', 'Differential Calculus'), ('kinematics', 'Kinematics'), ('maclaurin_series', 'MacLaurin Series'), ('differential_equations', 'Differential Equations')], default='null', max_length=100),
        ),
    ]
