# Generated by Django 5.0.6 on 2025-06-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0125_alter_past_paper_videos_aa_hl_topic1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_paper_videos_aa_hl',
            name='session',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_aa_hl',
            name='topic1',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_aa_hl',
            name='topic2',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_aa_hl',
            name='topic3',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
