# Generated by Django 5.0.6 on 2025-06-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0128_alter_past_paper_videos_aa_sl_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_paper_videos_aa_sl',
            name='topic1',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('exp_and_logs', 'Exponentials and Logarithms'), ('binomial_expansion', 'Binomial Expansion'), ('proofs', 'Proofs'), ('properties_of_functions', 'Properties of Functions'), ('quadratic_functions', 'Quadratic Functions'), ('rational_functions', 'Rational Functions'), ('exp_and_logs_functions', 'Exponential and Logarithmic Functions'), ('function_transformations', 'Function Transformations'), ('geometry', 'Geometry'), ('trig_functions', 'Trigonometric Functions'), ('statistics', 'Statistics'), ('bivariate_stats', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('integral_calculus', 'Integral Calculus'), ('differential_calculus', 'Differential Calculus'), ('kinematics', 'Kinematics')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_aa_sl',
            name='topic2',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('exp_and_logs', 'Exponentials and Logarithms'), ('binomial_expansion', 'Binomial Expansion'), ('proofs', 'Proofs'), ('properties_of_functions', 'Properties of Functions'), ('quadratic_functions', 'Quadratic Functions'), ('rational_functions', 'Rational Functions'), ('exp_and_logs_functions', 'Exponential and Logarithmic Functions'), ('function_transformations', 'Function Transformations'), ('geometry', 'Geometry'), ('trig_functions', 'Trigonometric Functions'), ('statistics', 'Statistics'), ('bivariate_stats', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('integral_calculus', 'Integral Calculus'), ('differential_calculus', 'Differential Calculus'), ('kinematics', 'Kinematics')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_aa_sl',
            name='topic3',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('exp_and_logs', 'Exponentials and Logarithms'), ('binomial_expansion', 'Binomial Expansion'), ('proofs', 'Proofs'), ('properties_of_functions', 'Properties of Functions'), ('quadratic_functions', 'Quadratic Functions'), ('rational_functions', 'Rational Functions'), ('exp_and_logs_functions', 'Exponential and Logarithmic Functions'), ('function_transformations', 'Function Transformations'), ('geometry', 'Geometry'), ('trig_functions', 'Trigonometric Functions'), ('statistics', 'Statistics'), ('bivariate_stats', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('integral_calculus', 'Integral Calculus'), ('differential_calculus', 'Differential Calculus'), ('kinematics', 'Kinematics')], default='null', max_length=100),
        ),
    ]
