# Generated by Django 5.0.6 on 2025-06-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0129_alter_past_paper_videos_aa_sl_topic1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physics_HL_Questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('paper', models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2')], default='paper1A', max_length=20)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=10)),
                ('video', models.TextField(default='none')),
                ('chapter', models.CharField(choices=[('kinematics', 'Kinematics'), ('forces_and_momentum', 'Forces and Momentum'), ('work_energy_power', 'Work, Energy, and Power'), ('thermal_energy', 'Thermal Energy'), ('greenhouse_effect', 'Greenhouse Effect'), ('ideal_gas_model', 'Ideal Gas Model'), ('electric_circuits', 'Electric Circuits'), ('simple_harmonic_motion', 'Simple Harmonic Motion'), ('wave_model', 'Wave Model'), ('wave_phenomena', 'Wave Phenomena'), ('standing_waves', 'Standing Wave and Resonance'), ('doppler_effect', 'Doppler Effect'), ('gravitational_fields', 'Gravitational Fields'), ('electric_magnetic_fields', 'Electric and Magnetic Fields'), ('motion_in_fields', 'Motion in Electromagnetic Fields'), ('structure_atom', 'Structure of the Atom'), ('radioactive_decay', 'Radioactive Decay'), ('fission', 'Fission'), ('fusion_and_stars', 'Fusion and Stars')], max_length=200)),
                ('marks', models.TextField(default='1')),
                ('type', models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='registered', max_length=10)),
            ],
        ),
    ]
