# Generated by Django 5.0.6 on 2025-06-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0130_physics_hl_questionbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physics_hl_questionbank',
            name='chapter',
            field=models.CharField(choices=[('kinematics', 'Kinematics'), ('forces_and_momentum', 'Forces and Momentum'), ('work_energy_power', 'Work, Energy, and Power'), ('rigid_body_mechanics', 'Rigid Body Mechanics'), ('galilean_and_special_relativity', 'Galilean and Special Relativity'), ('thermal_energy', 'Thermal Energy'), ('greenhouse_effect', 'Greenhouse Effect'), ('ideal_gas_model', 'Ideal Gas Model'), ('thermodynamics', 'Thermodynamics'), ('electric_circuits', 'Electric Circuits'), ('simple_harmonic_motion', 'Simple Harmonic Motion'), ('wave_model', 'Wave Model'), ('wave_phenomena', 'Wave Phenomena'), ('standing_waves', 'Standing Wave and Resonance'), ('doppler_effect', 'Doppler Effect'), ('gravitational_fields', 'Gravitational Fields'), ('electric_magnetic_fields', 'Electric and Magnetic Fields'), ('motion_in_fields', 'Motion in Electromagnetic Fields'), ('induction', 'Induction'), ('structure_atom', 'Structure of the Atom'), ('quantum_physics', 'Quantum Physics'), ('radioactive_decay', 'Radioactive Decay'), ('fission', 'Fission'), ('fusion_and_stars', 'Fusion and Stars')], max_length=200),
        ),
    ]
