# Generated by Django 5.0.6 on 2025-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0131_alter_physics_hl_questionbank_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='month',
            field=models.CharField(choices=[('May', 'May'), ('November', 'November')], default='May', max_length=10),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='paper',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='question',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='time_zone',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='topic1',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('complex_numbers', 'Complex Numbers'), ('matrices', 'Matrices'), ('systems_of_equations', 'Systems of Linear Equations'), ('linear_equations_graphs', 'Linear Equations & Graphs'), ('application_of_functions', 'Application of Functions'), ('properties_of_functions', 'Properties of Functions'), ('function_transformations', 'Function Transformations'), ('trigonometry', 'Trigonometry'), ('trigonometric_functions', 'Trigonometric Functions'), ('gemoetric_transformations', 'Geometric Transformations'), ('vectors', 'Vectors'), ('graph_theory', 'Graph Theory'), ('descriptive_statistics', 'Descriptive Statistics'), ('bivariate_statistics', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('hypothesis_testing', 'Hypothesis Testing'), ('confidence_intervals', 'Estimations & Confidence Intervals'), ('differentiation', 'Differentiation'), ('integration', 'Integration'), ('differential_equations', 'Differential Equations'), ('kinematics', 'Kinematics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='topic2',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('complex_numbers', 'Complex Numbers'), ('matrices', 'Matrices'), ('systems_of_equations', 'Systems of Linear Equations'), ('linear_equations_graphs', 'Linear Equations & Graphs'), ('application_of_functions', 'Application of Functions'), ('properties_of_functions', 'Properties of Functions'), ('function_transformations', 'Function Transformations'), ('trigonometry', 'Trigonometry'), ('trigonometric_functions', 'Trigonometric Functions'), ('gemoetric_transformations', 'Geometric Transformations'), ('vectors', 'Vectors'), ('graph_theory', 'Graph Theory'), ('descriptive_statistics', 'Descriptive Statistics'), ('bivariate_statistics', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('hypothesis_testing', 'Hypothesis Testing'), ('confidence_intervals', 'Estimations & Confidence Intervals'), ('differentiation', 'Differentiation'), ('integration', 'Integration'), ('differential_equations', 'Differential Equations'), ('kinematics', 'Kinematics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='topic3',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('complex_numbers', 'Complex Numbers'), ('matrices', 'Matrices'), ('systems_of_equations', 'Systems of Linear Equations'), ('linear_equations_graphs', 'Linear Equations & Graphs'), ('application_of_functions', 'Application of Functions'), ('properties_of_functions', 'Properties of Functions'), ('function_transformations', 'Function Transformations'), ('trigonometry', 'Trigonometry'), ('trigonometric_functions', 'Trigonometric Functions'), ('gemoetric_transformations', 'Geometric Transformations'), ('vectors', 'Vectors'), ('graph_theory', 'Graph Theory'), ('descriptive_statistics', 'Descriptive Statistics'), ('bivariate_statistics', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('hypothesis_testing', 'Hypothesis Testing'), ('confidence_intervals', 'Estimations & Confidence Intervals'), ('differentiation', 'Differentiation'), ('integration', 'Integration'), ('differential_equations', 'Differential Equations'), ('kinematics', 'Kinematics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='year',
            field=models.CharField(default='2024', max_length=10),
        ),
    ]
