# Generated by Django 5.0.6 on 2025-07-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0133_alter_past_paper_videos_ai_hl_topic1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='topic1',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('complex_numbers', 'Complex Numbers'), ('matrices', 'Matrices'), ('systems_of_equations', 'Systems of Linear Equations'), ('linear_equations_graphs', 'Linear Equations & Graphs'), ('application_of_functions', 'Application of Functions'), ('properties_of_functions', 'Properties of Functions'), ('function_transformations', 'Function Transformations'), ('trigonometry', 'Trigonometry'), ('trigonometric_functions', 'Trigonometric Functions'), ('gemoetric_transformations', 'Geometric Transformations'), ('voronoi_diagrams', 'Voronoi Diagrams'), ('vectors', 'Vectors'), ('graph_theory', 'Graph Theory'), ('descriptive_statistics', 'Descriptive Statistics'), ('bivariate_statistics', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('hypothesis_testing', 'Hypothesis Testing'), ('confidence_intervals', 'Estimations & Confidence Intervals'), ('differentiation', 'Differentiation'), ('integration', 'Integration'), ('differential_equations', 'Differential Equations'), ('kinematics', 'Kinematics')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='topic2',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('complex_numbers', 'Complex Numbers'), ('matrices', 'Matrices'), ('systems_of_equations', 'Systems of Linear Equations'), ('linear_equations_graphs', 'Linear Equations & Graphs'), ('application_of_functions', 'Application of Functions'), ('properties_of_functions', 'Properties of Functions'), ('function_transformations', 'Function Transformations'), ('trigonometry', 'Trigonometry'), ('trigonometric_functions', 'Trigonometric Functions'), ('gemoetric_transformations', 'Geometric Transformations'), ('voronoi_diagrams', 'Voronoi Diagrams'), ('vectors', 'Vectors'), ('graph_theory', 'Graph Theory'), ('descriptive_statistics', 'Descriptive Statistics'), ('bivariate_statistics', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('hypothesis_testing', 'Hypothesis Testing'), ('confidence_intervals', 'Estimations & Confidence Intervals'), ('differentiation', 'Differentiation'), ('integration', 'Integration'), ('differential_equations', 'Differential Equations'), ('kinematics', 'Kinematics')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos_ai_hl',
            name='topic3',
            field=models.CharField(choices=[('null', 'null'), ('seq_series', 'Sequences & Series'), ('complex_numbers', 'Complex Numbers'), ('matrices', 'Matrices'), ('systems_of_equations', 'Systems of Linear Equations'), ('linear_equations_graphs', 'Linear Equations & Graphs'), ('application_of_functions', 'Application of Functions'), ('properties_of_functions', 'Properties of Functions'), ('function_transformations', 'Function Transformations'), ('trigonometry', 'Trigonometry'), ('trigonometric_functions', 'Trigonometric Functions'), ('gemoetric_transformations', 'Geometric Transformations'), ('voronoi_diagrams', 'Voronoi Diagrams'), ('vectors', 'Vectors'), ('graph_theory', 'Graph Theory'), ('descriptive_statistics', 'Descriptive Statistics'), ('bivariate_statistics', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('hypothesis_testing', 'Hypothesis Testing'), ('confidence_intervals', 'Estimations & Confidence Intervals'), ('differentiation', 'Differentiation'), ('integration', 'Integration'), ('differential_equations', 'Differential Equations'), ('kinematics', 'Kinematics')], default='null', max_length=100),
        ),
    ]
