# Generated by Django 5.0.6 on 2025-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0136_comp_sci_sl_questionbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_sci_sl_questionbank',
            name='chapter',
            field=models.CharField(choices=[('system_fundamentals', 'System Fundamentals'), ('computer_organisation', 'Computer Organisation'), ('networks', 'Networks'), ('computational_thinking', 'Computational Thinking'), ('variables_input', 'Variables and Input'), ('if_statements', 'If Statements'), ('loops', 'Loops'), ('arrays', 'Arrays'), ('methods', 'Methods'), ('constructors', 'Constructors')], max_length=200),
        ),
    ]
