# Generated by Django 5.0.6 on 2025-07-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0137_alter_comp_sci_sl_questionbank_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_sci_sl_questionbank',
            name='paper',
            field=models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2')], default='paper1', max_length=20),
        ),
    ]
