# Generated by Django 5.0.6 on 2025-07-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0140_physics_sl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Physics_SL',
            new_name='Past_Paper_Videos_Physics_SL',
        ),
    ]
