# Generated by Django 5.0.6 on 2025-07-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0142_past_paper_videos_physics_hl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biology_HL_Questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('paper', models.CharField(choices=[('paper1A', 'Paper 1A'), ('paper1B', 'Paper 1B'), ('paper2', 'Paper 2')], default='paper1A', max_length=20)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=10)),
                ('video', models.TextField(default='none')),
                ('chapter', models.CharField(choices=[('water', 'Water'), ('nucleic_acids', 'Nucleic Acids'), ('cell_structure', 'Cell Structure'), ('diversity_of_organisms', 'Diversity of Organisms'), ('evolution_and_speciation', 'Evolution and Speciation'), ('conservation_of_biodiversity', 'Conservation of Biodiversity'), ('carbohydrates_and_lipids', 'Carbohydrates & Lipids'), ('proteins', 'Proteins'), ('membranes_and_membrane_transport', 'Membranes and Membrane Transport'), ('organelles_and_compartmentalization', 'Organelles and Compartmentalization'), ('cell_specialization', 'Cell Specialization'), ('gas_exchange', 'Gas Exchange'), ('transport', 'Transport'), ('adaptation_to_environment', 'Adaptation to Environment'), ('ecological_niches', 'Ecological Niches'), ('enzymes_metabolism', 'Enzymes and Metabolism'), ('cell_respiration', 'Cell Respiration'), ('photosynthesis', 'Photosynthesis'), ('neural_signaling', 'Neural Signaling'), ('integration_of_body_systems', 'Integration of Body Systems'), ('defence_against_disease', 'Defence Against Disease'), ('population_and_communities', 'Population and Communities'), ('transfer_of_energy', 'Transfer of Energy and Matter')], max_length=200)),
                ('marks', models.TextField(default='1')),
                ('type', models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='registered', max_length=10)),
            ],
        ),
    ]
