# Generated by Django 5.0.6 on 2025-07-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0144_alter_biology_hl_questionbank_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Sci_HL_Questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('paper', models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2')], default='paper1', max_length=20)),
                ('video', models.TextField(default='none')),
                ('chapter', models.CharField(choices=[('system_fundamentals', 'System Fundamentals'), ('computer_organisation', 'Computer Organisation'), ('networks', 'Networks'), ('computational_thinking', 'Computational Thinking'), ('resource_management', 'Resource Management'), ('abstract_data_structures', 'Abstract Data Structures'), ('variables_input', 'Variables and Input'), ('if_statements', 'If Statements'), ('loops', 'Loops'), ('arrays', 'Arrays'), ('methods', 'Methods'), ('constructors', 'Constructors')], max_length=200)),
                ('marks', models.TextField(default='1')),
                ('type', models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='registered', max_length=10)),
            ],
        ),
    ]
