# Generated by Django 5.0.6 on 2025-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0145_comp_sci_hl_questionbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology_sl_questionbank',
            name='chapter',
            field=models.CharField(choices=[('water', 'Water'), ('nucleic_acids', 'Nucleic Acids'), ('cell_structure', 'Cell Structure'), ('diversity_of_organisms', 'Diversity of Organisms'), ('evolution_and_speciation', 'Evolution and Speciation'), ('conservation_of_biodiversity', 'Conservation of Biodiversity'), ('carbohydrates_and_lipids', 'Carbohydrates & Lipids'), ('proteins', 'Proteins'), ('membranes_and_membrane_transport', 'Membranes and Membrane Transport'), ('organelles_and_compartmentalization', 'Organelles and Compartmentalization'), ('cell_specialization', 'Cell Specialization'), ('gas_exchange', 'Gas Exchange'), ('transport', 'Transport'), ('adaptation_to_environment', 'Adaptation to Environment'), ('ecological_niches', 'Ecological Niches'), ('enzymes_metabolism', 'Enzymes and Metabolism'), ('cell_respiration', 'Cell Respiration'), ('photosynthesis', 'Photosynthesis'), ('neural_signaling', 'Neural Signaling'), ('integration_of_body_systems', 'Integration of Body Systems'), ('defence_against_disease', 'Defence Against Disease'), ('population_and_communities', 'Population and Communities'), ('transfer_of_energy', 'Transfer of Energy and Matter'), ('dna_replication', 'DNA Replication'), ('protein_synthesis', 'Protein Synthesis'), ('mutations_editing', 'Mutations and Gene Editing'), ('natural_selection', 'Natural Selection'), ('inheritance', 'Inheritance'), ('climate_change', 'Climate Change'), ('water_potential', 'Water Potential'), ('cell_division', 'Cell Division'), ('reproduction', 'Reproduction'), ('stability_change', 'Stability & Change'), ('homeostasis', 'Homeostasis')], max_length=200),
        ),
    ]
