# Generated by Django 5.0.6 on 2025-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0147_alter_biology_hl_questionbank_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Math_AA_HL_Questionbank_Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('paper', models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2'), ('paper3', 'Paper 3')], max_length=20)),
                ('video', models.TextField()),
                ('chapter', models.CharField(choices=[('seq_series', 'Sequences & Series'), ('exp_and_logs', 'Exponentials and Logarithms'), ('binomial_expansion', 'Binomial Expansion'), ('proofs', 'Proofs'), ('counting_principles', 'Counting Principles'), ('complex_numbers', 'Complex Numbers'), ('systems_of_equations', 'Systems of Equations'), ('properties_of_functions', 'Properties of Functions'), ('quadratic_functions', 'Quadratic Functions'), ('rational_functions', 'Rational Functions'), ('exp_and_logs_functions', 'Exponential and Logarithmic Functions'), ('function_transformations', 'Function Transformations'), ('polynomials', 'Polynomials'), ('mod_inequalities', 'Mod & Inequalities'), ('geometry', 'Geometry'), ('trig_functions', 'Trigonometric Functions'), ('vectors', 'Vectors'), ('statistics', 'Statistics'), ('bivariate_stats', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('integral_calculus', 'Integral Calculus'), ('differential_calculus', 'Differential Calculus'), ('kinematics', 'Kinematics'), ('maclaurin_series', 'MacLaurin Series'), ('differential_equations', 'Differential Equations')], max_length=200)),
                ('marks', models.TextField(default='null')),
                ('type', models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='registered', max_length=10)),
            ],
        ),
    ]
