# Generated by Django 5.0.6 on 2025-08-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0148_math_aa_hl_questionbank_backup"),
    ]

    operations = [
        migrations.AddField(
            model_name="biology_sl_questionbank",
            name="sync_to_hl",
            field=models.BooleanField(
                default=True, help_text="Automatically sync this question to Biology HL"
            ),
        ),
    ]
