# Generated by Django 5.0.6 on 2025-08-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0149_biology_sl_questionbank_sync_to_hl"),
    ]

    operations = [
        migrations.AddField(
            model_name="biology_sl_questionbank",
            name="hl_question_id",
            field=models.IntegerField(
                blank=True, help_text="ID of corresponding HL question", null=True
            ),
        ),
    ]
