# Generated by Django 5.0.6 on 2025-08-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0150_biology_sl_questionbank_hl_question_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="physics_sl_questionbank",
            name="hl_question_id",
            field=models.IntegerField(
                blank=True, help_text="ID of corresponding HL question", null=True
            ),
        ),
        migrations.AddField(
            model_name="physics_sl_questionbank",
            name="sync_to_hl",
            field=models.BooleanField(
                default=True, help_text="Automatically sync this question to Physics HL"
            ),
        ),
    ]
