# Generated by Django 5.0.6 on 2025-08-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0152_alter_physics_sl_questionbank_paper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physics_hl_questionbank",
            name="paper",
            field=models.CharField(
                choices=[
                    ("paper1A", "Paper 1A"),
                    ("paper1B", "Paper 1B"),
                    ("paper2", "Paper 2"),
                ],
                default="paper1A",
                max_length=20,
            ),
        ),
    ]
