# Generated by Django 5.0.6 on 2025-08-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0154_math_ai_sl_questionbank_hl_question_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="math_aa_sl_questionbank",
            name="hl_question_id",
            field=models.IntegerField(
                blank=True, help_text="ID of corresponding HL question", null=True
            ),
        ),
        migrations.AddField(
            model_name="math_aa_sl_questionbank",
            name="sync_to_hl",
            field=models.BooleanField(
                default=True, help_text="Automatically sync this question to Math AA HL"
            ),
        ),
    ]
