# Generated by Django 5.0.6 on 2025-08-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0155_math_aa_sl_questionbank_hl_question_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="math_aa_hl_questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("seq_series", "Sequences & Series"),
                    ("exp_and_logs", "Exponentials and Logarithms"),
                    ("binomial_expansion", "Binomial Expansion"),
                    ("proofs", "Proofs"),
                    ("counting_principles", "Counting Principles"),
                    ("complex_numbers", "Complex Numbers"),
                    ("systems_of_equations", "Systems of Equations"),
                    ("properties_of_functions", "Properties of Functions"),
                    ("quadratic_functions", "Quadratic Functions"),
                    ("rational_functions", "Rational Functions"),
                    ("exp_and_logs_functions", "Exponential and Logarithmic Functions"),
                    ("function_transformations", "Function Transformations"),
                    ("polynomials", "Polynomials"),
                    ("mod_inequalities", "Mod & Inequalities"),
                    ("geometry", "Geometry"),
                    ("trig_functions", "Trigonometric Functions"),
                    ("vectors", "Vectors"),
                    ("statistics", "Statistics"),
                    ("bivariate_stats", "Bivariate Statistics"),
                    ("probability", "Probability"),
                    ("distributions", "Distributions"),
                    ("integration", "Integration"),
                    ("differentiation", "Differentiation"),
                    ("kinematics", "Kinematics"),
                    ("maclaurin_series", "MacLaurin Series"),
                    ("differential_equations", "Differential Equations"),
                ],
                max_length=200,
            ),
        ),
    ]
