# Generated by Django 5.0.6 on 2025-08-30 07:21

from django.db import migrations, models


def copy_chapter_to_chapter1(apps, schema_editor):
    """Copy existing chapter data to chapter1 field"""
    Math_AI_SL_Questionbank = apps.get_model('website', 'Math_AI_SL_Questionbank')
    for question in Math_AI_SL_Questionbank.objects.all():
        if question.chapter:
            question.chapter1 = question.chapter
            question.save()


def reverse_copy_chapter1_to_chapter(apps, schema_editor):
    """Reverse operation: copy chapter1 back to chapter"""
    Math_AI_SL_Questionbank = apps.get_model('website', 'Math_AI_SL_Questionbank')
    for question in Math_AI_SL_Questionbank.objects.all():
        if question.chapter1:
            question.chapter = question.chapter1
            question.save()


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0156_alter_math_aa_hl_questionbank_chapter"),
    ]

    operations = [
        # Add the new chapter fields
        migrations.AddField(
            model_name="math_ai_sl_questionbank",
            name="chapter1",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("number_skills", "Number Skills"),
                    ("seq_series", "Sequences & Series"),
                    ("systems_lin_eq", "Systems of Linear Equations"),
                    ("lin_eq_graphs", "Linear Equations & Graphs"),
                    ("hypothesis_testing", "Hypothesis Testing"),
                    ("trigonometry", "Trigonometry"),
                    ("applications_of_functions", "Applications of Functions"),
                    ("voronoi_diagrams", "Voronoi Diagrams"),
                    ("probability", "Probability"),
                    ("properties_of_functions", "Properties of Functions"),
                    ("integration", "Integration"),
                    ("distributions", "Distributions"),
                    ("geometry_shapes", "Geometry & Shapes"),
                    ("descriptive_stats", "Descriptive Statistics"),
                    ("differentiation", "Differentiation"),
                    ("bivariate_statistics", "Bivariate Statistics"),
                ],
                default="",
                help_text="Primary chapter",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="math_ai_sl_questionbank",
            name="chapter2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("number_skills", "Number Skills"),
                    ("seq_series", "Sequences & Series"),
                    ("systems_lin_eq", "Systems of Linear Equations"),
                    ("lin_eq_graphs", "Linear Equations & Graphs"),
                    ("hypothesis_testing", "Hypothesis Testing"),
                    ("trigonometry", "Trigonometry"),
                    ("applications_of_functions", "Applications of Functions"),
                    ("voronoi_diagrams", "Voronoi Diagrams"),
                    ("probability", "Probability"),
                    ("properties_of_functions", "Properties of Functions"),
                    ("integration", "Integration"),
                    ("distributions", "Distributions"),
                    ("geometry_shapes", "Geometry & Shapes"),
                    ("descriptive_stats", "Descriptive Statistics"),
                    ("differentiation", "Differentiation"),
                    ("bivariate_statistics", "Bivariate Statistics"),
                ],
                default="",
                help_text="Secondary chapter (optional)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="math_ai_sl_questionbank",
            name="chapter3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("number_skills", "Number Skills"),
                    ("seq_series", "Sequences & Series"),
                    ("systems_lin_eq", "Systems of Linear Equations"),
                    ("lin_eq_graphs", "Linear Equations & Graphs"),
                    ("hypothesis_testing", "Hypothesis Testing"),
                    ("trigonometry", "Trigonometry"),
                    ("applications_of_functions", "Applications of Functions"),
                    ("voronoi_diagrams", "Voronoi Diagrams"),
                    ("probability", "Probability"),
                    ("properties_of_functions", "Properties of Functions"),
                    ("integration", "Integration"),
                    ("distributions", "Distributions"),
                    ("geometry_shapes", "Geometry & Shapes"),
                    ("descriptive_stats", "Descriptive Statistics"),
                    ("differentiation", "Differentiation"),
                    ("bivariate_statistics", "Bivariate Statistics"),
                ],
                default="",
                help_text="Third chapter (optional)",
                max_length=200,
            ),
        ),
        # Copy data from old chapter field to chapter1
        migrations.RunPython(copy_chapter_to_chapter1, reverse_copy_chapter1_to_chapter),
        # Remove the old chapter field
        migrations.RemoveField(
            model_name="math_ai_sl_questionbank",
            name="chapter",
        ),
    ]
