# Generated by Django 5.0.6 on 2025-08-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0157_add_multi_chapter_support_math_ai_sl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='math_ai_sl_questionbank',
            old_name='chapter1',
            new_name='chapter',
        ),
    ]
