# Generated by Django 5.2.6 on 2025-09-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0161_tutorsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='homework_comments',
            field=models.TextField(blank=True, help_text='Homework assignments and comments', null=True),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='hours_taught',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of hours taught', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20),
        ),
    ]
