# Generated by Django 5.2.6 on 2025-09-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0162_tutorsession_homework_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='student_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='student_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='tutor_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='tutor_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
