# Generated by Django 5.2.6 on 2025-09-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0163_tutorsession_student_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('price_charged_to_parents', models.DecimalField(decimal_places=2, help_text='Price charged to parents per hour', max_digits=8)),
                ('price_given_to_tutor', models.DecimalField(decimal_places=2, help_text='Price given to tutor per hour', max_digits=8)),
                ('curriculum', models.CharField(blank=True, max_length=100)),
                ('subjects', models.CharField(blank=True, help_text='Subjects being tutored', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the student')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Hold', 'On Hold')], default='Active', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assigned_tutor', models.ForeignKey(limit_choices_to={'occupation': 'Tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='website.users')),
            ],
            options={
                'ordering': ['student_first_name', 'student_last_name'],
                'unique_together': {('student_first_name', 'student_last_name', 'parent_email')},
            },
        ),
    ]
