# Generated by Django 5.2.6 on 2025-09-21 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0164_studentmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmanagement',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='Link to existing student account in Users database', limit_choices_to={'occupation': 'Student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_management_profile', to='website.users'),
        ),
    ]
