# Generated by Django 5.2.6 on 2025-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0165_studentmanagement_linked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmanagement',
            name='price_charged_currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('USD', 'US Dollar ($)'), ('PLN', 'Polish Złoty (zł)')], default='EUR', help_text='Currency for price charged to parents', max_length=3),
        ),
        migrations.AddField(
            model_name='studentmanagement',
            name='price_given_currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('USD', 'US Dollar ($)'), ('PLN', 'Polish Złoty (zł)')], default='EUR', help_text='Currency for price given to tutor', max_length=3),
        ),
    ]
