# Generated by Django 5.2.6 on 2025-09-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0166_studentmanagement_price_charged_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='session_pdf',
            field=models.FileField(blank=True, help_text='Upload session materials (PDF format recommended)', null=True, upload_to='session_pdfs/%Y/%m/%d/'),
        ),
    ]
