# Generated by Django 5.2.6 on 2025-09-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0167_tutorsession_session_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='past_paper_videos_physics_hl',
            options={'verbose_name': 'Physics HL - Past Paper Video', 'verbose_name_plural': 'Physics HL - Past Paper Videos'},
        ),
    ]
