# Generated by Django 5.2.6 on 2025-09-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0168_alter_past_paper_videos_physics_hl_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='past_paper_videos_aa_hl',
            options={'verbose_name': 'Math AA HL - Past Paper Video', 'verbose_name_plural': 'Math AA HL - Past Paper Videos'},
        ),
    ]
