# Generated by Django 5.2.6 on 2025-09-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0169_alter_past_paper_videos_aa_hl_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biology_hl_questionbank',
            options={'verbose_name': 'Biology HL - Questionbank', 'verbose_name_plural': 'Biology HL - Questionbanks'},
        ),
        migrations.AlterModelOptions(
            name='biology_sl_questionbank',
            options={'verbose_name': 'Biology SL - Questionbank', 'verbose_name_plural': 'Biology SL - Questionbanks'},
        ),
        migrations.AlterModelOptions(
            name='comp_sci_hl_questionbank',
            options={'verbose_name': 'Comp Sci HL - Questionbank', 'verbose_name_plural': 'Comp Sci HL - Questionbanks'},
        ),
        migrations.AlterModelOptions(
            name='comp_sci_sl_questionbank',
            options={'verbose_name': 'Comp Sci SL - Questionbank', 'verbose_name_plural': 'Comp Sci SL - Questionbanks'},
        ),
        migrations.AlterModelOptions(
            name='math_aa_hl_questionbank',
            options={'verbose_name': 'Math AA HL - Questionbank', 'verbose_name_plural': 'Math AA HL - Questionbanks'},
        ),
        migrations.AlterModelOptions(
            name='math_aa_sl_questionbank',
            options={'verbose_name': 'Math AA SL - Questionbank', 'verbose_name_plural': 'Math AA SL - Questionbanks'},
        ),
        migrations.AlterModelOptions(
            name='math_ai_hl_questionbank',
            options={'verbose_name': 'Math AI HL - Questionbank', 'verbose_name_plural': 'Math AI HL - Questionbanks'},
        ),
        migrations.AlterModelOptions(
            name='math_ai_sl_questionbank',
            options={'verbose_name': 'Math AI SL - Questionbank', 'verbose_name_plural': 'Math AI SL - Questionbanks'},
        ),
        migrations.AlterModelOptions(
            name='past_paper_videos',
            options={'verbose_name': 'Math AI SL - Past Paper Video', 'verbose_name_plural': 'Math AI SL - Past Paper Videos'},
        ),
        migrations.AlterModelOptions(
            name='past_paper_videos_aa_sl',
            options={'verbose_name': 'Math AA SL - Past Paper Video', 'verbose_name_plural': 'Math AA SL - Past Paper Videos'},
        ),
        migrations.AlterModelOptions(
            name='past_paper_videos_ai_hl',
            options={'verbose_name': 'Math AI HL - Past Paper Video', 'verbose_name_plural': 'Math AI HL - Past Paper Videos'},
        ),
        migrations.AlterModelOptions(
            name='past_paper_videos_physics_sl',
            options={'verbose_name': 'Physics SL - Past Paper Video', 'verbose_name_plural': 'Physics SL - Past Paper Videos'},
        ),
        migrations.AlterModelOptions(
            name='physics_hl_questionbank',
            options={'verbose_name': 'Physics HL - Questionbank', 'verbose_name_plural': 'Physics HL - Questionbanks'},
        ),
        migrations.AlterModelOptions(
            name='physics_sl_questionbank',
            options={'verbose_name': 'Physics SL - Questionbank', 'verbose_name_plural': 'Physics SL - Questionbanks'},
        ),
        migrations.AlterModelOptions(
            name='uni_database',
            options={'verbose_name': 'Uni Database', 'verbose_name_plural': 'Uni Databases'},
        ),
        migrations.AlterModelOptions(
            name='webinars_live',
            options={'verbose_name': 'Webinar Live', 'verbose_name_plural': 'Webinars Live'},
        ),
    ]
