# Generated by Django 5.2.6 on 2025-09-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0170_alter_biology_hl_questionbank_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
