# Generated by Django 5.2.6 on 2025-09-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0171_alter_users_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='subject',
            field=models.CharField(choices=[('physics_sl', 'Physics SL'), ('physics_hl', 'Physics HL'), ('biology_sl', 'Biology SL'), ('biology_hl', 'Biology HL'), ('chemistry_sl', 'Chemistry SL'), ('chemistry_hl', 'Chemistry HL'), ('math_ai_sl', 'Math AI SL'), ('math_ai_hl', 'Math AI HL'), ('math_aa_sl', 'Math AA SL'), ('math_aa_hl', 'Math AA HL'), ('comp_sci_sl', 'Comp Sci SL'), ('comp_sci_hl', 'Comp Sci HL'), ('geography_sl', 'Geography SL'), ('geography_hl', 'Geography HL'), ('economics_sl', 'Economics SL'), ('economics_hl', 'Economics HL'), ('history_sl', 'History SL'), ('history_hl', 'History HL'), ('business_sl', 'Business SL'), ('business_hl', 'Business HL')], default='physics_sl', max_length=200),
        ),
    ]
