# Generated by Django 5.2.6 on 2025-09-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0172_tutorsession_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='student_email',
            field=models.EmailField(blank=True, help_text="Student's email for easy lookup", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20),
        ),
    ]
