# Generated by Django 5.2.6 on 2025-10-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0173_tutorsession_student_email_alter_tutorsession_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmanagement',
            unique_together={('student_first_name', 'student_last_name', 'parent_email', 'assigned_tutor')},
        ),
    ]
