# Generated by Django 5.0 on 2025-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0175_remove_student_management_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="premium_members",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="premium_members",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="premium_members",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
