# Generated by Django 5.2.6 on 2025-10-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0176_premium_members_email_premium_members_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleted_premium_users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='deleted_premium_users',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deleted_premium_users',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
