# Generated by Django 5.2.6 on 2025-10-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0177_deleted_premium_users_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleted_premium_users',
            name='stripe_customer_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
