# Generated by Django 5.0 on 2025-10-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0179_alter_past_paper_videos_aa_hl_paper_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="past_paper_videos_aa_hl",
            name="paper",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3")], default="1", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="past_paper_videos_aa_sl",
            name="paper",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3")], default="1", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="past_paper_videos_ai_hl",
            name="paper",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3")], default="1", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="past_paper_videos_physics_hl",
            name="paper",
            field=models.CharField(
                choices=[
                    ("1", "Paper 1"),
                    ("1A", "Paper 1A"),
                    ("1B", "Paper 1B"),
                    ("2", "Paper 2"),
                    ("3", "Paper 3"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="past_paper_videos_physics_sl",
            name="paper",
            field=models.CharField(
                choices=[
                    ("1", "Paper 1"),
                    ("1A", "Paper 1A"),
                    ("1B", "Paper 1B"),
                    ("2", "Paper 2"),
                    ("3", "Paper 3"),
                ],
                default="1",
                max_length=10,
            ),
        ),
    ]
