# Generated by Django 5.0 on 2025-10-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0183_alter_past_paper_videos_topic1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuestionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=200, unique=True)),
                ("math_ai_sl_completed", models.TextField(blank=True, default="[]")),
                ("math_ai_sl_marked", models.TextField(blank=True, default="[]")),
                ("math_aa_sl_completed", models.TextField(blank=True, default="[]")),
                ("math_aa_sl_marked", models.TextField(blank=True, default="[]")),
                ("math_ai_hl_completed", models.TextField(blank=True, default="[]")),
                ("math_ai_hl_marked", models.TextField(blank=True, default="[]")),
                ("math_aa_hl_completed", models.TextField(blank=True, default="[]")),
                ("math_aa_hl_marked", models.TextField(blank=True, default="[]")),
                ("physics_sl_completed", models.TextField(blank=True, default="[]")),
                ("physics_sl_marked", models.TextField(blank=True, default="[]")),
                ("physics_hl_completed", models.TextField(blank=True, default="[]")),
                ("physics_hl_marked", models.TextField(blank=True, default="[]")),
                ("biology_sl_completed", models.TextField(blank=True, default="[]")),
                ("biology_sl_marked", models.TextField(blank=True, default="[]")),
                ("biology_hl_completed", models.TextField(blank=True, default="[]")),
                ("biology_hl_marked", models.TextField(blank=True, default="[]")),
                ("comp_sci_sl_completed", models.TextField(blank=True, default="[]")),
                ("comp_sci_sl_marked", models.TextField(blank=True, default="[]")),
                ("comp_sci_hl_completed", models.TextField(blank=True, default="[]")),
                ("comp_sci_hl_marked", models.TextField(blank=True, default="[]")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Question Progress",
                "verbose_name_plural": "User Question Progress",
            },
        ),
        migrations.AlterField(
            model_name="comp_sci_hl_questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("system_fundamentals", "System Fundamentals"),
                    ("computer_organisation", "Computer Organisation"),
                    ("networks", "Networks"),
                    ("computational_thinking", "Computational Thinking"),
                    ("resource_management", "Resource Management"),
                    ("abstract_data_structures", "Abstract Data Structures"),
                    ("variables_input", "Variables and Input"),
                    ("if_statements", "If Statements"),
                    ("loops", "Loops"),
                    ("arrays", "Arrays"),
                    ("methods", "Methods"),
                    ("constructors", "Constructors"),
                    ("oop", "OOP"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="comp_sci_sl_questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("system_fundamentals", "System Fundamentals"),
                    ("computer_organisation", "Computer Organisation"),
                    ("networks", "Networks"),
                    ("computational_thinking", "Computational Thinking"),
                    ("variables_input", "Variables and Input"),
                    ("if_statements", "If Statements"),
                    ("loops", "Loops"),
                    ("arrays", "Arrays"),
                    ("methods", "Methods"),
                    ("constructors", "Constructors"),
                    ("oop", "OOP"),
                ],
                max_length=200,
            ),
        ),
    ]
