# Generated by Django 5.0 on 2025-10-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0184_userquestionprogress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comp_sci_sl_questionbank",
            name="hl_question_id",
            field=models.IntegerField(
                blank=True, help_text="ID of corresponding HL question", null=True
            ),
        ),
        migrations.AddField(
            model_name="comp_sci_sl_questionbank",
            name="sync_to_hl",
            field=models.BooleanField(
                default=True,
                help_text="Automatically sync this question to Computer Science HL",
            ),
        ),
    ]
