# Generated by Django 5.0 on 2025-10-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0185_comp_sci_sl_questionbank_hl_question_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comp_sci_sl_questionbank",
            name="sync_to_hl",
            field=models.BooleanField(
                default=False,
                help_text="Automatically sync this question to Computer Science HL",
            ),
        ),
    ]
