# Generated by Django 5.2.6 on 2025-10-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0186_alter_comp_sci_sl_questionbank_sync_to_hl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comp_sci_hl_questionbank",
            name="paper",
            field=models.CharField(
                choices=[
                    ("paper1", "Paper 1"),
                    ("paper2", "Paper 2"),
                    ("practice", "Practice"),
                ],
                default="paper1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="comp_sci_sl_questionbank",
            name="paper",
            field=models.CharField(
                choices=[
                    ("paper1", "Paper 1"),
                    ("paper2", "Paper 2"),
                    ("practice", "Practice"),
                ],
                default="paper1",
                max_length=20,
            ),
        ),
    ]
