# Generated by Django 5.2.6 on 2025-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0187_alter_comp_sci_hl_questionbank_paper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='marek.kowalczyk12@vp.pl', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
