# Generated by Django 5.2.6 on 2025-11-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0188_last_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_entries',
            name='unique_ip_addresses_no_unknown',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
