# Generated by Django 5.2.6 on 2025-11-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0189_total_entries_unique_ip_addresses_no_unknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_journey',
            name='visitor_id',
            field=models.CharField(default='null', max_length=64),
        ),
    ]
