# Generated by Django 5.2.6 on 2025-11-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0190_user_journey_visitor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_journey',
            name='visitor_id',
        ),
    ]
