# Generated by Django 5.2.6 on 2025-11-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0191_remove_user_journey_visitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_journey',
            name='visitor_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
