# Generated by Django 5.2.6 on 2025-11-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0192_user_journey_visitor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_entries',
            old_name='unique_ip_addresses_all',
            new_name='unique_cookies_all',
        ),
        migrations.RenameField(
            model_name='total_entries',
            old_name='unique_ip_addresses_all_no_db',
            new_name='unique_cookies_logged_in',
        ),
        migrations.RenameField(
            model_name='total_entries',
            old_name='unique_ip_addresses_home',
            new_name='unique_cookies_no_db',
        ),
        migrations.RenameField(
            model_name='total_entries',
            old_name='unique_ip_addresses_no_unknown',
            new_name='unique_cookies_no_unknown',
        ),
        migrations.RemoveField(
            model_name='total_entries',
            name='full_journey',
        ),
        migrations.RemoveField(
            model_name='total_entries',
            name='total_entries_home',
        ),
    ]
