# Generated by Django 5.2.6 on 2025-11-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0193_rename_unique_ip_addresses_all_total_entries_unique_cookies_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_entries',
            name='full_journey',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='total_entries',
            name='full_journey2',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
