# Generated by Django 5.2.6 on 2025-11-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0194_total_entries_full_journey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_entries',
            name='full_journey2',
        ),
    ]
