# Generated by Django 5.2.6 on 2025-11-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0195_remove_total_entries_full_journey2'),
    ]

    operations = [
        migrations.AddField(
            model_name='biology_hl_questionbank',
            name='verified',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='biology_sl_questionbank',
            name='verified',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
    ]
