# Generated by Django 5.2.6 on 2025-11-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0196_biology_hl_questionbank_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology_sl_questionbank',
            name='verified',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10),
        ),
    ]
