# Generated by Django 5.0 on 2025-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0197_alter_biology_sl_questionbank_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmanagement",
            name="rules_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Whether student/parent has accepted the tutoring rules",
            ),
        ),
        migrations.AddField(
            model_name="studentmanagement",
            name="rules_accepted_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when rules were accepted", null=True
            ),
        ),
    ]
