# Generated by Django 5.0 on 2025-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0198_studentmanagement_rules_accepted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentmanagement",
            name="rules_accepted",
        ),
        migrations.RemoveField(
            model_name="studentmanagement",
            name="rules_accepted_date",
        ),
        migrations.AddField(
            model_name="studentmanagement",
            name="parent_rules_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Whether parent has accepted the tutoring rules",
            ),
        ),
        migrations.AddField(
            model_name="studentmanagement",
            name="parent_rules_accepted_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when parent accepted rules", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentmanagement",
            name="student_rules_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Whether student has accepted the tutoring rules",
            ),
        ),
        migrations.AddField(
            model_name="studentmanagement",
            name="student_rules_accepted_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when student accepted rules", null=True
            ),
        ),
    ]
