# Generated by Django 5.0 on 2025-11-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0199_remove_studentmanagement_rules_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="verification_code_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="verified",
            field=models.BooleanField(default=True),
        ),
    ]
