# Generated by Django 5.0 on 2025-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0200_users_verification_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        help_text="Enter an emoji (e.g., 🎉, 📢, 🚀)", max_length=10
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short title for the announcement", max_length=100
                    ),
                ),
                ("content", models.TextField(help_text="Full announcement content")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this announcement on home page"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
            ],
            options={
                "verbose_name": "News Announcement",
                "verbose_name_plural": "News Announcements",
                "ordering": ["order", "-created_date"],
            },
        ),
    ]
