# Generated by Django 5.0 on 2025-11-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0201_newsannouncement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsannouncement",
            name="content",
        ),
        migrations.RemoveField(
            model_name="newsannouncement",
            name="title",
        ),
        migrations.AddField(
            model_name="newsannouncement",
            name="color",
            field=models.CharField(
                choices=[
                    ("purple", "🟣 Purple"),
                    ("pink", "\U0001fa77 Pink"),
                    ("blue", "🔵 Blue"),
                    ("green", "🟢 Green"),
                    ("orange", "🟠 Orange"),
                    ("red", "🔴 Red"),
                    ("teal", "\U0001fa75 Teal"),
                    ("yellow", "🟡 Yellow"),
                ],
                default="purple",
                help_text="Border color of the circle",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="newsannouncement",
            name="label",
            field=models.CharField(
                default="News",
                help_text="Text shown below the circle (e.g., 'New Feature')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="newsannouncement",
            name="popup_content",
            field=models.TextField(
                default="", help_text="Full announcement content shown in popup"
            ),
        ),
        migrations.AddField(
            model_name="newsannouncement",
            name="popup_title",
            field=models.CharField(
                default="Announcement",
                help_text="Title shown in the popup",
                max_length=100,
            ),
        ),
    ]
