# Generated by Django 5.0 on 2025-11-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0202_remove_newsannouncement_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsannouncement",
            name="popup_content",
            field=models.TextField(
                default="",
                help_text="Full announcement content - you can use HTML for buttons, links, formatting, etc.",
            ),
        ),
    ]
