# Generated by Django 5.0 on 2025-11-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0203_alter_newsannouncement_popup_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="past_paper_videos_physics_sl",
            name="topic1",
            field=models.CharField(
                choices=[
                    ("null", "null"),
                    ("kinematics", "Kinematics"),
                    ("forces_and_momentum", "Forces and Momentum"),
                    ("work_energy_power", "Work, Energy, and Power"),
                    ("thermal_energy", "Thermal Energy"),
                    ("greenhouse_effect", "Greenhouse Effect"),
                    ("ideal_gas_model", "Ideal Gas Model"),
                    ("electric_circuits", "Electric Circuits"),
                    ("simple_harmonic_motion", "Simple Harmonic Motion"),
                    ("wave_model", "Wave Model"),
                    ("wave_phenomena", "Wave Phenomena"),
                    ("standing_waves", "Standing Wave and Resonance"),
                    ("doppler_effect", "Doppler Effect"),
                    ("gravitational_fields", "Gravitational Fields"),
                    ("electric_magnetic_fields", "Electric and Magnetic Fields"),
                    ("motion_in_fields", "Motion in Electromagnetic Fields"),
                    ("structure_atom", "Structure of the Atom"),
                    ("radioactive_decay", "Radioactive Decay"),
                    ("fission", "Fission"),
                    ("fusion_and_stars", "Fusion and Stars"),
                ],
                default="null",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="past_paper_videos_physics_sl",
            name="topic2",
            field=models.CharField(
                choices=[
                    ("null", "null"),
                    ("kinematics", "Kinematics"),
                    ("forces_and_momentum", "Forces and Momentum"),
                    ("work_energy_power", "Work, Energy, and Power"),
                    ("thermal_energy", "Thermal Energy"),
                    ("greenhouse_effect", "Greenhouse Effect"),
                    ("ideal_gas_model", "Ideal Gas Model"),
                    ("electric_circuits", "Electric Circuits"),
                    ("simple_harmonic_motion", "Simple Harmonic Motion"),
                    ("wave_model", "Wave Model"),
                    ("wave_phenomena", "Wave Phenomena"),
                    ("standing_waves", "Standing Wave and Resonance"),
                    ("doppler_effect", "Doppler Effect"),
                    ("gravitational_fields", "Gravitational Fields"),
                    ("electric_magnetic_fields", "Electric and Magnetic Fields"),
                    ("motion_in_fields", "Motion in Electromagnetic Fields"),
                    ("structure_atom", "Structure of the Atom"),
                    ("radioactive_decay", "Radioactive Decay"),
                    ("fission", "Fission"),
                    ("fusion_and_stars", "Fusion and Stars"),
                ],
                default="null",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="past_paper_videos_physics_sl",
            name="topic3",
            field=models.CharField(
                choices=[
                    ("null", "null"),
                    ("kinematics", "Kinematics"),
                    ("forces_and_momentum", "Forces and Momentum"),
                    ("work_energy_power", "Work, Energy, and Power"),
                    ("thermal_energy", "Thermal Energy"),
                    ("greenhouse_effect", "Greenhouse Effect"),
                    ("ideal_gas_model", "Ideal Gas Model"),
                    ("electric_circuits", "Electric Circuits"),
                    ("simple_harmonic_motion", "Simple Harmonic Motion"),
                    ("wave_model", "Wave Model"),
                    ("wave_phenomena", "Wave Phenomena"),
                    ("standing_waves", "Standing Wave and Resonance"),
                    ("doppler_effect", "Doppler Effect"),
                    ("gravitational_fields", "Gravitational Fields"),
                    ("electric_magnetic_fields", "Electric and Magnetic Fields"),
                    ("motion_in_fields", "Motion in Electromagnetic Fields"),
                    ("structure_atom", "Structure of the Atom"),
                    ("radioactive_decay", "Radioactive Decay"),
                    ("fission", "Fission"),
                    ("fusion_and_stars", "Fusion and Stars"),
                ],
                default="null",
                max_length=100,
            ),
        ),
    ]
