# Generated by Django 5.0 on 2025-11-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0205_alter_past_paper_videos_physics_hl_topic1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="referral_code",
            field=models.CharField(
                blank=True,
                help_text="Unique referral code for this user",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="referral_code_used",
            field=models.CharField(
                blank=True,
                help_text="Referral code this user activated",
                max_length=12,
                null=True,
            ),
        ),
    ]
