# Generated by Django 5.2.6 on 2025-12-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0206_users_referral_code_users_referral_code_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology_sl_questionbank',
            name='verified',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
    ]
