# Generated by Django 5.0 on 2026-01-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0208_past_paper_videos_comp_sci_sl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="past_paper_videos",
            name="question_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for question screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
    ]
