# Generated by Django 5.0 on 2026-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0209_past_paper_videos_question_screenshots_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Past_Paper_Videos_Chemistry_SL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("May", "May"),
                            ("November", "November"),
                            ("Specimen", "Specimen"),
                        ],
                        default="May",
                        max_length=10,
                    ),
                ),
                ("year", models.CharField(default="2024", max_length=10)),
                ("session", models.CharField(default="null", max_length=100)),
                (
                    "time_zone",
                    models.CharField(
                        choices=[("0", "0"), ("1", "1"), ("2", "2"), ("3", "3")],
                        default="1",
                        max_length=10,
                    ),
                ),
                (
                    "paper",
                    models.CharField(
                        choices=[
                            ("1", "Paper 1"),
                            ("1A", "Paper 1A"),
                            ("1B", "Paper 1B"),
                            ("2", "Paper 2"),
                            ("3", "Paper 3"),
                        ],
                        default="1",
                        max_length=10,
                    ),
                ),
                ("question", models.CharField(default="1", max_length=100)),
                (
                    "abbreviation_month",
                    models.CharField(default="null", max_length=100),
                ),
                ("abbreviation_year", models.CharField(default="null", max_length=100)),
                (
                    "topic1",
                    models.CharField(
                        choices=[
                            ("null", "null"),
                            ("kinematics", "Kinematics"),
                            ("forces_and_momentum", "Forces and Momentum"),
                            ("work_energy_power", "Work, Energy, and Power"),
                            ("thermal_energy", "Thermal Energy"),
                            ("greenhouse_effect", "Greenhouse Effect"),
                            ("ideal_gas_model", "Ideal Gas Model"),
                            ("electric_circuits", "Electric Circuits"),
                            ("simple_harmonic_motion", "Simple Harmonic Motion"),
                            ("wave_model", "Wave Model"),
                            ("wave_phenomena", "Wave Phenomena"),
                            ("standing_waves", "Standing Wave and Resonance"),
                            ("doppler_effect", "Doppler Effect"),
                            ("gravitational_fields", "Gravitational Fields"),
                            (
                                "electric_magnetic_fields",
                                "Electric and Magnetic Fields",
                            ),
                            ("motion_in_fields", "Motion in Electromagnetic Fields"),
                            ("structure_atom", "Structure of the Atom"),
                            ("radioactive_decay", "Radioactive Decay"),
                            ("fission", "Fission"),
                            ("fusion_and_stars", "Fusion and Stars"),
                        ],
                        default="null",
                        max_length=100,
                    ),
                ),
                (
                    "topic2",
                    models.CharField(
                        choices=[
                            ("null", "null"),
                            ("kinematics", "Kinematics"),
                            ("forces_and_momentum", "Forces and Momentum"),
                            ("work_energy_power", "Work, Energy, and Power"),
                            ("thermal_energy", "Thermal Energy"),
                            ("greenhouse_effect", "Greenhouse Effect"),
                            ("ideal_gas_model", "Ideal Gas Model"),
                            ("electric_circuits", "Electric Circuits"),
                            ("simple_harmonic_motion", "Simple Harmonic Motion"),
                            ("wave_model", "Wave Model"),
                            ("wave_phenomena", "Wave Phenomena"),
                            ("standing_waves", "Standing Wave and Resonance"),
                            ("doppler_effect", "Doppler Effect"),
                            ("gravitational_fields", "Gravitational Fields"),
                            (
                                "electric_magnetic_fields",
                                "Electric and Magnetic Fields",
                            ),
                            ("motion_in_fields", "Motion in Electromagnetic Fields"),
                            ("structure_atom", "Structure of the Atom"),
                            ("radioactive_decay", "Radioactive Decay"),
                            ("fission", "Fission"),
                            ("fusion_and_stars", "Fusion and Stars"),
                        ],
                        default="null",
                        max_length=100,
                    ),
                ),
                (
                    "topic3",
                    models.CharField(
                        choices=[
                            ("null", "null"),
                            ("kinematics", "Kinematics"),
                            ("forces_and_momentum", "Forces and Momentum"),
                            ("work_energy_power", "Work, Energy, and Power"),
                            ("thermal_energy", "Thermal Energy"),
                            ("greenhouse_effect", "Greenhouse Effect"),
                            ("ideal_gas_model", "Ideal Gas Model"),
                            ("electric_circuits", "Electric Circuits"),
                            ("simple_harmonic_motion", "Simple Harmonic Motion"),
                            ("wave_model", "Wave Model"),
                            ("wave_phenomena", "Wave Phenomena"),
                            ("standing_waves", "Standing Wave and Resonance"),
                            ("doppler_effect", "Doppler Effect"),
                            ("gravitational_fields", "Gravitational Fields"),
                            (
                                "electric_magnetic_fields",
                                "Electric and Magnetic Fields",
                            ),
                            ("motion_in_fields", "Motion in Electromagnetic Fields"),
                            ("structure_atom", "Structure of the Atom"),
                            ("radioactive_decay", "Radioactive Decay"),
                            ("fission", "Fission"),
                            ("fusion_and_stars", "Fusion and Stars"),
                        ],
                        default="null",
                        max_length=100,
                    ),
                ),
                ("link", models.CharField(default="null", max_length=200)),
            ],
            options={
                "verbose_name": "Chemistry SL - Past Paper Video",
                "verbose_name_plural": "Chemistry SL - Past Paper Videos",
            },
        ),
        migrations.AddField(
            model_name="past_paper_videos_aa_hl",
            name="question_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for question screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_aa_sl",
            name="question_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for question screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_ai_hl",
            name="question_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for question screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_physics_hl",
            name="question_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for question screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_physics_sl",
            name="question_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for question screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
    ]
