# Generated by Django 5.0 on 2026-01-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0212_alter_past_paper_videos_chemistry_hl_topic1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chemistry_HL_Questionbank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Easy",
                        max_length=10,
                    ),
                ),
                (
                    "paper",
                    models.CharField(
                        choices=[
                            ("paper1", "Paper 1"),
                            ("paper2", "Paper 2"),
                            ("paper3", "Paper 3"),
                        ],
                        default="paper1",
                        max_length=20,
                    ),
                ),
                ("video", models.TextField(default="none")),
                (
                    "chapter",
                    models.CharField(
                        choices=[
                            ("", "None"),
                            (
                                "introduction_particulate_nature",
                                "S1.1 Introduction to the particulate nature of matter",
                            ),
                            ("nuclear_atom", "S1.2 The nuclear atom"),
                            ("electron_configurations", "S1.3 Electron configurations"),
                            (
                                "counting_particles_mole",
                                "S1.4 Counting particles by mass: The mole",
                            ),
                            ("ideal_gases", "S1.5 Ideal gases"),
                            ("ionic_model", "S2.1 The ionic model"),
                            ("covalent_model", "S2.2 The covalent model"),
                            ("metallic_model", "S2.3 The metallic model"),
                            ("models_to_materials", "S2.4 From models to materials"),
                            (
                                "periodic_table",
                                "S3.1 The periodic table: Classification of elements",
                            ),
                            (
                                "functional_groups",
                                "S3.2 Functional groups: Classification of organic compounds",
                            ),
                            ("measuring_enthalpy", "R1.1 Measuring enthalpy changes"),
                            ("energy_cycles", "R1.2 Energy cycles in reactions"),
                            ("energy_from_fuels", "R1.3 Energy from fuels"),
                            ("entropy_spontaneity", "R1.4 Entropy and spontaneity"),
                            (
                                "amount_chemical_change",
                                "R2.1 How much? The amount of chemical change",
                            ),
                            (
                                "rate_chemical_change",
                                "R2.2 How fast? The rate of chemical change",
                            ),
                            (
                                "extent_chemical_change",
                                "R2.3 How far? The extent of chemical change",
                            ),
                            ("proton_transfer", "R3.1 Proton transfer reactions"),
                            ("electron_transfer", "R3.2 Electron transfer reactions"),
                            ("electron_sharing", "R3.3 Electron sharing reactions"),
                            (
                                "electron_pair_sharing",
                                "R3.4 Electron-pair sharing reactions",
                            ),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "chapter2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            (
                                "introduction_particulate_nature",
                                "S1.1 Introduction to the particulate nature of matter",
                            ),
                            ("nuclear_atom", "S1.2 The nuclear atom"),
                            ("electron_configurations", "S1.3 Electron configurations"),
                            (
                                "counting_particles_mole",
                                "S1.4 Counting particles by mass: The mole",
                            ),
                            ("ideal_gases", "S1.5 Ideal gases"),
                            ("ionic_model", "S2.1 The ionic model"),
                            ("covalent_model", "S2.2 The covalent model"),
                            ("metallic_model", "S2.3 The metallic model"),
                            ("models_to_materials", "S2.4 From models to materials"),
                            (
                                "periodic_table",
                                "S3.1 The periodic table: Classification of elements",
                            ),
                            (
                                "functional_groups",
                                "S3.2 Functional groups: Classification of organic compounds",
                            ),
                            ("measuring_enthalpy", "R1.1 Measuring enthalpy changes"),
                            ("energy_cycles", "R1.2 Energy cycles in reactions"),
                            ("energy_from_fuels", "R1.3 Energy from fuels"),
                            ("entropy_spontaneity", "R1.4 Entropy and spontaneity"),
                            (
                                "amount_chemical_change",
                                "R2.1 How much? The amount of chemical change",
                            ),
                            (
                                "rate_chemical_change",
                                "R2.2 How fast? The rate of chemical change",
                            ),
                            (
                                "extent_chemical_change",
                                "R2.3 How far? The extent of chemical change",
                            ),
                            ("proton_transfer", "R3.1 Proton transfer reactions"),
                            ("electron_transfer", "R3.2 Electron transfer reactions"),
                            ("electron_sharing", "R3.3 Electron sharing reactions"),
                            (
                                "electron_pair_sharing",
                                "R3.4 Electron-pair sharing reactions",
                            ),
                        ],
                        default="",
                        help_text="Secondary chapter (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "chapter3",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            (
                                "introduction_particulate_nature",
                                "S1.1 Introduction to the particulate nature of matter",
                            ),
                            ("nuclear_atom", "S1.2 The nuclear atom"),
                            ("electron_configurations", "S1.3 Electron configurations"),
                            (
                                "counting_particles_mole",
                                "S1.4 Counting particles by mass: The mole",
                            ),
                            ("ideal_gases", "S1.5 Ideal gases"),
                            ("ionic_model", "S2.1 The ionic model"),
                            ("covalent_model", "S2.2 The covalent model"),
                            ("metallic_model", "S2.3 The metallic model"),
                            ("models_to_materials", "S2.4 From models to materials"),
                            (
                                "periodic_table",
                                "S3.1 The periodic table: Classification of elements",
                            ),
                            (
                                "functional_groups",
                                "S3.2 Functional groups: Classification of organic compounds",
                            ),
                            ("measuring_enthalpy", "R1.1 Measuring enthalpy changes"),
                            ("energy_cycles", "R1.2 Energy cycles in reactions"),
                            ("energy_from_fuels", "R1.3 Energy from fuels"),
                            ("entropy_spontaneity", "R1.4 Entropy and spontaneity"),
                            (
                                "amount_chemical_change",
                                "R2.1 How much? The amount of chemical change",
                            ),
                            (
                                "rate_chemical_change",
                                "R2.2 How fast? The rate of chemical change",
                            ),
                            (
                                "extent_chemical_change",
                                "R2.3 How far? The extent of chemical change",
                            ),
                            ("proton_transfer", "R3.1 Proton transfer reactions"),
                            ("electron_transfer", "R3.2 Electron transfer reactions"),
                            ("electron_sharing", "R3.3 Electron sharing reactions"),
                            (
                                "electron_pair_sharing",
                                "R3.4 Electron-pair sharing reactions",
                            ),
                        ],
                        default="",
                        help_text="Third chapter (optional)",
                        max_length=200,
                    ),
                ),
                ("marks", models.TextField(default="1")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("free", "free"),
                            ("registered", "registered"),
                            ("premium", "premium"),
                        ],
                        default="registered",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chemistry HL - Questionbank",
                "verbose_name_plural": "Chemistry HL - Questionbanks",
            },
        ),
        migrations.CreateModel(
            name="Chemistry_SL_Questionbank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Easy",
                        max_length=10,
                    ),
                ),
                (
                    "paper",
                    models.CharField(
                        choices=[("paper1", "Paper 1"), ("paper2", "Paper 2")],
                        default="paper1",
                        max_length=20,
                    ),
                ),
                ("video", models.TextField(default="none")),
                (
                    "sync_to_hl",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically sync this question to Chemistry HL",
                    ),
                ),
                (
                    "hl_question_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of corresponding HL question",
                        null=True,
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        choices=[
                            ("", "None"),
                            (
                                "introduction_particulate_nature",
                                "S1.1 Introduction to the particulate nature of matter",
                            ),
                            ("nuclear_atom", "S1.2 The nuclear atom"),
                            ("electron_configurations", "S1.3 Electron configurations"),
                            (
                                "counting_particles_mole",
                                "S1.4 Counting particles by mass: The mole",
                            ),
                            ("ideal_gases", "S1.5 Ideal gases"),
                            ("ionic_model", "S2.1 The ionic model"),
                            ("covalent_model", "S2.2 The covalent model"),
                            ("metallic_model", "S2.3 The metallic model"),
                            ("models_to_materials", "S2.4 From models to materials"),
                            (
                                "periodic_table",
                                "S3.1 The periodic table: Classification of elements",
                            ),
                            (
                                "functional_groups",
                                "S3.2 Functional groups: Classification of organic compounds",
                            ),
                            ("measuring_enthalpy", "R1.1 Measuring enthalpy changes"),
                            ("energy_cycles", "R1.2 Energy cycles in reactions"),
                            ("energy_from_fuels", "R1.3 Energy from fuels"),
                            (
                                "amount_chemical_change",
                                "R2.1 How much? The amount of chemical change",
                            ),
                            (
                                "rate_chemical_change",
                                "R2.2 How fast? The rate of chemical change",
                            ),
                            (
                                "extent_chemical_change",
                                "R2.3 How far? The extent of chemical change",
                            ),
                            ("proton_transfer", "R3.1 Proton transfer reactions"),
                            ("electron_transfer", "R3.2 Electron transfer reactions"),
                            ("electron_sharing", "R3.3 Electron sharing reactions"),
                            (
                                "electron_pair_sharing",
                                "R3.4 Electron-pair sharing reactions",
                            ),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "chapter2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            (
                                "introduction_particulate_nature",
                                "S1.1 Introduction to the particulate nature of matter",
                            ),
                            ("nuclear_atom", "S1.2 The nuclear atom"),
                            ("electron_configurations", "S1.3 Electron configurations"),
                            (
                                "counting_particles_mole",
                                "S1.4 Counting particles by mass: The mole",
                            ),
                            ("ideal_gases", "S1.5 Ideal gases"),
                            ("ionic_model", "S2.1 The ionic model"),
                            ("covalent_model", "S2.2 The covalent model"),
                            ("metallic_model", "S2.3 The metallic model"),
                            ("models_to_materials", "S2.4 From models to materials"),
                            (
                                "periodic_table",
                                "S3.1 The periodic table: Classification of elements",
                            ),
                            (
                                "functional_groups",
                                "S3.2 Functional groups: Classification of organic compounds",
                            ),
                            ("measuring_enthalpy", "R1.1 Measuring enthalpy changes"),
                            ("energy_cycles", "R1.2 Energy cycles in reactions"),
                            ("energy_from_fuels", "R1.3 Energy from fuels"),
                            (
                                "amount_chemical_change",
                                "R2.1 How much? The amount of chemical change",
                            ),
                            (
                                "rate_chemical_change",
                                "R2.2 How fast? The rate of chemical change",
                            ),
                            (
                                "extent_chemical_change",
                                "R2.3 How far? The extent of chemical change",
                            ),
                            ("proton_transfer", "R3.1 Proton transfer reactions"),
                            ("electron_transfer", "R3.2 Electron transfer reactions"),
                            ("electron_sharing", "R3.3 Electron sharing reactions"),
                            (
                                "electron_pair_sharing",
                                "R3.4 Electron-pair sharing reactions",
                            ),
                        ],
                        default="",
                        help_text="Secondary chapter (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "chapter3",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            (
                                "introduction_particulate_nature",
                                "S1.1 Introduction to the particulate nature of matter",
                            ),
                            ("nuclear_atom", "S1.2 The nuclear atom"),
                            ("electron_configurations", "S1.3 Electron configurations"),
                            (
                                "counting_particles_mole",
                                "S1.4 Counting particles by mass: The mole",
                            ),
                            ("ideal_gases", "S1.5 Ideal gases"),
                            ("ionic_model", "S2.1 The ionic model"),
                            ("covalent_model", "S2.2 The covalent model"),
                            ("metallic_model", "S2.3 The metallic model"),
                            ("models_to_materials", "S2.4 From models to materials"),
                            (
                                "periodic_table",
                                "S3.1 The periodic table: Classification of elements",
                            ),
                            (
                                "functional_groups",
                                "S3.2 Functional groups: Classification of organic compounds",
                            ),
                            ("measuring_enthalpy", "R1.1 Measuring enthalpy changes"),
                            ("energy_cycles", "R1.2 Energy cycles in reactions"),
                            ("energy_from_fuels", "R1.3 Energy from fuels"),
                            (
                                "amount_chemical_change",
                                "R2.1 How much? The amount of chemical change",
                            ),
                            (
                                "rate_chemical_change",
                                "R2.2 How fast? The rate of chemical change",
                            ),
                            (
                                "extent_chemical_change",
                                "R2.3 How far? The extent of chemical change",
                            ),
                            ("proton_transfer", "R3.1 Proton transfer reactions"),
                            ("electron_transfer", "R3.2 Electron transfer reactions"),
                            ("electron_sharing", "R3.3 Electron sharing reactions"),
                            (
                                "electron_pair_sharing",
                                "R3.4 Electron-pair sharing reactions",
                            ),
                        ],
                        default="",
                        help_text="Third chapter (optional)",
                        max_length=200,
                    ),
                ),
                ("marks", models.TextField(default="1")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("free", "free"),
                            ("registered", "registered"),
                            ("premium", "premium"),
                        ],
                        default="registered",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chemistry SL - Questionbank",
                "verbose_name_plural": "Chemistry SL - Questionbanks",
            },
        ),
    ]
