# Generated by Django 5.0 on 2026-01-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0213_chemistry_hl_questionbank_chemistry_sl_questionbank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chemistry_hl_questionbank",
            name="chapter2",
        ),
        migrations.RemoveField(
            model_name="chemistry_hl_questionbank",
            name="chapter3",
        ),
        migrations.RemoveField(
            model_name="chemistry_sl_questionbank",
            name="chapter2",
        ),
        migrations.RemoveField(
            model_name="chemistry_sl_questionbank",
            name="chapter3",
        ),
        migrations.AddField(
            model_name="chemistry_hl_questionbank",
            name="correct_answer",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="A",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chemistry_sl_questionbank",
            name="correct_answer",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="A",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chemistry_hl_questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    (
                        "introduction_particulate_nature",
                        "S1.1 Introduction to the particulate nature of matter",
                    ),
                    ("nuclear_atom", "S1.2 The nuclear atom"),
                    ("electron_configurations", "S1.3 Electron configurations"),
                    (
                        "counting_particles_mole",
                        "S1.4 Counting particles by mass: The mole",
                    ),
                    ("ideal_gases", "S1.5 Ideal gases"),
                    ("ionic_model", "S2.1 The ionic model"),
                    ("covalent_model", "S2.2 The covalent model"),
                    ("metallic_model", "S2.3 The metallic model"),
                    ("models_to_materials", "S2.4 From models to materials"),
                    (
                        "periodic_table",
                        "S3.1 The periodic table: Classification of elements",
                    ),
                    (
                        "functional_groups",
                        "S3.2 Functional groups: Classification of organic compounds",
                    ),
                    ("measuring_enthalpy", "R1.1 Measuring enthalpy changes"),
                    ("energy_cycles", "R1.2 Energy cycles in reactions"),
                    ("energy_from_fuels", "R1.3 Energy from fuels"),
                    ("entropy_spontaneity", "R1.4 Entropy and spontaneity"),
                    (
                        "amount_chemical_change",
                        "R2.1 How much? The amount of chemical change",
                    ),
                    (
                        "rate_chemical_change",
                        "R2.2 How fast? The rate of chemical change",
                    ),
                    (
                        "extent_chemical_change",
                        "R2.3 How far? The extent of chemical change",
                    ),
                    ("proton_transfer", "R3.1 Proton transfer reactions"),
                    ("electron_transfer", "R3.2 Electron transfer reactions"),
                    ("electron_sharing", "R3.3 Electron sharing reactions"),
                    ("electron_pair_sharing", "R3.4 Electron-pair sharing reactions"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="chemistry_sl_questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    (
                        "introduction_particulate_nature",
                        "S1.1 Introduction to the particulate nature of matter",
                    ),
                    ("nuclear_atom", "S1.2 The nuclear atom"),
                    ("electron_configurations", "S1.3 Electron configurations"),
                    (
                        "counting_particles_mole",
                        "S1.4 Counting particles by mass: The mole",
                    ),
                    ("ideal_gases", "S1.5 Ideal gases"),
                    ("ionic_model", "S2.1 The ionic model"),
                    ("covalent_model", "S2.2 The covalent model"),
                    ("metallic_model", "S2.3 The metallic model"),
                    ("models_to_materials", "S2.4 From models to materials"),
                    (
                        "periodic_table",
                        "S3.1 The periodic table: Classification of elements",
                    ),
                    (
                        "functional_groups",
                        "S3.2 Functional groups: Classification of organic compounds",
                    ),
                    ("measuring_enthalpy", "R1.1 Measuring enthalpy changes"),
                    ("energy_cycles", "R1.2 Energy cycles in reactions"),
                    ("energy_from_fuels", "R1.3 Energy from fuels"),
                    (
                        "amount_chemical_change",
                        "R2.1 How much? The amount of chemical change",
                    ),
                    (
                        "rate_chemical_change",
                        "R2.2 How fast? The rate of chemical change",
                    ),
                    (
                        "extent_chemical_change",
                        "R2.3 How far? The extent of chemical change",
                    ),
                    ("proton_transfer", "R3.1 Proton transfer reactions"),
                    ("electron_transfer", "R3.2 Electron transfer reactions"),
                    ("electron_sharing", "R3.3 Electron sharing reactions"),
                    ("electron_pair_sharing", "R3.4 Electron-pair sharing reactions"),
                ],
                max_length=200,
            ),
        ),
    ]
