# Generated by Django 5.2.6 on 2026-01-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0214_remove_chemistry_hl_questionbank_chapter2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry_hl_questionbank',
            name='paper',
            field=models.CharField(choices=[('paper1A', 'Paper 1A'), ('paper1B', 'Paper 1B'), ('paper2', 'Paper 2')], default='paper1', max_length=20),
        ),
        migrations.AlterField(
            model_name='chemistry_sl_questionbank',
            name='paper',
            field=models.CharField(choices=[('paper1A', 'Paper 1A'), ('paper1B', 'Paper 1B'), ('paper2', 'Paper 2')], default='paper1', max_length=20),
        ),
    ]
