# Generated by Django 5.0 on 2026-01-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0215_alter_chemistry_hl_questionbank_paper_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionprogress",
            name="chemistry_hl_completed",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AddField(
            model_name="userquestionprogress",
            name="chemistry_hl_marked",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AddField(
            model_name="userquestionprogress",
            name="chemistry_sl_completed",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AddField(
            model_name="userquestionprogress",
            name="chemistry_sl_marked",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
