# Generated by Django 5.0 on 2026-01-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0216_userquestionprogress_chemistry_hl_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="math_ai_sl_questionbank",
            name="question_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for question screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
    ]
