# Generated by Django 5.0 on 2026-02-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0217_math_ai_sl_questionbank_question_screenshots_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorsession",
            name="managed_student",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to managed student record if applicable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="website.studentmanagement",
            ),
        ),
    ]
