# Generated by Django 5.2.6 on 2026-02-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0218_tutorsession_managed_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Past_Paper_Videos_Comp_Sci_HL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('May', 'May'), ('November', 'November')], default='May', max_length=10)),
                ('year', models.CharField(default='2024', max_length=10)),
                ('session', models.CharField(default='null', max_length=100)),
                ('time_zone', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='1', max_length=10)),
                ('paper', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=10)),
                ('question', models.CharField(default='1', max_length=100)),
                ('abbreviation_month', models.CharField(default='null', max_length=100)),
                ('abbreviation_year', models.CharField(default='null', max_length=100)),
                ('topic1', models.CharField(choices=[('null', 'null'), ('system_fundamentals', 'System Fundamentals'), ('computer_organisation', 'Computer Organisation'), ('networks', 'Networks'), ('computational_thinking', 'Computational Thinking'), ('resource_management', 'Resource Management'), ('abstract_data_structures', 'Abstract Data Structures'), ('variables_input', 'Variables and Input'), ('if_statements', 'If Statements'), ('loops', 'Loops'), ('arrays', 'Arrays'), ('methods', 'Methods'), ('constructors', 'Constructors'), ('oop', 'OOP')], default='null', max_length=100)),
                ('topic2', models.CharField(choices=[('null', 'null'), ('system_fundamentals', 'System Fundamentals'), ('computer_organisation', 'Computer Organisation'), ('networks', 'Networks'), ('computational_thinking', 'Computational Thinking'), ('resource_management', 'Resource Management'), ('abstract_data_structures', 'Abstract Data Structures'), ('variables_input', 'Variables and Input'), ('if_statements', 'If Statements'), ('loops', 'Loops'), ('arrays', 'Arrays'), ('methods', 'Methods'), ('constructors', 'Constructors'), ('oop', 'OOP')], default='null', max_length=100)),
                ('topic3', models.CharField(choices=[('null', 'null'), ('system_fundamentals', 'System Fundamentals'), ('computer_organisation', 'Computer Organisation'), ('networks', 'Networks'), ('computational_thinking', 'Computational Thinking'), ('resource_management', 'Resource Management'), ('abstract_data_structures', 'Abstract Data Structures'), ('variables_input', 'Variables and Input'), ('if_statements', 'If Statements'), ('loops', 'Loops'), ('arrays', 'Arrays'), ('methods', 'Methods'), ('constructors', 'Constructors'), ('oop', 'OOP')], default='null', max_length=100)),
                ('link', models.CharField(default='null', max_length=200)),
                ('text_answer', models.TextField(default='null')),
            ],
            options={
                'verbose_name': 'Comp Sci HL - Past Paper Video',
                'verbose_name_plural': 'Comp Sci HL - Past Paper Videos',
            },
        ),
    ]
