# Generated by Django 5.2.6 on 2026-02-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0220_past_paper_videos_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_paper_videos_ai_hl',
            name='access_level',
            field=models.CharField(choices=[('free', 'Free'), ('registered', 'Registered'), ('premium', 'Premium')], default='premium', help_text='Access level for this video', max_length=20),
        ),
    ]
