# Generated by Django 5.2.6 on 2026-02-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0222_past_paper_videos_aa_hl_access_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_paper_videos_physics_sl',
            name='access_level',
            field=models.CharField(choices=[('free', 'Free'), ('registered', 'Registered'), ('premium', 'Premium')], default='premium', help_text='Access level for this video', max_length=20),
        ),
    ]
