# Generated by Django 5.2.6 on 2026-02-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0224_past_paper_videos_physics_hl_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium_members',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('free', 'Free'), ('free_trial', 'Free Trial'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=20, null=True),
        ),
    ]
