# Generated by Django 5.2.6 on 2026-03-01 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0225_premium_members_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedExamsPastPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ai_sl', 'Math AI SL'), ('ai_hl', 'Math AI HL'), ('aa_sl', 'Math AA SL'), ('aa_hl', 'Math AA HL'), ('physics_sl', 'Physics SL'), ('physics_hl', 'Physics HL')], max_length=20)),
                ('chapters', models.JSONField(help_text='List of chapter codes selected')),
                ('paper', models.CharField(help_text='Paper number: 1, 2, all, 1A, 1B', max_length=10)),
                ('question_limit', models.IntegerField(default=50)),
                ('question_ids', models.JSONField(help_text='List of video IDs that were included in the PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_past_paper_exams', to='website.users')),
            ],
            options={
                'verbose_name': 'Generated Exam (Past Papers)',
                'verbose_name_plural': 'Generated Exams (Past Papers)',
                'ordering': ['-created_at'],
            },
        ),
    ]
