# Generated by Django 5.2.6 on 2026-03-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0226_generatedexamspastpapers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_paper_videos',
            name='topic1',
            field=models.CharField(choices=[('null', 'null'), ('number_skills', 'Number Skills'), ('seq_series', 'Sequences & Series'), ('systems_of_equations', 'Systems of Linear Equations'), ('linear_equations_graphs', 'Linear Equations & Graphs'), ('application_of_functions', 'Application of Functions'), ('properties_of_functions', 'Properties of Functions'), ('trigonometry', 'Trigonometry'), ('voronoi_diagrams', 'Voronoi Diagrams'), ('descriptive_statistics', 'Descriptive Statistics'), ('bivariate_statistics', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('geometry_shapes', 'Geometry of 3D Shapes'), ('hypothesis_testing', 'Hypothesis Testing'), ('differentiation', 'Differentiation'), ('integration', 'Integration')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos',
            name='topic2',
            field=models.CharField(choices=[('null', 'null'), ('number_skills', 'Number Skills'), ('seq_series', 'Sequences & Series'), ('systems_of_equations', 'Systems of Linear Equations'), ('linear_equations_graphs', 'Linear Equations & Graphs'), ('application_of_functions', 'Application of Functions'), ('properties_of_functions', 'Properties of Functions'), ('trigonometry', 'Trigonometry'), ('voronoi_diagrams', 'Voronoi Diagrams'), ('descriptive_statistics', 'Descriptive Statistics'), ('bivariate_statistics', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('geometry_shapes', 'Geometry of 3D Shapes'), ('hypothesis_testing', 'Hypothesis Testing'), ('differentiation', 'Differentiation'), ('integration', 'Integration')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='past_paper_videos',
            name='topic3',
            field=models.CharField(choices=[('null', 'null'), ('number_skills', 'Number Skills'), ('seq_series', 'Sequences & Series'), ('systems_of_equations', 'Systems of Linear Equations'), ('linear_equations_graphs', 'Linear Equations & Graphs'), ('application_of_functions', 'Application of Functions'), ('properties_of_functions', 'Properties of Functions'), ('trigonometry', 'Trigonometry'), ('voronoi_diagrams', 'Voronoi Diagrams'), ('descriptive_statistics', 'Descriptive Statistics'), ('bivariate_statistics', 'Bivariate Statistics'), ('probability', 'Probability'), ('distributions', 'Distributions'), ('geometry_shapes', 'Geometry of 3D Shapes'), ('hypothesis_testing', 'Hypothesis Testing'), ('differentiation', 'Differentiation'), ('integration', 'Integration')], default='null', max_length=100),
        ),
    ]
