# Generated by Django 5.2.6 on 2026-03-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0227_alter_past_paper_videos_topic1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_HL_Questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2'), ('paper3', 'Paper 3')], default='paper2', max_length=20)),
                ('chapter', models.CharField(choices=[('emergence_democratic_states', 'Emergence and Development of Democratic States'), ('authoritarian_states', 'Authoritarian States'), ('causes_effects_wars', 'Causes and Effects of 20th Century Wars'), ('cold_war', 'The Cold War: Superpower Tensions and Rivalries'), ('rights_protest', 'Rights and Protest'), ('conflict_intervention', 'Conflict and Intervention'), ('move_global_war', 'The Move to Global War'), ('independence_movements', 'Independence Movements'), ('history_europe', 'History of Europe'), ('history_americas', 'History of the Americas'), ('history_asia_oceania', 'History of Asia and Oceania'), ('history_africa_middle_east', 'History of Africa and the Middle East')], max_length=200)),
                ('title', models.TextField(help_text='The essay question/prompt')),
                ('command_term', models.CharField(choices=[('evaluate', 'Evaluate'), ('discuss', 'Discuss'), ('analyze', 'Analyze'), ('compare', 'Compare'), ('compare_contrast', 'Compare and Contrast'), ('examine', 'Examine'), ('to_what_extent', 'To What Extent'), ('assess', 'Assess'), ('explain', 'Explain')], default='evaluate', max_length=50)),
                ('explanation', models.TextField(help_text='Command term explanation')),
                ('intro', models.TextField(help_text='Introduction paragraph')),
                ('body', models.TextField(help_text='Body paragraphs (can include multiple paragraphs with headings)')),
                ('conclusion', models.TextField(blank=True, help_text='Conclusion paragraph', null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('marks', models.CharField(default='15', max_length=10)),
                ('type', models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='premium', max_length=10)),
                ('verified', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10)),
            ],
            options={
                'verbose_name': 'History HL - Questionbank',
                'verbose_name_plural': 'History HL - Questionbanks',
            },
        ),
        migrations.CreateModel(
            name='History_SL_Questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(choices=[('paper1', 'Paper 1'), ('paper2', 'Paper 2')], default='paper2', max_length=20)),
                ('chapter', models.CharField(choices=[('emergence_democratic_states', 'Emergence and Development of Democratic States'), ('authoritarian_states', 'Authoritarian States'), ('causes_effects_wars', 'Causes and Effects of 20th Century Wars'), ('cold_war', 'The Cold War: Superpower Tensions and Rivalries'), ('rights_protest', 'Rights and Protest'), ('conflict_intervention', 'Conflict and Intervention'), ('move_global_war', 'The Move to Global War'), ('independence_movements', 'Independence Movements')], max_length=200)),
                ('title', models.TextField(help_text='The essay question/prompt')),
                ('command_term', models.CharField(choices=[('evaluate', 'Evaluate'), ('discuss', 'Discuss'), ('analyze', 'Analyze'), ('compare', 'Compare'), ('compare_contrast', 'Compare and Contrast'), ('examine', 'Examine'), ('to_what_extent', 'To What Extent'), ('assess', 'Assess'), ('explain', 'Explain')], default='evaluate', max_length=50)),
                ('explanation', models.TextField(help_text='Command term explanation')),
                ('intro', models.TextField(help_text='Introduction paragraph')),
                ('body', models.TextField(help_text='Body paragraphs (can include multiple paragraphs with headings)')),
                ('conclusion', models.TextField(blank=True, help_text='Conclusion paragraph', null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('marks', models.CharField(default='15', max_length=10)),
                ('type', models.CharField(choices=[('free', 'free'), ('registered', 'registered'), ('premium', 'premium')], default='premium', max_length=10)),
                ('verified', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10)),
            ],
            options={
                'verbose_name': 'History SL - Questionbank',
                'verbose_name_plural': 'History SL - Questionbanks',
            },
        ),
    ]
