# Generated by Django 5.0 on 2026-03-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0228_history_hl_questionbank_history_sl_questionbank"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApexUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("tutor", "Tutor"),
                            ("admin", "Admin"),
                            ("student", "Student"),
                        ],
                        default="tutor",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "subjects",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of subjects",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("avatar", models.CharField(default="avatar1.png", max_length=200)),
                ("verified", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "verification_code_created",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Apex User",
                "verbose_name_plural": "Apex Users",
            },
        ),
    ]
