# Generated by Django 5.2.6 on 2026-03-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0229_apexusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apexusers',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='apexusers',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='apexusers',
            name='role',
        ),
        migrations.RemoveField(
            model_name='apexusers',
            name='status',
        ),
        migrations.RemoveField(
            model_name='apexusers',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='apexusers',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='apexusers',
            name='verification_code_created',
        ),
        migrations.AddField(
            model_name='apexusers',
            name='curriculum',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='apexusers',
            name='exam_session',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='apexusers',
            name='occupation',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='apexusers',
            name='school_name',
            field=models.CharField(default='No School Name Given', max_length=200),
        ),
        migrations.AlterField(
            model_name='apexusers',
            name='password',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='apexusers',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
