# Generated by Django 5.0 on 2026-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0230_remove_apexusers_bio_remove_apexusers_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apexusers",
            name="confirmed_teacher",
            field=models.BooleanField(
                default=False,
                help_text="Whether this teacher is confirmed as part of the company",
            ),
        ),
    ]
