# Generated by Django 5.0 on 2026-03-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0231_apexusers_confirmed_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premium_members",
            name="subscription_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("free", "Free"),
                    ("free_trial", "Free Trial"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("apex_teacher", "Apex Teacher"),
                ],
                default="none",
                max_length=20,
                null=True,
            ),
        ),
    ]
