# Generated by Django 5.2.6 on 2026-03-23 10:21

from django.db import migrations, models
import random
import string


def generate_customer_ids(apps, schema_editor):
    """Generate unique customer_ids for existing ApexUsers records"""
    ApexUsers = apps.get_model('website', 'ApexUsers')
    existing_ids = set()
    
    for user in ApexUsers.objects.all():
        # Generate a unique customer_id
        while True:
            new_id = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10))
            if new_id not in existing_ids:
                existing_ids.add(new_id)
                break
        user.customer_id = new_id
        user.save(update_fields=['customer_id'])


def reverse_customer_ids(apps, schema_editor):
    """Reverse migration - set all customer_ids to None"""
    ApexUsers = apps.get_model('website', 'ApexUsers')
    ApexUsers.objects.all().update(customer_id='None')


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0232_alter_premium_members_subscription_type'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='apexusers',
            name='customer_id',
            field=models.CharField(default='None', max_length=20),
        ),
        # Step 2: Populate unique customer_ids for existing records
        migrations.RunPython(generate_customer_ids, reverse_customer_ids),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='apexusers',
            name='customer_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
