# Generated by Django 5.0 on 2026-03-23 16:46

from django.db import migrations
import random
import string


def create_or_update_max_milstein_admin(apps, schema_editor):
    ApexUsers = apps.get_model('website', 'ApexUsers')
    Premium_Members = apps.get_model('website', 'Premium_Members')
    User = apps.get_model('auth', 'User')
    
    from django.utils import timezone
    from datetime import timedelta
    from django.contrib.auth.hashers import make_password
    
    email = 'max@apextuitionaustralia.com'
    
    # Check if user already exists
    existing_user = ApexUsers.objects.filter(email=email).first()
    if existing_user:
        # Update occupation to AdminExternal
        existing_user.occupation = 'AdminExternal'
        existing_user.confirmed_teacher = True
        existing_user.save()
        print(f"Updated user {email} occupation to AdminExternal")
        
        # Ensure premium membership exists
        if not Premium_Members.objects.filter(customer_id=existing_user.customer_id).exists():
            subscription_end = timezone.now() + timedelta(days=365)
            Premium_Members.objects.create(
                customer_id=existing_user.customer_id,
                stripe_customer_id='FREE',
                first_name='Max',
                last_name='Milstein',
                email=email,
                subscribed='Yes',
                subscription_type='apex_teacher',
                subscription_end_date=subscription_end
            )
        return
    
    # Generate unique customer_id
    customer_id = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10))
    while ApexUsers.objects.filter(customer_id=customer_id).exists():
        customer_id = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10))
    
    # Create Django User for authentication
    if not User.objects.filter(email=email).exists():
        user = User.objects.create(
            username=email,
            email=email,
            first_name='Max',
            last_name='Milstein',
            password=make_password('Apex2026!')
        )
    
    # Create ApexUsers entry with occupation='AdminExternal'
    apex_user = ApexUsers.objects.create(
        first_name='Max',
        last_name='Milstein',
        email=email,
        password='N/A',
        curriculum='IB',
        occupation='AdminExternal',
        exam_session='May2026',
        customer_id=customer_id,
        school_name='Apex Tuition Australia',
        avatar='avatar1.png',
        verified=True,
        confirmed_teacher=True
    )
    
    # Create Premium_Members entry for 1 year
    subscription_end = timezone.now() + timedelta(days=365)
    Premium_Members.objects.create(
        customer_id=customer_id,
        stripe_customer_id='FREE',
        first_name='Max',
        last_name='Milstein',
        email=email,
        subscribed='Yes',
        subscription_type='apex_teacher',
        subscription_end_date=subscription_end
    )
    
    print(f"Created AdminExternal user: Max Milstein ({email})")


def reverse_create_max_milstein_admin(apps, schema_editor):
    ApexUsers = apps.get_model('website', 'ApexUsers')
    Premium_Members = apps.get_model('website', 'Premium_Members')
    User = apps.get_model('auth', 'User')
    
    email = 'max@apextuitionaustralia.com'
    
    try:
        apex_user = ApexUsers.objects.get(email=email)
        customer_id = apex_user.customer_id
        Premium_Members.objects.filter(customer_id=customer_id).delete()
        apex_user.delete()
        User.objects.filter(email=email).delete()
        print(f"Deleted AdminExternal user: Max Milstein ({email})")
    except ApexUsers.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0233_apexusers_customer_id"),
    ]

    operations = [
        migrations.RunPython(create_or_update_max_milstein_admin, reverse_create_max_milstein_admin),
    ]
