# Generated by Django 5.0

from django.db import migrations


def fix_max_occupation(apps, schema_editor):
    ApexUsers = apps.get_model('website', 'ApexUsers')
    
    email = 'max@apextuitionaustralia.com'
    
    try:
        user = ApexUsers.objects.get(email=email)
        user.occupation = 'AdminExternal'
        user.confirmed_teacher = True
        user.save()
        print(f"Updated {email} occupation to AdminExternal")
    except ApexUsers.DoesNotExist:
        print(f"User {email} not found")


def reverse_fix(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0234_create_max_milstein_admin"),
    ]

    operations = [
        migrations.RunPython(fix_max_occupation, reverse_fix),
    ]
