# Generated by Django 5.0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0235_fix_max_milstein_occupation"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE website_apexusers DROP COLUMN IF EXISTS user_type;",
            reverse_sql="ALTER TABLE website_apexusers ADD COLUMN user_type VARCHAR(20) DEFAULT 'user';",
        ),
    ]
