# Generated by Django 5.0 on 2026-03-23 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0236_drop_user_type_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedexamspastpapers",
            name="apex_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_past_paper_exams",
                to="website.apexusers",
            ),
        ),
        migrations.AlterField(
            model_name="generatedexamspastpapers",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_past_paper_exams",
                to="website.users",
            ),
        ),
    ]
