# Generated by Django 5.0 on 2026-03-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0237_add_apex_user_to_generated_exams"),
    ]

    operations = [
        migrations.AddField(
            model_name="apexusers",
            name="source_domain",
            field=models.CharField(
                choices=[
                    ("apex", "Apex Tuition Australia"),
                    ("topibtutors", "Top IB Tutors"),
                ],
                default="apex",
                help_text="Which subdomain the user registered from",
                max_length=20,
            ),
        ),
    ]
