# Generated by Django 5.0 on 2026-04-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0240_past_paper_videos_markscheme_screenshots_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="math_ai_sl_questionbank",
            name="question_screenshots_url",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE website_math_ai_sl_questionbank DROP COLUMN IF EXISTS question_type;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
