# Generated by Django 5.0 on 2026-04-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0242_add_biology_sl_hl_past_paper_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="past_paper_videos_aa_hl",
            name="markscheme_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for markscheme screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_aa_sl",
            name="markscheme_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for markscheme screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_ai_hl",
            name="markscheme_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for markscheme screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_chemistry_hl",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("registered", "Registered"),
                    ("premium", "Premium"),
                ],
                default="premium",
                help_text="Access level for this video",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_chemistry_hl",
            name="correct_answer",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                help_text="For Paper 1A multiple-choice questions only",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_chemistry_hl",
            name="markscheme_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for markscheme screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_chemistry_sl",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("registered", "Registered"),
                    ("premium", "Premium"),
                ],
                default="premium",
                help_text="Access level for this video",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_chemistry_sl",
            name="correct_answer",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                help_text="For Paper 1A multiple-choice questions only",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_chemistry_sl",
            name="markscheme_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for markscheme screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_physics_hl",
            name="correct_answer",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                help_text="For Paper 1A multiple-choice questions only",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_physics_hl",
            name="markscheme_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for markscheme screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_physics_sl",
            name="correct_answer",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                help_text="For Paper 1A multiple-choice questions only",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_physics_sl",
            name="markscheme_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for markscheme screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
    ]
