# Generated by Django 5.0 on 2026-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0243_add_markscheme_and_correct_answer_to_past_papers"),
    ]

    operations = [
        migrations.AddField(
            model_name="past_paper_videos_comp_sci_hl",
            name="markscheme_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for markscheme screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_comp_sci_hl",
            name="question_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for question screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_comp_sci_sl",
            name="markscheme_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for markscheme screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="past_paper_videos_comp_sci_sl",
            name="question_screenshots_url",
            field=models.TextField(
                blank=True,
                help_text="ImageKit URL for question screenshots (comma-separated if multiple)",
                null=True,
            ),
        ),
    ]
