# Generated by Django 5.0 on 2026-04-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0244_add_screenshots_to_comp_sci_past_papers"),
    ]

    operations = [
        migrations.AddField(
            model_name="history_sl_questionbank",
            name="hl_question_id",
            field=models.IntegerField(
                blank=True, help_text="ID of corresponding HL question", null=True
            ),
        ),
        migrations.AddField(
            model_name="history_sl_questionbank",
            name="sync_to_hl",
            field=models.BooleanField(
                default=True, help_text="Automatically sync this question to History HL"
            ),
        ),
    ]
