# Generated by Django 5.2.6 on 2026-04-24 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0246_add_revision_engine"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionSubQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'a', 'b', 'c'. Leave blank for single-part questions.",
                        max_length=10,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="Sub-question text (LaTeX/HTML supported)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subquestions",
                        to="website.math_ai_sl_questionbank",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("question", "part_label")},
            },
        ),
        migrations.CreateModel(
            name="RevisionMCQOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                (
                    "option_text",
                    models.TextField(
                        help_text="Answer option text (LaTeX/HTML supported)"
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "subquestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="website.revisionsubquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "unique_together": {("subquestion", "label")},
            },
        ),
    ]
