# Generated by Django 5.2.6 on 2026-04-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0247_add_revision_mcq_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisionattempt",
            name="selected_label",
            field=models.CharField(
                blank=True,
                help_text="Which MCQ option was chosen (A/B/C/D)",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="revisionattempt",
            name="subquestion",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific sub-part that was answered",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="website.revisionsubquestion",
            ),
        ),
    ]
