# Generated by Django 5.0 on 2026-05-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0248_add_subquestion_and_label_to_revision_attempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Journey_Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(db_index=True, max_length=255)),
                (
                    "visitor_id",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("ip_address", models.CharField(default="null", max_length=255)),
                ("device", models.CharField(default="null", max_length=255)),
                ("country", models.CharField(default="null", max_length=255)),
                ("journey_path", models.JSONField()),
                ("session_start", models.DateTimeField()),
                ("session_end", models.DateTimeField()),
                ("date_created", models.DateTimeField()),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user_journey",
            name="email",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user_journey",
            name="ip_address",
            field=models.CharField(db_index=True, default="null", max_length=255),
        ),
        migrations.AlterField(
            model_name="user_journey",
            name="session_end",
            field=models.DateTimeField(db_index=True),
        ),
    ]
