# Generated by Django 5.0 on 2026-05-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0249_archive_user_journey_and_add_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="math_ai_sl_questionbank",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("number_skills", "Number Skills"),
                    ("seq_series", "Sequences & Series"),
                    ("systems_lin_eq", "Systems of Linear Equations"),
                    ("lin_eq_graphs", "Linear Equations & Graphs"),
                    ("hypothesis_testing", "Hypothesis Testing"),
                    ("trigonometry", "Trigonometry"),
                    ("applications_of_functions", "Applications of Functions"),
                    ("voronoi_diagrams", "Voronoi Diagrams"),
                    ("probability", "Probability"),
                    ("properties_of_functions", "Properties of Functions"),
                    ("integration", "Integration"),
                    ("distributions", "Distributions"),
                    ("geometry_shapes", "Geometry & Shapes"),
                    ("descriptive_stats", "Descriptive Statistics"),
                    ("differentiation", "Differentiation"),
                    ("bivariate_statistics", "Bivariate Statistics"),
                ],
                db_index=True,
                default="",
                help_text="Primary chapter",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="math_ai_sl_questionbank",
            name="chapter2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("number_skills", "Number Skills"),
                    ("seq_series", "Sequences & Series"),
                    ("systems_lin_eq", "Systems of Linear Equations"),
                    ("lin_eq_graphs", "Linear Equations & Graphs"),
                    ("hypothesis_testing", "Hypothesis Testing"),
                    ("trigonometry", "Trigonometry"),
                    ("applications_of_functions", "Applications of Functions"),
                    ("voronoi_diagrams", "Voronoi Diagrams"),
                    ("probability", "Probability"),
                    ("properties_of_functions", "Properties of Functions"),
                    ("integration", "Integration"),
                    ("distributions", "Distributions"),
                    ("geometry_shapes", "Geometry & Shapes"),
                    ("descriptive_stats", "Descriptive Statistics"),
                    ("differentiation", "Differentiation"),
                    ("bivariate_statistics", "Bivariate Statistics"),
                ],
                db_index=True,
                default="",
                help_text="Secondary chapter (optional)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="math_ai_sl_questionbank",
            name="chapter3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("number_skills", "Number Skills"),
                    ("seq_series", "Sequences & Series"),
                    ("systems_lin_eq", "Systems of Linear Equations"),
                    ("lin_eq_graphs", "Linear Equations & Graphs"),
                    ("hypothesis_testing", "Hypothesis Testing"),
                    ("trigonometry", "Trigonometry"),
                    ("applications_of_functions", "Applications of Functions"),
                    ("voronoi_diagrams", "Voronoi Diagrams"),
                    ("probability", "Probability"),
                    ("properties_of_functions", "Properties of Functions"),
                    ("integration", "Integration"),
                    ("distributions", "Distributions"),
                    ("geometry_shapes", "Geometry & Shapes"),
                    ("descriptive_stats", "Descriptive Statistics"),
                    ("differentiation", "Differentiation"),
                    ("bivariate_statistics", "Bivariate Statistics"),
                ],
                db_index=True,
                default="",
                help_text="Third chapter (optional)",
                max_length=200,
            ),
        ),
    ]
