# Generated by Django 5.0 on 2026-05-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0250_add_chapter_indexes_math_ai_sl"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorsession",
            name="session_transcript",
            field=models.FileField(
                blank=True,
                help_text="Upload session transcript (PDF or TXT)",
                null=True,
                upload_to="session_transcripts/%Y/%m/%d/",
            ),
        ),
    ]
