# Generated by Django 5.0 on 2026-05-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0252_add_class_transcript_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisionsubquestion",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skill(s) this specific sub-part tests.",
                related_name="subquestions",
                to="website.revisionskill",
            ),
        ),
    ]
