# Generated by Django 5.0 on 2026-05-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0253_add_skills_m2m_to_subquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPathProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lp_progress",
                        to="website.classtranscriptanalysis",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lp_progress",
                        to="website.revisionskill",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lp_progress",
                        to="website.users",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("student", "analysis", "skill")},
            },
        ),
    ]
