# Generated by hand: MCQ subquestions for Math AI SL Q179 (systems of linear equations).

from django.db import migrations


MCQ_ROWS = (
    (
        'a',
        0,
        'Which system corresponds to the first three households when \\(x,y,z\\) are appliance '
        'powers in watts \\((hours)(watts)=1000\\times \\mathrm{kWh}\\) on the RHS totals)?',
        (
            ('A', False, r'\(24x+5y+4z=1.272,\ 9x+12y+16z=1.215,\ 15x+8y+7z=1.128\)'),
            ('B', False, r'\(24x+5y+4z=1272,\ 9x+12y+16z=6075,\ 15x+8y+7z=1128\)'),
            ('C', True, r'\(24x+5y+4z=1272,\ 9x+12y+16z=1215,\ 15x+8y+7z=1128\)'),
            ('D', False, r'\(24x+12y+5z=1272,\ 9x+5y+16z=1215,\ 15x+8y+7z=1128\)'),
        ),
    ),
    (
        'b',
        1,
        'Find \\(x\\), \\(y\\), and \\(z\\) (approximate wattages per appliance).',
        (
            ('A', False, r'\(x=30,\ y=39,\ z=9\)'),
            ('B', True, r'\(x=39,\ y=60,\ z=9\)'),
            ('C', False, r'\(x=39,\ y=60,\ z=900\)'),
            ('D', False, r'\(x=-39,\ y=60,\ z=9\)'),
        ),
    ),
    (
        'c',
        2,
        'What is the power consumption of Sarah\'s washing machine in W?',
        (
            ('A', False, r'\(840\ \\mathrm{W}\)'),
            ('B', True, r'\(3168\ \\mathrm{W}\)'),
            ('C', False, r'\(6336\ \\mathrm{W}\)'),
            ('D', False, r'\(1800\ \\mathrm{W}\)'),
        ),
    ),
)


def forwards(apps, schema_editor):
    MathQB = apps.get_model('website', 'Math_AI_SL_Questionbank')
    RevisionSkill = apps.get_model('website', 'RevisionSkill')
    RevisionSubQuestion = apps.get_model('website', 'RevisionSubQuestion')
    RevisionMCQOption = apps.get_model('website', 'RevisionMCQOption')

    if not MathQB.objects.filter(pk=179).exists():
        return

    skill = RevisionSkill.objects.filter(slug='solving_linear_systems').first()
    if not skill:
        return

    # Idempotent — do not overwrite if anything already wired for Q179 (manual edits honoured).
    if RevisionSubQuestion.objects.filter(question_id=179).exists():
        return

    for part_label, order, stem, options in MCQ_ROWS:
        sq = RevisionSubQuestion.objects.create(
            question_id=179,
            part_label=part_label,
            question_text=stem,
            order=order,
        )
        sq.skills.add(skill)
        for label, _is_corr, txt in options:
            RevisionMCQOption.objects.create(
                subquestion=sq,
                label=label,
                option_text=txt,
                is_correct=_is_corr,
            )


def backwards(apps, schema_editor):
    RevisionMCQOption = apps.get_model('website', 'RevisionMCQOption')
    RevisionSubQuestion = apps.get_model('website', 'RevisionSubQuestion')

    sq_ids = list(
        RevisionSubQuestion.objects.filter(question_id=179).values_list('pk', flat=True)
    )
    if not sq_ids:
        return
    RevisionMCQOption.objects.filter(subquestion_id__in=sq_ids).delete()
    RevisionSubQuestion.objects.filter(pk__in=sq_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0254_add_learning_path_progress'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
