# Generated by Django 5.0 on 2026-05-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0256_fix_revision_q275_part_b_mcqs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="past_paper_videos",
            name="time_zone",
            field=models.CharField(
                choices=[
                    ("null", "null"),
                    ("0", "0"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                ],
                default="null",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="past_paper_videos_aa_hl",
            name="time_zone",
            field=models.CharField(
                choices=[("0", "0"), ("1", "1"), ("2", "2"), ("3", "3")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="past_paper_videos_aa_sl",
            name="time_zone",
            field=models.CharField(
                choices=[("0", "0"), ("1", "1"), ("2", "2"), ("3", "3")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="past_paper_videos_ai_hl",
            name="time_zone",
            field=models.CharField(
                choices=[("0", "0"), ("1", "1"), ("2", "2"), ("3", "3")],
                default="1",
                max_length=10,
            ),
        ),
    ]
