# Generated by Django 5.0 on 2026-05-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0257_past_paper_videos_tz3_choices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="revisionsubquestion",
            options={"ordering": ["order", "id"]},
        ),
    ]
