# Generated by hand: MCQ subquestions for Math AI SL Q289 and Q298 (descriptive stats / hypothesis testing).

from django.db import migrations


def _options(rows):
    return tuple((label, is_correct, text) for label, is_correct, text in rows)


Q289_ROWS = (
    (
        'a.i',
        0,
        'Estimate the mean mass of the oranges from the grouped data.',
        ('frequency_tables',),
        _options((
            ('A', True, r'\(146\text{ g}\)'),
            ('B', False, r'\(148\text{ g}\)'),
            ('C', False, r'\(131\text{ g}\)'),
            ('D', False, r'\(165\text{ g}\)'),
        )),
    ),
    (
        'a.ii',
        1,
        'Estimate the standard deviation of the masses.',
        ('summary_statistics',),
        _options((
            ('A', False, r'\(148\)'),
            ('B', True, r'\(11.6\)'),
            ('C', False, r'\(7.83\)'),
            ('D', False, r'\(12\)'),
        )),
    ),
    (
        'b',
        2,
        r'Estimate the percentage of oranges heavier than \(165\text{ g}\).',
        ('frequency_tables',),
        _options((
            ('A', False, r'\(84.2\%\)'),
            ('B', False, r'\(12\%\)'),
            ('C', True, r'\(7.83\%\)'),
            ('D', False, r'\(8.0\%\)'),
        )),
    ),
    (
        'c',
        3,
        r'Given that 8% of oranges have mass less than \(y\), find \(y\).',
        ('frequency_tables',),
        _options((
            ('A', True, r'\(131\text{ g}\)'),
            ('B', False, r'\(146\text{ g}\)'),
            ('C', False, r'\(165\text{ g}\)'),
            ('D', False, r'\(120\text{ g}\)'),
        )),
    ),
    (
        'd',
        4,
        'Estimate the percentage of medium-sized oranges.',
        ('frequency_tables',),
        _options((
            ('A', False, r'\(7.83\%\)'),
            ('B', True, r'\(84.2\%\)'),
            ('C', False, r'\(92\%\)'),
            ('D', False, r'\(50\%\)'),
        )),
    ),
    (
        'e',
        5,
        'The shipment contains approximately 18000 oranges. Estimate how many are heavy.',
        ('frequency_tables',),
        _options((
            ('A', True, '1410'),
            ('B', False, '1800'),
            ('C', False, '783'),
            ('D', False, '1510'),
        )),
    ),
)

Q298_ROWS = (
    (
        'a',
        0,
        'How many households own at least 4 bicycles?',
        ('frequency_tables',),
        _options((
            ('A', True, '54'),
            ('B', False, '86'),
            ('C', False, '46'),
            ('D', False, '68'),
        )),
    ),
    (
        'b',
        1,
        'Find the probability that a household owns fewer than 3 bicycles.',
        ('frequency_tables',),
        _options((
            ('A', False, '0.300'),
            ('B', False, '0.522'),
            ('C', True, '0.478'),
            ('D', False, '0.700'),
        )),
    ),
    (
        'c.i',
        2,
        'Find the mode.',
        ('frequency_tables',),
        _options((
            ('A', False, '1'),
            ('B', True, '2'),
            ('C', False, '3'),
            ('D', False, '4'),
        )),
    ),
    (
        'c.ii',
        3,
        'Find the median number of bicycles.',
        ('summary_statistics',),
        _options((
            ('A', False, '2'),
            ('B', False, '4'),
            ('C', False, '1'),
            ('D', True, '3'),
        )),
    ),
    (
        'c.iii',
        4,
        'Find the interquartile range.',
        ('summary_statistics',),
        _options((
            ('A', True, '2'),
            ('B', False, '1'),
            ('C', False, '3'),
            ('D', False, '4'),
        )),
    ),
    (
        'd.i',
        5,
        'State the null hypothesis.',
        ('frequency_tables',),
        _options((
            ('A', True, 'Holiday preference and age group are independent.'),
            ('B', False, 'Holiday preference depends on age group.'),
            ('C', False, 'There is correlation.'),
            ('D', False, 'All frequencies are equal.'),
        )),
    ),
    (
        'd.ii',
        6,
        'State the alternative hypothesis.',
        ('frequency_tables',),
        _options((
            ('A', False, 'Holiday preference and age group are independent.'),
            ('B', True, 'Holiday preference depends on age group.'),
            ('C', False, 'No association exists.'),
            ('D', False, 'All expected frequencies are equal.'),
        )),
    ),
    (
        'e',
        7,
        'Find the degrees of freedom.',
        ('frequency_tables',),
        _options((
            ('A', False, '2'),
            ('B', False, '6'),
            ('C', True, '4'),
            ('D', False, '9'),
        )),
    ),
    (
        'f',
        8,
        'Find the expected frequency for adults aged 30–49 who prefer city holidays.',
        ('frequency_tables',),
        _options((
            ('A', True, '25.8'),
            ('B', False, '26.0'),
            ('C', False, '22.0'),
            ('D', False, '68.0'),
        )),
    ),
    (
        'g',
        9,
        'Find the p-value.',
        ('frequency_tables',),
        _options((
            ('A', False, '0.050'),
            ('B', False, '0.822'),
            ('C', True, '0.178'),
            ('D', False, '0.025'),
        )),
    ),
    (
        'h',
        10,
        'State the conclusion of the test.',
        ('frequency_tables',),
        _options((
            ('A', False, r'Reject \(H_0\).'),
            ('B', True, r'Fail to reject \(H_0\); insufficient evidence of dependence.'),
            ('C', False, r'Accept \(H_1\).'),
            ('D', False, 'Perfect association exists.'),
        )),
    ),
)


def _seed_question(apps, question_id, rows):
    MathQB = apps.get_model('website', 'Math_AI_SL_Questionbank')
    RevisionSkill = apps.get_model('website', 'RevisionSkill')
    RevisionSubQuestion = apps.get_model('website', 'RevisionSubQuestion')
    RevisionMCQOption = apps.get_model('website', 'RevisionMCQOption')

    if not MathQB.objects.filter(pk=question_id).exists():
        return

    if RevisionSubQuestion.objects.filter(question_id=question_id).exists():
        return

    skill_cache = {}
    for part_label, order, stem, skill_slugs, options in rows:
        sq = RevisionSubQuestion.objects.create(
            question_id=question_id,
            part_label=part_label,
            question_text=stem,
            order=order,
        )
        for slug in skill_slugs:
            if slug not in skill_cache:
                skill_cache[slug] = RevisionSkill.objects.filter(slug=slug).first()
            skill = skill_cache[slug]
            if skill:
                sq.skills.add(skill)
        for label, is_correct, text in options:
            RevisionMCQOption.objects.create(
                subquestion=sq,
                label=label,
                option_text=text,
                is_correct=is_correct,
            )


def forwards(apps, schema_editor):
    _seed_question(apps, 289, Q289_ROWS)
    _seed_question(apps, 298, Q298_ROWS)


def backwards(apps, schema_editor):
    RevisionMCQOption = apps.get_model('website', 'RevisionMCQOption')
    RevisionSubQuestion = apps.get_model('website', 'RevisionSubQuestion')

    sq_ids = list(
        RevisionSubQuestion.objects.filter(question_id__in=(289, 298)).values_list('pk', flat=True)
    )
    if not sq_ids:
        return
    RevisionMCQOption.objects.filter(subquestion_id__in=sq_ids).delete()
    RevisionSubQuestion.objects.filter(pk__in=sq_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0258_alter_revisionsubquestion_meta_ordering'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
