# Generated by Django 5.2.6 on 2026-06-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0265_replace_q287_mcqs"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutoringLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("ib_year", models.CharField(blank=True, max_length=50)),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
