# Generated by Django 5.0 on 2026-06-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "personal_email",
                    models.EmailField(blank=True, default="", max_length=200),
                ),
                (
                    "edunade_email",
                    models.EmailField(blank=True, default="", max_length=200),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "school_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("curriculum", models.CharField(blank=True, default="", max_length=50)),
                (
                    "graduation_year",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("subjects", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personal Profile",
                "verbose_name_plural": "Personal Profiles",
            },
        ),
    ]
