# Generated by Django 5.0 on 2026-06-11 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_grades", models.TextField(blank=True, default="")),
                ("standardized_tests", models.TextField(blank=True, default="")),
                (
                    "extracurricular_activities",
                    models.TextField(blank=True, default=""),
                ),
                ("awards_competitions", models.TextField(blank=True, default="")),
                (
                    "transcripts",
                    models.FileField(
                        blank=True, null=True, upload_to="academic/transcripts/"
                    ),
                ),
                (
                    "cv_upload",
                    models.FileField(blank=True, null=True, upload_to="academic/cv/"),
                ),
                (
                    "personal_statement_upload",
                    models.FileField(
                        blank=True, null=True, upload_to="academic/personal_statements/"
                    ),
                ),
                ("intended_course_interests", models.TextField(blank=True, default="")),
                ("country_preferences", models.TextField(blank=True, default="")),
                (
                    "budget_expectations",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("parent_input", models.TextField(blank=True, default="")),
                ("career_goals", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personal_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_profile",
                        to="portal.personalprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Profile",
                "verbose_name_plural": "Academic Profiles",
            },
        ),
    ]
