# Generated by Django 6.0.6 on 2026-06-15 18:25

from django.db import migrations, models


def backfill_platform_user_identity(apps, schema_editor):
    PlatformUser = apps.get_model('portal', 'PlatformUser')
    for platform_user in PlatformUser.objects.select_related('user').all():
        user = platform_user.user
        platform_user.first_name = user.first_name
        platform_user.last_name = user.last_name
        platform_user.email = user.email
        platform_user.account_created_at = user.date_joined
        platform_user.save(update_fields=[
            'first_name',
            'last_name',
            'email',
            'account_created_at',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_alter_personalprofile_session_key_platformuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformuser",
            name="account_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformuser",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="platformuser",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="platformuser",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.RunPython(backfill_platform_user_identity, migrations.RunPython.noop),
    ]
