# Generated by Django 6.0.6 on 2026-08-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_portfoliodesignelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdocument',
            name='document_type',
            field=models.CharField(choices=[('transcript', 'Transcript'), ('cv', 'CV'), ('final_diploma', 'Final diploma'), ('language_certificate', 'Language certificate'), ('exam_results', 'Exam results'), ('other', 'Other')], max_length=50),
        ),
    ]
