from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
# from .sitemaps import StaticViewSitemap
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.http import JsonResponse
from django.views.static import serve
import json
import os





# sitemaps = {
#     'static': StaticViewSitemap,
# }

# Define a view to serve the JSON data directly


urlpatterns = [
    path('admin/', admin.site.urls),
    # Serve favicon.ico from root for better Google Search visibility
    path('favicon.ico', serve, {'path': 'website/images/favicon.ico', 'document_root': settings.STATIC_ROOT}),
    path('', views.landing, name="landing"),
    path('login/', views.login, name="login"),
    path('register/', views.register, name="register"),
    path('register-qr-code/', views.register_qr_code, name="register-qr-code"),
    path('verify-email/', views.verify_email, name="verify-email"),
    path('resend-verification-code/', views.resend_verification_code, name="resend-verification-code"),
    path('logout/', views.logout_view, name="logout"),
    path('forgot-password/', views.forgot_password, name="forgot-password"),
    path('reset-password/<str:uidb64>/<str:token>/', views.reset_password, name="reset-password"),
    path("fillout-webhook/", views.fillout_webhook, name="fillout-webhook"),
    path('calendar/', views.calendar, name="calendar"),
    path('timeline/', views.timeline, name="timeline"), 
    path('home/', views.home, name="home"),
    path('account/', views.account, name="account"),
    path('activate-referral-code/', views.activate_referral_code, name="activate-referral-code"),
    path('send-referral-email/', views.send_referral_email, name="send-referral-email"),
    path('security/', views.security, name="security"),
    path('subscription/', views.subscription, name="subscription"),
    path('pricing/', views.pricing, name="pricing"),
    path('pricing2/', views.pricing2, name="pricing2"),  # Test page for trial subscription
    path('faq/', views.faq, name="faq"),
    path('data-processing-terms/', views.data_processing_terms, name="data-processing-terms"),
    path('privacy-policy/', views.privacy_policy, name="privacy-policy"),
    path('questionbank/', views.questionbank, name="questionbank"),
    path('university-database/', views.uni_database, name="uni-database"),
    path('survey-results/', views.suitability_survey, name="suitability-survey"),
    path('contact/', views.contact, name="contact"),
    path('university-documents/', views.pdf_viewer, name="uni-docs"),
    path('success/', views.success, name="success"),
    path('success-trial/', views.success_trial, name="success-trial"),
    path('questionpreview/', views.questionpreview, name="questionpreview"),
    path('past-papers/', views.past_papers, name="past-papers"),
    path('gpt/', views.gpt, name="gpt"),
    path('api/chatgpt-query/', views.chatgpt_query, name='chatgpt_query'),
    path('api/generate-similar-question/', views.generate_similar_question_api, name='generate-similar-question'),
    path('api/generate-explanation/', views.generate_explanation_api, name='generate-explanation'),
    path('api/get-topics/', views.get_topics_api, name='get-topics'),
    path('api/get-questions/', views.get_questions_api, name='get-questions'),
    path('ai-question-generator/', views.ai_question_generator, name='ai-question-generator'),
    path('ai-question-generator-2/', views.ai_question_generator_2, name='ai-question-generator-2'),
    path('api/pdf-questions/', views.get_pdf_questions_api, name='get-pdf-questions'),
    # path('tutoring/', views.tutoring, name="tutoring"),
    path('tutoring/', views.tutoring2, name="tutoring"),
    path('tutoring-landing/', views.tutoring_landing, name="tutoring-landing"),
    path('tutoring-landing/thank-you/', views.tutoring_landing_thank_you, name="tutoring-landing-thank-you"),
    path('vimeo-test/', views.vimeo_test, name="vimeo-test"),
    
    # Exam Builder Routes
    path('exam-builder/', views.exam_builder_landing, name="exam-builder"),
    path('exam-builder/questionbank/', views.exam_builder_questionbank, name="exam-builder-questionbank"),
    path('exam-builder/past-papers/', views.exam_builder_past_papers, name="exam-builder-past-papers"),
    path('exam-answers/', views.exam_answers, name="exam-answers"),
    # path('tour-123/', views.tour, name="tour"),

    # Webinars
    path('webinars/', views.webinars, name="webinars-recorded"),
    path('webinars-live/', views.webinars_live, name="webinars-live"),
    path('webinars/interview-preparation/', views.webinar_interview_preparation, name="webinar-interview-preparation"),
    path('webinars/cv/', views.webinar_cv, name="webinar-cv"),  
    path('webinars/studying-around-the-world/', views.webinar_around_the_world, name="webinar-around-the-world"),
    path('webinars/suitability-advice/', views.webinar_suitability, name="webinar-suitability"),
    path('webinars/application-portals/', views.webinar_application_portals, name="webinar-application-portals"),
    path('webinars/ias-ees-revision-tips/', views.webinar_ias_ees, name="webinar-ias-ees"),
    path('webinars/university-documents/', views.webinar_uni_docs, name="webinar-uni-docs"),
    path('webinars/personal-statement/', views.webinar_personal_statement, name="webinar-personal-statement"),
    path('webinars/studying-abroad/', views.webinar_why_study_abroad, name="webinar-why-study-abroad"),
    path('webinars/surviving-a-degree/', views.webinar_surviving_a_degree, name="webinar-surviving-a-degree"),
    path('webinars/gap-year/', views.webinar_gap_year, name="webinar-gap-year"),

    # Math AI SL Questionbank
    path('ib-hub/math-ai-sl/', views.math_ai_sl, name='math-ai-sl'),
    path('ib-hub/math-ai-sl/number-skills/', views.number_skills_ai_sl, name='number-skills-ai-sl'),
    path('ib-hub/math-ai-sl/sequences-and-series/', views.seq_series_ai_sl, name='seq-series-ai-sl'),
    path('ib-hub/math-ai-sl/linear-equations-and-graphs/', views.lin_eq_graphs_ai_sl, name='lin-eq-graphs-ai-sl'),
    path('api/math-ai-sl-questions/', views.Math_AI_SL_QuestionsListAPIView.as_view(), name='math-ai-sl-questions-list'),
    path('api/chatgpt-query/', views.chatgpt_query, name='chatgpt-query'),
    path('ib-hub/math-ai-sl/systems-of-linear-equations/', views.systems_lin_eq_ai_sl, name='systems-lin-eq-ai-sl'),
    path('ib-hub/math-ai-sl/hypothesis-testing/', views.hypothesis_testing_ai_sl, name='hypothesis-testing-ai-sl'),
    path('ib-hub/math-ai-sl/trigonometry/', views.trigonometry_ai_sl, name='trigonometry-ai-sl'),
    path('ib-hub/math-ai-sl/applications-of-functions/', views.applications_of_functions_ai_sl, name='applications-of-functions-ai-sl'),
    path('ib-hub/math-ai-sl/voronoi-diagrams/', views.voronoi_diagrams_ai_sl, name='voronoi-diagrams-ai-sl'),
    path('ib-hub/math-ai-sl/probability/', views.probability_ai_sl, name='probability-ai-sl'),
    path('ib-hub/math-ai-sl/properties-of-functions/', views.properties_of_functions_ai_sl, name='properties-of-functions-ai-sl'),
    path('ib-hub/math-ai-sl/integration/', views.integration_ai_sl, name='integration-ai-sl'),
    path('ib-hub/math-ai-sl/distributions/', views.distributions_ai_sl, name='distributions-ai-sl'),
    path('ib-hub/math-ai-sl/geometry-of-3d-shapes/', views.geometry_shapes_ai_sl, name='geometry-shapes-ai-sl'),
    path('ib-hub/math-ai-sl/descriptive-statistics/', views.descriptive_stats_ai_sl, name='descriptive-stats-ai-sl'),
    path('ib-hub/math-ai-sl/differentiation/', views.differentiation_ai_sl, name='differentiation-ai-sl'),
    path('ib-hub/math-ai-sl/bivariate-statistics/', views.bivariate_statistics_ai_sl, name='bivariate-statistics-ai-sl'),

    # Math AI SL Past Papers
    path('past-papers/math-ai-sl/', views.math_ai_sl_past_papers, name='math-ai-sl-past-papers'),
    path('past-papers/math-ai-sl/may-2025-tz1-p1/', views.math_ai_sl_may25tz1p1, name='math-ai-sl-may25tz1p1'),
    path('past-papers/math-ai-sl/may-2025-tz1-p2/', views.math_ai_sl_may25tz1p2, name='math-ai-sl-may25tz1p2'),
    path('past-papers/math-ai-sl/may-2024-tz1-p1/', views.math_ai_sl_may24tz1p1, name='math-ai-sl-may24tz1p1'),
    path('past-papers/math-ai-sl/may-2024-tz1-p2/', views.math_ai_sl_may24tz1p2, name='math-ai-sl-may24tz1p2'),
    path('past-papers/math-ai-sl/may-2023-tz1-p1/', views.math_ai_sl_may23tz1p1, name='math-ai-sl-may23tz1p1'),
    path('past-papers/math-ai-sl/may-2023-tz1-p2/', views.math_ai_sl_may23tz1p2, name='math-ai-sl-may23tz1p2'),
    path('past-papers/math-ai-sl/may-2023-tz2-p1/', views.math_ai_sl_may23tz2p1, name='math-ai-sl-may23tz2p1'),
    path('past-papers/math-ai-sl/may-2023-tz2-p2/', views.math_ai_sl_may23tz2p2, name='math-ai-sl-may23tz2p2'),
    path('past-papers/math-ai-sl/nov-2023-tz1-p1/', views.math_ai_sl_nov23tz1p1, name='math-ai-sl-nov23tz1p1'),
    path('past-papers/math-ai-sl/nov-2023-tz1-p2/', views.math_ai_sl_nov23tz1p2, name='math-ai-sl-nov23tz1p2'),
    path('past-papers/math-ai-sl/may-2022-tz1-p1/', views.math_ai_sl_may22tz1p1, name='math-ai-sl-may22tz1p1'),
    path('past-papers/math-ai-sl/may-2022-tz1-p2/', views.math_ai_sl_may22tz1p2, name='math-ai-sl-may22tz1p2'),
    path('past-papers/math-ai-sl/may-2021-tz1-p1/', views.math_ai_sl_may21tz1p1, name='math-ai-sl-may21tz1p1'),
    path('past-papers/math-ai-sl/may-2021-tz1-p2/', views.math_ai_sl_may21tz1p2, name='math-ai-sl-may21tz1p2'),
    path('past-papers/math-ai-sl/may-2021-tz2-p1/', views.math_ai_sl_may21tz2p1, name='math-ai-sl-may21tz2p1'),
    path('past-papers/math-ai-sl/may-2021-tz2-p2/', views.math_ai_sl_may21tz2p2, name='math-ai-sl-may21tz2p2'),
    path('past-papers/math-ai-sl/nov-2021-tz0-p1/', views.math_ai_sl_nov21tz0p1, name='math-ai-sl-nov21tz0p1'),
    path('past-papers/math-ai-sl/nov-2021-tz0-p2/', views.math_ai_sl_nov21tz0p2, name='math-ai-sl-nov21tz0p2'),

    # Math Past Papers PDF Generator (supports all subjects: AI SL, AI HL, AA SL, AA HL)
    path('past-papers/math/pdf-generator/', views.math_ai_sl_pdf_generator, name='math-pdf-generator'),
    path('past-papers/math/generate-pdf/', views.math_ai_sl_generate_pdf, name='math-generate-pdf'),
    # Legacy URLs for backward compatibility
    path('past-papers/math-ai-sl/pdf-generator/', views.math_ai_sl_pdf_generator, name='math-ai-sl-pdf-generator'),
    path('past-papers/math-ai-sl/generate-pdf/', views.math_ai_sl_generate_pdf, name='math-ai-sl-generate-pdf'),
    
    # Saved Exams endpoints
    path('saved-exams/', views.get_saved_exams, name='get_saved_exams'),
    path('download-saved-exam/<int:exam_id>/', views.download_saved_exam, name='download_saved_exam'),
    path('delete-saved-exam/<int:exam_id>/', views.delete_saved_exam, name='delete_saved_exam'),

    # Math AI SL Past Papers Topics
    path('past-papers-topics/math-ai-sl/', views.math_ai_sl_past_papers_topics, name='math-ai-sl-past-papers-topics'),
    path('past-papers-topics/math-ai-sl/number-skills/', views.math_ai_sl_number_skills_videos, name='math-ai-sl-number-skills-videos'),
    path('past-papers-topics/math-ai-sl/sequences-and-series/', views.math_ai_sl_seq_series_videos, name='math-ai-sl-seq-series-videos'),
    path('past-papers-topics/math-ai-sl/systems-of-linear-equations/', views.math_ai_sl_systems_of_equations_videos, name='math-ai-sl-systems-of-equations-videos'),
    path('past-papers-topics/math-ai-sl/linear-equations-and-graphs/', views.math_ai_sl_lin_eq_graphs_videos, name='math-ai-sl-lin-eq-graphs-videos'),
    path('past-papers-topics/math-ai-sl/application-of-functions/', views.math_ai_sl_application_of_functions_videos, name='math-ai-sl-application-of-functions-videos'),
    path('past-papers-topics/math-ai-sl/properties-of-functions/', views.math_ai_sl_properties_of_functions_videos, name='math-ai-sl-properties-of-functions-videos'),
    path('past-papers-topics/math-ai-sl/geometry-of-3d-shapes/', views.math_ai_sl_geometry_shapes_videos, name='math-ai-sl-geometry-of-3d-shapes-videos'),
    path('past-papers-topics/math-ai-sl/voronoi-diagrams/', views.math_ai_sl_voronoi_diagrams_videos, name='math-ai-sl-voronoi-diagrams-videos'),
    path('past-papers-topics/math-ai-sl/trigonometry/', views.math_ai_sl_trigonometry_videos, name='math-ai-sl-trigonometry-videos'),
    path('past-papers-topics/math-ai-sl/hypothesis-testing/', views.math_ai_sl_hypothesis_testing_videos, name='math-ai-sl-hypothesis-testing-videos'),
    path('past-papers-topics/math-ai-sl/probability/', views.math_ai_sl_probability_videos, name='math-ai-sl-probability-videos'),
    path('past-papers-topics/math-ai-sl/distributions/', views.math_ai_sl_distributions_videos, name='math-ai-sl-distributions-videos'),
    path('past-papers-topics/math-ai-sl/bivariate-statistics/', views.math_ai_sl_bivariate_statistics_videos, name='math-ai-sl-bivariate-statistics-videos'),
    path('past-papers-topics/math-ai-sl/descriptive-statistics/', views.math_ai_sl_descriptive_stats_videos, name='math-ai-sl-descriptive-statistics-videos'),
    path('past-papers-topics/math-ai-sl/differentiation/', views.math_ai_sl_differentiation_videos, name='math-ai-sl-differentiation-videos'),
    path('past-papers-topics/math-ai-sl/integration/', views.math_ai_sl_integration_videos, name='math-ai-sl-integration-videos'),

    # Math AA SL Questionbank
    path('ib-hub/math-aa-sl/', views.math_aa_sl, name='math-aa-sl'),
    path('api/math-aa-sl-questions/', views.Math_AA_SL_QuestionsListAPIView.as_view(), name='math-aa-sl-questions-list'),
    path('ib-hub/math-aa-sl/sequences-and-series/', views.seq_and_series_aa_sl, name='seq-and-series-aa-sl'),
    path('ib-hub/math-aa-sl/integration/', views.integration_aa_sl, name='integration-aa-sl'),
    path('ib-hub/math-aa-sl/kinematics/', views.kinematics_aa_sl, name='kinematics-aa-sl'),
    path('ib-hub/math-aa-sl/statistics/', views.statistics_aa_sl, name='statistics-aa-sl'),
    path('ib-hub/math-aa-sl/trigonometric-functions/', views.trig_functions_aa_sl, name='trig-functions-aa-sl'),
    path('ib-hub/math-aa-sl/properties-of-functions/', views.properties_of_functions_aa_sl, name='properties-of-functions-aa-sl'),
    path('ib-hub/math-aa-sl/quadratic-functions/', views.quadratic_functions_aa_sl, name='quadratic-functions-aa-sl'),
    path('ib-hub/math-aa-sl/rational-functions/', views.rational_functions_aa_sl, name='rational-functions-aa-sl'),
    path('ib-hub/math-aa-sl/probability/', views.probability_aa_sl, name='probability-aa-sl'),
    path('ib-hub/math-aa-sl/proofs/', views.proofs_aa_sl, name='proofs-aa-sl'),
    path('ib-hub/math-aa-sl/geometry/', views.geometry_aa_sl, name='geometry-aa-sl'),
    path('ib-hub/math-aa-sl/exponentials-and-logarithms/', views.exp_and_logs_aa_sl, name='exp-and-logs-aa-sl'),
    path('ib-hub/math-aa-sl/exponential-and-logarithmic-functions/', views.exp_and_logs_functions_aa_sl, name='exp-and-logs-functions-aa-sl'),
    path('ib-hub/math-aa-sl/function-transformations/', views.function_transformations_aa_sl, name='function-transformations-aa-sl'),
    path('ib-hub/math-aa-sl/differentiation/', views.differentiation_aa_sl, name='differentiation-aa-sl'),
    path('ib-hub/math-aa-sl/distributions/', views.distributions_aa_sl, name='distributions-aa-sl'),
    path('ib-hub/math-aa-sl/binomial-expansion/', views.binomial_expansion_aa_sl, name='binomial-expansion-aa-sl'),
    path('ib-hub/math-aa-sl/bivariate-statistics/', views.bivariate_stats_aa_sl, name='bivariate-stats-aa-sl'),

    # Math AA SL Past Papers
    path('past-papers/math-aa-sl/', views.math_aa_sl_past_papers, name='math-aa-sl-past-papers'),
    path('past-papers/math-aa-sl/may-2024-tz1-p1/', views.math_aa_sl_may24tz1p1, name='math-aa-sl-may24tz1p1'),
    path('past-papers/math-aa-sl/may-2024-tz1-p2/', views.math_aa_sl_may24tz1p2, name='math-aa-sl-may24tz1p2'),
    path('past-papers/math-aa-sl/may-2024-tz2-p1/', views.math_aa_sl_may24tz2p1, name='math-aa-sl-may24tz2p1'),
    path('past-papers/math-aa-sl/may-2024-tz2-p2/', views.math_aa_sl_may24tz2p2, name='math-aa-sl-may24tz2p2'),
    path('past-papers/math-aa-sl/may-2023-tz1-p1/', views.math_aa_sl_may23tz1p1, name='math-aa-sl-may23tz1p1'),
    path('past-papers/math-aa-sl/may-2023-tz1-p2/', views.math_aa_sl_may23tz1p2, name='math-aa-sl-may23tz1p2'),
    path('past-papers/math-aa-sl/may-2023-tz2-p1/', views.math_aa_sl_may23tz2p1, name='math-aa-sl-may23tz2p1'),
    path('past-papers/math-aa-sl/may-2023-tz2-p2/', views.math_aa_sl_may23tz2p2, name='math-aa-sl-may23tz2p2'),
    path('past-papers/math-aa-sl/nov-2023-tz1-p1/', views.math_aa_sl_nov23tz1p1, name='math-aa-sl-nov23tz1p1'),
    path('past-papers/math-aa-sl/nov-2023-tz1-p2/', views.math_aa_sl_nov23tz1p2, name='math-aa-sl-nov23tz1p2'),
    path('past-papers/math-aa-sl/may-2022-tz1-p1/', views.math_aa_sl_may22tz1p1, name='math-aa-sl-may22tz1p1'),
    path('past-papers/math-aa-sl/may-2022-tz1-p2/', views.math_aa_sl_may22tz1p2, name='math-aa-sl-may22tz1p2'),
    path('past-papers/math-aa-sl/nov-2022-tz0-p1/', views.math_aa_sl_nov22tz0p1, name='math-aa-sl-nov22tz0p1'),
    path('past-papers/math-aa-sl/nov-2022-tz0-p2/', views.math_aa_sl_nov22tz0p2, name='math-aa-sl-nov22tz0p2'),
    path('past-papers/math-aa-sl/may-2021-tz1-p1/', views.math_aa_sl_may21tz1p1, name='math-aa-sl-may21tz1p1'),
    path('past-papers/math-aa-sl/may-2021-tz1-p2/', views.math_aa_sl_may21tz1p2, name='math-aa-sl-may21tz1p2'),
    path('past-papers/math-aa-sl/nov-2021-tz0-p1/', views.math_aa_sl_nov21tz0p1, name='math-aa-sl-nov21tz0p1'),
    path('past-papers/math-aa-sl/nov-2021-tz0-p2/', views.math_aa_sl_nov21tz0p2, name='math-aa-sl-nov21tz0p2'),
    # Math AA SL Past Paper Topics
    path('past-papers-topics/math-aa-sl/', views.math_aa_sl_past_papers_topics, name='math-aa-sl-past-papers-topics'),
    path('past-papers-topics/math-aa-sl/sequences-and-series/', views.math_aa_sl_seq_series_videos, name='math-aa-sl-seq-series-videos'),
    path('past-papers-topics/math-aa-sl/exponents-and-logs/', views.math_aa_sl_exponents_and_logs_videos, name='math-aa-sl-exponents-and-logs-videos'),
    path('past-papers-topics/math-aa-sl/binomial-expansion/', views.math_aa_sl_binomial_expansion_videos, name='math-aa-sl-binomial-expansion-videos'),
    path('past-papers-topics/math-aa-sl/proofs/', views.math_aa_sl_proofs_videos, name='math-aa-sl-proofs-videos'),
    path('past-papers-topics/math-aa-sl/properties-of-functions/', views.math_aa_sl_properties_of_functions_videos, name='math-aa-sl-properties-of-functions-videos'),
    path('past-papers-topics/math-aa-sl/quadratic-functions/', views.math_aa_sl_quadratic_functions_videos, name='math-aa-sl-quadratic-functions-videos'),
    path('past-papers-topics/math-aa-sl/rational-functions/', views.math_aa_sl_rational_functions_videos, name='math-aa-sl-rational-functions-videos'),
    path('past-papers-topics/math-aa-sl/exponential-and-logarithmic-functions/', views.math_aa_sl_exp_and_logs_functions_videos, name='math-aa-sl-exp-and-logs-functions-videos'),
    path('past-papers-topics/math-aa-sl/function-transformations/', views.math_aa_sl_function_transformations_videos, name='math-aa-sl-function-transformations-videos'),
    path('past-papers-topics/math-aa-sl/geometry/', views.math_aa_sl_geometry_videos, name='math-aa-sl-geometry-videos'),
    path('past-papers-topics/math-aa-sl/trigonometric-functions/', views.math_aa_sl_trigonometric_functions_videos, name='math-aa-sl-trigonometric-functions-videos'),
    path('past-papers-topics/math-aa-sl/statistics/', views.math_aa_sl_statistics_videos, name='math-aa-sl-statistics-videos'),
    path('past-papers-topics/math-aa-sl/bivariate-statistics/', views.math_aa_sl_bivariate_statistics_videos, name='math-aa-sl-bivariate-statistics-videos'),
    path('past-papers-topics/math-aa-sl/probability/', views.math_aa_sl_probability_videos, name='math-aa-sl-probability-videos'),
    path('past-papers-topics/math-aa-sl/distributions/', views.math_aa_sl_distributions_videos, name='math-aa-sl-distributions-videos'),
    path('past-papers-topics/math-aa-sl/differential-calculus/', views.math_aa_sl_differential_calculus_videos, name='math-aa-sl-differential-calculus-videos'),
    path('past-papers-topics/math-aa-sl/integral-calculus/', views.math_aa_sl_integral_calculus_videos, name='math-aa-sl-integral-calculus-videos'),
    path('past-papers-topics/math-aa-sl/kinematics/', views.math_aa_sl_kinematics_videos, name='math-aa-sl-kinematics-videos'),




    # Math AI HL Questionbank
    path('api/math-ai-hl-questions/', views.Math_AI_HL_QuestionsListAPIView.as_view(), name='math-ai-hl-questions-list'),
    
    # Question Editor
    path('question-editor/', views.question_editor, name='question-editor'),
    path('question-maker/', views.question_maker, name='question-maker'),
    path('api/save-question/', views.save_question_api, name='save-question-api'),
    path('api/update-question/', views.UpdateQuestionAPIView.as_view(), name='update-question'),
    path('api/delete-question/', views.delete_question_api, name='delete-question-api'),
    path('ib-hub/math-ai-hl/', views.math_ai_hl, name='math-ai-hl'),
    path('ib-hub/math-ai-hl/number-skills/', views.number_skills_ai_hl, name='number-skills-ai-hl'),
    path('ib-hub/math-ai-hl/sequences-and-series/', views.seq_series_ai_hl, name='seq-series-ai-hl'),
    path('ib-hub/math-ai-hl/matrices/', views.matrices_ai_hl, name='matrices-ai-hl'),
    path('ib-hub/math-ai-hl/systems-of-linear-equations/', views.systems_lin_eq_ai_hl, name='systems-lin-eq-ai-hl'),
    path('ib-hub/math-ai-hl/complex-numbers/', views.complex_numbers_ai_hl, name='complex-numbers-ai-hl'),
    path('ib-hub/math-ai-hl/linear-equations-graphs/', views.linear_equations_graphs_ai_hl, name='linear-equations-graphs-ai-hl'),
    path('ib-hub/math-ai-hl/application-of-functions/', views.application_of_functions_ai_hl, name='application-of-functions-ai-hl'),
    path('ib-hub/math-ai-hl/properties-of-functions/', views.properties_of_functions_ai_hl, name='properties-of-functions-ai-hl'),
    path('ib-hub/math-ai-hl/function-transformations/', views.function_transformations_ai_hl, name='function-transformations-ai-hl'),
    path('ib-hub/math-ai-hl/trigonometry/', views.trigonometry_ai_hl, name='trigonometry-ai-hl'),
    path('ib-hub/math-ai-hl/trigonometric-functions/', views.trigonometric_functions_ai_hl, name='trigonometric-functions-ai-hl'),
    path('ib-hub/math-ai-hl/geometry-of-3d-shapes/', views.geometry_shapes_ai_hl, name='geometry-shapes-ai-hl'),
    path('ib-hub/math-ai-hl/voronoi-diagrams/', views.voronoi_diagrams_ai_hl, name='voronoi-diagrams-ai-hl'),
    path('ib-hub/math-ai-hl/geometric-transformations/', views.geometric_transformations_ai_hl, name='geometric-transformations-ai-hl'),
    path('ib-hub/math-ai-hl/vectors/', views.vectors_ai_hl, name='vectors-ai-hl'),
    path('ib-hub/math-ai-hl/graph-theory/', views.graph_theory_ai_hl, name='graph-theory-ai-hl'),
    path('ib-hub/math-ai-hl/descriptive-statistics/', views.descriptive_stats_ai_hl, name='descriptive-stats-ai-hl'),
    path('ib-hub/math-ai-hl/bivariate-statistics/', views.bivariate_statistics_ai_hl, name='bivariate-statistics-ai-hl'),
    path('ib-hub/math-ai-hl/probability/', views.probability_ai_hl, name='probability-ai-hl'),
    path('ib-hub/math-ai-hl/hypothesis-testing/', views.hypothesis_testing_ai_hl, name='hypothesis-testing-ai-hl'),
    path('ib-hub/math-ai-hl/confidence-intervals/', views.confidence_intervals_ai_hl, name='confidence-intervals-ai-hl'),
    path('ib-hub/math-ai-hl/distributions/', views.distributions_ai_hl, name='distributions-ai-hl'),
    path('ib-hub/math-ai-hl/differentiation/', views.differentiation_ai_hl, name='differentiation-ai-hl'),
    path('ib-hub/math-ai-hl/integration/', views.integration_ai_hl, name='integration-ai-hl'),
    path('ib-hub/math-ai-hl/kinematics/', views.kinematics_ai_hl, name='kinematics-ai-hl'),
    path('ib-hub/math-ai-hl/differential-equation/', views.differential_equation_ai_hl, name='differential-equation-ai-hl'),

    # Math AI HL Past Papers
    path('past-papers/math-ai-hl/', views.math_ai_hl_past_papers, name='math-ai-hl-past-papers'),
    path('past-papers/math-ai-hl/may-2024-tz1-p1/', views.math_ai_hl_may24tz1p1, name='math-ai-hl-may24tz1p1'),
    path('past-papers/math-ai-hl/may-2024-tz1-p2/', views.math_ai_hl_may24tz1p2, name='math-ai-hl-may24tz1p2'),
    path('past-papers/math-ai-hl/may-2023-tz1-p1/', views.math_ai_hl_may23tz1p1, name='math-ai-hl-may23tz1p1'),
    path('past-papers/math-ai-hl/may-2023-tz1-p2/', views.math_ai_hl_may23tz1p2, name='math-ai-hl-may23tz1p2'),
    path('past-papers/math-ai-hl/may-2023-tz2-p1/', views.math_ai_hl_may23tz2p1, name='math-ai-hl-may23tz2p1'),
    path('past-papers/math-ai-hl/may-2023-tz2-p2/', views.math_ai_hl_may23tz2p2, name='math-ai-hl-may23tz2p2'),
    path('past-papers/math-ai-hl/may-2022-tz1-p1/', views.math_ai_hl_may22tz1p1, name='math-ai-hl-may22tz1p1'),
    path('past-papers/math-ai-hl/may-2022-tz1-p2/', views.math_ai_hl_may22tz1p2, name='math-ai-hl-may22tz1p2'),
    path('past-papers/math-ai-hl/nov-2023-tz0-p1/', views.math_ai_hl_nov23tz0p1, name='math-ai-hl-nov23tz0p1'),
    path('past-papers/math-ai-hl/nov-2023-tz0-p2/', views.math_ai_hl_nov23tz0p2, name='math-ai-hl-nov23tz0p2'),
    path('past-papers/math-ai-hl/nov-2022-tz0-p1/', views.math_ai_hl_nov22tz0p1, name='math-ai-hl-nov22tz0p1'),
    path('past-papers/math-ai-hl/nov-2022-tz0-p2/', views.math_ai_hl_nov22tz0p2, name='math-ai-hl-nov22tz0p2'),
    path('past-papers/math-ai-hl/may-2021-tz1-p1/', views.math_ai_hl_may21tz1p1, name='math-ai-hl-may21tz1p1'),
    path('past-papers/math-ai-hl/may-2021-tz1-p2/', views.math_ai_hl_may21tz1p2, name='math-ai-hl-may21tz1p2'),
    path('webhook/', views.webhook, name='webhook'),
    path('cancel-subscription/', views.cancel_subscription, name='cancel-subscription'),
    # Math AI HL Past Papers Topics
    path('past-papers-topics/math-ai-hl/', views.math_ai_hl_past_papers_topics, name='math-ai-hl-past-papers-topics'),
    path('past-papers-topics/math-ai-hl/sequences-and-series/', views.math_ai_hl_seq_series_videos, name='math-ai-hl-seq-series-videos'),
    path('past-papers-topics/math-ai-hl/complex-numbers/', views.math_ai_hl_complex_numbers_videos, name='math-ai-hl-complex-numbers-videos'),
    path('past-papers-topics/math-ai-hl/matrices/', views.math_ai_hl_matrices_videos, name='math-ai-hl-matrices-videos'),
    path('past-papers-topics/math-ai-hl/systems-of-linear-equations/', views.math_ai_hl_systems_of_linear_equations_videos, name='math-ai-hl-systems-of-linear-equations-videos'),
    path('past-papers-topics/math-ai-hl/linear-equations-graphs/', views.math_ai_hl_linear_equations_graphs_videos, name='math-ai-hl-linear-equations-graphs-videos'),
    path('past-papers-topics/math-ai-hl/application-of-functions/', views.math_ai_hl_applications_of_functions_videos, name='math-ai-hl-application-of-functions-videos'),
    path('past-papers-topics/math-ai-hl/function-transformations/', views.math_ai_hl_function_transformations_videos, name='math-ai-hl-function-transformations-videos'),
    path('past-papers-topics/math-ai-hl/trigonometry/', views.math_ai_hl_trigonometry_videos, name='math-ai-hl-trigonometry-videos'),
    path('past-papers-topics/math-ai-hl/trigonometric-functions/', views.math_ai_hl_trigonometric_functions_videos, name='math-ai-hl-trigonometric-functions-videos'),
    path('past-papers-topics/math-ai-hl/geometric-transformations/', views.math_ai_hl_geometric_transformations_videos, name='math-ai-hl-geometric-transformations-videos'),
    path('past-papers-topics/math-ai-hl/vectors/', views.math_ai_hl_vectors_videos, name='math-ai-hl-vectors-videos'),
    path('past-papers-topics/math-ai-hl/graph-theory/', views.math_ai_hl_graph_theory_videos, name='math-ai-hl-graph-theory-videos'),
    path('past-papers-topics/math-ai-hl/descriptive-statistics/', views.math_ai_hl_descriptive_stats_videos, name='math-ai-hl-descriptive-stats-videos'),
    path('past-papers-topics/math-ai-hl/bivariate-statistics/', views.math_ai_hl_bivariate_statistics_videos, name='math-ai-hl-bivariate-statistics-videos'),
    path('past-papers-topics/math-ai-hl/probability/', views.math_ai_hl_probability_videos, name='math-ai-hl-probability-videos'),
    path('past-papers-topics/math-ai-hl/hypothesis-testing/', views.math_ai_hl_hypothesis_testing_videos, name='math-ai-hl-hypothesis-testing-videos'),
    path('past-papers-topics/math-ai-hl/confidence-intervals/', views.math_ai_hl_confidence_intervals_videos, name='math-ai-hl-confidence-intervals-videos'),
    path('past-papers-topics/math-ai-hl/distributions/', views.math_ai_hl_distributions_videos, name='math-ai-hl-distributions-videos'),
    path('past-papers-topics/math-ai-hl/differentiation/', views.math_ai_hl_differentiation_videos, name='math-ai-hl-differentiation-videos'),
    path('past-papers-topics/math-ai-hl/integration/', views.math_ai_hl_integration_videos, name='math-ai-hl-integration-videos'),
    path('past-papers-topics/math-ai-hl/kinematics/', views.math_ai_hl_kinematics_videos, name='math-ai-hl-kinematics-videos'),
    path('past-papers-topics/math-ai-hl/differential-equations/', views.math_ai_hl_differential_equation_videos, name='math-ai-hl-differential-equation-videos'),
    path('past-papers-topics/math-ai-hl/voronoi-diagrams/', views.math_ai_hl_voronoi_diagrams_videos, name='math-ai-hl-voronoi-diagrams-videos'),
    path('past-papers-topics/math-ai-hl/geometry-of-3d-shapes/', views.math_ai_hl_geometry_shapes_videos, name='math-ai-hl-geometry-shapes-videos'),

    
    # Math AA HL Questionbank
    path('api/math-aa-hl-questions/', views.Math_AA_HL_QuestionsListAPIView.as_view(), name='math-aa-hl-questions-list'),
    path('api/math-aa-hl-backup-questions/', views.Math_AA_HL_Backup_QuestionsListAPIView.as_view(), name='math-aa-hl-backup-questions-list'),
    path('ib-hub/math-aa-hl/', views.math_aa_hl, name='math-aa-hl'),
    path('ib-hub/math-aa-hl/sequences-and-series/', views.seq_and_series_aa_hl, name='seq-and-series-aa-hl'),
    path('ib-hub/math-aa-hl/proofs/', views.proofs_aa_hl, name='proofs-aa-hl'),
    path('ib-hub/math-aa-hl/exponentials-and-logarithms/', views.exp_and_logs_aa_hl, name='exp-and-logs-aa-hl'),
    path('ib-hub/math-aa-hl/binomial-expansion/', views.binomial_expansion_aa_hl, name='binomial-expansion-aa-hl'),
    path('ib-hub/math-aa-hl/properties-of-functions/', views.properties_of_functions_aa_hl, name='properties-of-functions-aa-hl'),
    path('ib-hub/math-aa-hl/quadratic-functions/', views.quadratic_functions_aa_hl, name='quadratic-functions-aa-hl'),
    path('ib-hub/math-aa-hl/counting-principles/', views.counting_principles_aa_hl, name='counting-principles-aa-hl'),
    path('ib-hub/math-aa-hl/complex-numbers/', views.complex_numbers_aa_hl, name='complex-numbers-aa-hl'),
    path('ib-hub/math-aa-hl/systems-of-equations/', views.systems_of_equations_aa_hl, name='systems-of-equations-aa-hl'),
    path('ib-hub/math-aa-hl/geometry/', views.geometry_aa_hl, name='geometry-aa-hl'),
    path('ib-hub/math-aa-hl/trigonometric-functions/', views.trig_functions_aa_hl, name='trig-functions-aa-hl'),
    path('ib-hub/math-aa-hl/vectors/', views.vectors_aa_hl, name='vectors-aa-hl'),
    path('ib-hub/math-aa-hl/rational-functions/', views.rational_functions_aa_hl, name='rational-functions-aa-hl'),
    path('ib-hub/math-aa-hl/function-transformations/', views.function_transformations_aa_hl, name='function-transformations-aa-hl'),
    path('ib-hub/math-aa-hl/polynomials/', views.polynomials_aa_hl, name='polynomials-aa-hl'),
    path('ib-hub/math-aa-hl/modulus-and-inequalities/', views.mod_inequalities_aa_hl, name='modulus-inequalities-aa-hl'),
    path('ib-hub/math-aa-hl/exponentials-and-logarithmic-functions/', views.exp_and_logs_functions_aa_hl, name='exp-and-logs-functions-aa-hl'),
    path('ib-hub/math-aa-hl/statistics/', views.statistics_aa_hl, name='statistics-aa-hl'),
    path('ib-hub/math-aa-hl/distributions/', views.distributions_aa_hl, name='distributions-aa-hl'),
    path('ib-hub/math-aa-hl/probability/', views.probability_aa_hl, name='probability-aa-hl'),
    path('ib-hub/math-aa-hl/bivariate-statistics/', views.bivariate_stats_aa_hl, name='bivariate-stats-aa-hl'),
    path('ib-hub/math-aa-hl/kinematics/', views.kinematics_aa_hl, name='kinematics-aa-hl'),
    path('ib-hub/math-aa-hl/differential-equations/', views.differential_equations_aa_hl, name='differential-equations-aa-hl'),
    path('ib-hub/math-aa-hl/differential-calculus/', views.differential_calculus_aa_hl, name='differential-calculus-aa-hl'),
    path('ib-hub/math-aa-hl/integral-calculus/', views.integral_calculus_aa_hl, name='integral-calculus-aa-hl'),
    path('ib-hub/math-aa-hl/maclaurin-series/', views.maclaurin_series_aa_hl, name='maclaurin-series-aa-hl'),

    # Math AA HL Past Papers
    path('past-papers/math-aa-hl/', views.math_aa_hl_past_papers, name='math-aa-hl-past-papers'),
    path('past-papers/math-aa-hl/may-2024-tz1-p1/', views.math_aa_hl_may24tz1p1, name='math-aa-hl-may24tz1p1'),
    path('past-papers/math-aa-hl/may-2024-tz1-p2/', views.math_aa_hl_may24tz1p2, name='math-aa-hl-may24tz1p2'),
    path('past-papers/math-aa-hl/may-2024-tz2-p1/', views.math_aa_hl_may24tz2p1, name='math-aa-hl-may24tz2p1'),
    path('past-papers/math-aa-hl/may-2024-tz2-p2/', views.math_aa_hl_may24tz2p2, name='math-aa-hl-may24tz2p2'),
    path('past-papers/math-aa-hl/may-2023-tz1-p1/', views.math_aa_hl_may23tz1p1, name='math-aa-hl-may23tz1p1'),
    path('past-papers/math-aa-hl/may-2023-tz1-p2/', views.math_aa_hl_may23tz1p2, name='math-aa-hl-may23tz1p2'),
    path('past-papers/math-aa-hl/nov-2023-tz1-p1/', views.math_aa_hl_nov23tz1p1, name='math-aa-hl-nov23tz1p1'),
    path('past-papers/math-aa-hl/nov-2023-tz1-p2/', views.math_aa_hl_nov23tz1p2, name='math-aa-hl-nov23tz1p2'),
    path('past-papers/math-aa-hl/may-2022-tz1-p1/', views.math_aa_hl_may22tz1p1, name='math-aa-hl-may22tz1p1'),
    path('past-papers/math-aa-hl/may-2022-tz1-p2/', views.math_aa_hl_may22tz1p2, name='math-aa-hl-may22tz1p2'),
    path('past-papers/math-aa-hl/nov-2022-tz1-p1/', views.math_aa_hl_nov22tz0p1, name='math-aa-hl-nov22tz1p1'),
    path('past-papers/math-aa-hl/nov-2022-tz1-p2/', views.math_aa_hl_nov22tz0p2, name='math-aa-hl-nov22tz1p2'),
    path('past-papers/math-aa-hl/may-2021-tz1-p1/', views.math_aa_hl_may21tz1p1, name='math-aa-hl-may21tz1p1'),
    path('past-papers/math-aa-hl/may-2021-tz1-p2/', views.math_aa_hl_may21tz1p2, name='math-aa-hl-may21tz1p2'),
    path('past-papers/math-aa-hl/nov-2021-tz0-p1/', views.math_aa_hl_nov21tz0p1, name='math-aa-hl-nov21tz0p1'),
    path('past-papers/math-aa-hl/nov-2021-tz0-p2/', views.math_aa_hl_nov21tz0p2, name='math-aa-hl-nov21tz0p2'),
    # Math AA HL Past Papers Topics
    path('past-papers-topics/math-aa-hl/', views.math_aa_hl_past_papers_topics, name='math-aa-hl-past-papers-topics'),
    path('past-papers-topics/math-aa-hl/sequences-and-series/', views.math_aa_hl_seq_series_videos, name='math-aa-hl-seq-series-videos'),
    path('past-papers-topics/math-aa-hl/proofs/', views.math_aa_hl_proofs_videos, name='math-aa-hl-proofs-videos'),
    path('past-papers-topics/math-aa-hl/exponentials-and-logarithms/', views.math_aa_hl_exp_and_logs_videos, name='math-aa-hl-exp-and-logs-videos'),
    path('past-papers-topics/math-aa-hl/binomial-expansion/', views.math_aa_hl_binomial_expansion_videos, name='math-aa-hl-binomial-expansion-videos'),
    path('past-papers-topics/math-aa-hl/properties-of-functions/', views.math_aa_hl_properties_of_functions_videos, name='math-aa-hl-properties-of-functions-videos'),
    path('past-papers-topics/math-aa-hl/quadratic-functions/', views.math_aa_hl_quadratic_functions_videos, name='math-aa-hl-quadratic-functions-videos'),
    path('past-papers-topics/math-aa-hl/counting-principles/', views.math_aa_hl_counting_principles_videos, name='math-aa-hl-counting-principles-videos'),
    path('past-papers-topics/math-aa-hl/complex-numbers/', views.math_aa_hl_complex_numbers_videos, name='math-aa-hl-complex-numbers-videos'),
    path('past-papers-topics/math-aa-hl/systems-of-equations/', views.math_aa_hl_systems_of_equations_videos, name='math-aa-hl-systems-of-equations-videos'),
    path('past-papers-topics/math-aa-hl/geometry/', views.math_aa_hl_geometry_videos, name='math-aa-hl-geometry-videos'),
    path('past-papers-topics/math-aa-hl/trigonometric-functions/', views.math_aa_hl_trig_functions_videos, name='math-aa-hl-trig-functions-videos'),
    path('past-papers-topics/math-aa-hl/vectors/', views.math_aa_hl_vectors_videos, name='math-aa-hl-vectors-videos'),
    path('past-papers-topics/math-aa-hl/rational-functions/', views.math_aa_hl_rational_functions_videos, name='math-aa-hl-rational-functions-videos'),
    path('past-papers-topics/math-aa-hl/function-transformations/', views.math_aa_hl_function_transformations_videos, name='math-aa-hl-function-transformations-videos'),
    path('past-papers-topics/math-aa-hl/polynomials/', views.math_aa_hl_polynomials_videos, name='math-aa-hl-polynomials-videos'),
    path('past-papers-topics/math-aa-hl/modulus-and-inequalities/', views.math_aa_hl_mod_inequalities_videos, name='math-aa-hl-modulus-inequalities-videos'),
    path('past-papers-topics/math-aa-hl/exponentials-and-logarithmic-functions/', views.math_aa_hl_exp_and_logs_functions_videos, name='math-aa-hl-exp-and-logs-functions-videos'),
    path('past-papers-topics/math-aa-hl/statistics/', views.math_aa_hl_statistics_videos, name='math-aa-hl-statistics-videos'),
    path('past-papers-topics/math-aa-hl/distributions/', views.math_aa_hl_distributions_videos, name='math-aa-hl-distributions-videos'),
    path('past-papers-topics/math-aa-hl/probability/', views.math_aa_hl_probability_videos, name='math-aa-hl-probability-videos'),
    path('past-papers-topics/math-aa-hl/bivariate-statistics/', views.math_aa_hl_bivariate_stats_videos, name='math-aa-hl-bivariate-stats-videos'),
    path('past-papers-topics/math-aa-hl/kinematics/', views.math_aa_hl_kinematics_videos, name='math-aa-hl-kinematics-videos'),
    path('past-papers-topics/math-aa-hl/differential-equations/', views.math_aa_hl_differential_equations_videos, name='math-aa-hl-differential-equations-videos'),
    path('past-papers-topics/math-aa-hl/differential-calculus/', views.math_aa_hl_differential_calculus_videos, name='math-aa-hl-differential-calculus-videos'),
    path('past-papers-topics/math-aa-hl/integral-calculus/', views.math_aa_hl_integral_calculus_videos, name='math-aa-hl-integral-calculus-videos'),
    path('past-papers-topics/math-aa-hl/maclaurin-series/', views.math_aa_hl_maclaurin_series_videos, name='math-aa-hl-maclaurin-series-videos'),


    # Biology SL Questionbank
    path('api/biology-sl-questions/', views.BiologySLQuestionsListAPIView.as_view(), name='biology-sl-questions-list'),
    path('ib-hub/biology-sl/', views.biology_sl, name='biology-sl'),
    path('ib-hub/biology-sl/water/', views.water_sl, name='water-sl'),
    path('ib-hub/biology-sl/water-chatgpt/', views.water_sl_chatgpt, name='water-sl-chatgpt'),
    path('ib-hub/biology-sl/nucleic-acids/', views.nucleic_acids_sl, name='nucleic-acids-sl'),
    path('ib-hub/biology-sl/cell-structure/', views.cell_structure_sl, name='cell-structure-sl'),
    path('ib-hub/biology-sl/diversity-of-organisms/', views.diversity_of_organisms_sl, name='diversity-of-organisms-sl'),
    path('ib-hub/biology-sl/evolution-and-speciation/', views.evolution_and_speciation_sl, name='evolution-and-speciation-sl'),
    path('ib-hub/biology-sl/conservation-of-biodiversity/', views.conservation_of_biodiversity_sl, name='conservation-of-biodiversity-sl'),
    path('ib-hub/biology-sl/carbohydrates-and-lipids/', views.carbohydrates_and_lipids_sl, name='carbohydrates-and-lipids-sl'),
    path('ib-hub/biology-sl/proteins/', views.proteins_sl, name='proteins-sl'),
    path('ib-hub/biology-sl/membranes-and-membrane-transport/', views.membranes_transport_sl, name='membranes-transport-sl'),
    path('ib-hub/biology-sl/organelles-and-compartmentalization/', views.organelles_comperatment_sl, name='organelles-compartment-sl'),
    path('ib-hub/biology-sl/cell-specialization/', views.cell_specialization_sl, name='cell-specialization-sl'),
    path('ib-hub/biology-sl/gas-exchange/', views.gas_exchange_sl, name='gas-exchange-sl'),
    path('ib-hub/biology-sl/transport/', views.transport_sl, name='transport-sl'),
    path('ib-hub/biology-sl/adaptation-to-environment/', views.adaptation_to_environment_sl, name='adaptation-to-environment-sl'),
    path('ib-hub/biology-sl/ecological-niche/', views.ecological_niches_sl, name='ecological-niches-sl'),
    path('ib-hub/biology-sl/enzymes-and-metabolism/', views.enzymes_metabolism_sl, name='enzymes-metabolism-sl'),
    path('ib-hub/biology-sl/cell-respiration/', views.cell_respiration_sl, name='cell-respiration-sl'),
    path('ib-hub/biology-sl/photosynthesis/', views.photosynthesis_sl, name='photosynthesis-sl'),
    path('ib-hub/biology-sl/neural-signaling/', views.neural_signaling_sl, name='neural-signaling-sl'),
    path('ib-hub/biology-sl/integration-of-body-systems/', views.integration_body_systems_sl, name='integration-of-body-systems-sl'),
    path('ib-hub/biology-sl/defence-against-disease/', views.defence_against_disease_sl, name='defence-against-disease-sl'),
    path('ib-hub/biology-sl/population-and-communities/', views.population_and_communities_sl, name='population-communities-sl'),
    path('ib-hub/biology-sl/transfer-of-energy-and-matter/', views.transfer_of_energy_sl, name='transfer-energy-matter-sl'),
    path('ib-hub/biology-sl/dna-replication/', views.dna_replication_sl, name='dna-replication-sl'),
    path('ib-hub/biology-sl/protein-synthesis/', views.protein_synthesis_sl, name='protein-synthesis-sl'),
    path('ib-hub/biology-sl/mutations-editing/', views.mutations_editing_sl, name='mutations-editing-sl'),
    path('ib-hub/biology-sl/natural-selection/', views.natural_selection_sl, name='natural-selection-sl'),
    path('ib-hub/biology-sl/inheritance/', views.inheritance_sl, name='inheritance-sl'),
    path('ib-hub/biology-sl/climate-change/', views.climate_change_sl, name='climate-change-sl'),
    path('ib-hub/biology-sl/water-potential/', views.water_potential_sl, name='water-potential-sl'),
    path('ib-hub/biology-sl/cell-division/', views.cell_division_sl, name='cell-division-sl'),
    path('ib-hub/biology-sl/reproduction/', views.reproduction_sl, name='reproduction-sl'),
    path('ib-hub/biology-sl/stability-change/', views.stability_change_sl, name='stability-change-sl'),
    path('ib-hub/biology-sl/homeostasis/', views.homeostasis_sl, name='homeostasis-sl'),
    


    # Biology HL Questionbank
    path('api/biology-hl-questions/', views.BiologyHLQuestionsListAPIView.as_view(), name='biology-hl-questions-list'),
    path('ib-hub/biology-hl/', views.biology_hl, name='biology-hl'),
    path('ib-hub/biology-hl/water/', views.water_hl, name='water-hl'),
    path('ib-hub/biology-hl/nucleic-acids/', views.nucleic_acids_hl, name='nucleic-acids-hl'),
    path('ib-hub/biology-hl/cell-structure/', views.cell_structure_hl, name='cell-structure-hl'),
    path('ib-hub/biology-hl/diversity-of-organisms/', views.diversity_of_organisms_hl, name='diversity-of-organisms-hl'),
    path('ib-hub/biology-hl/evolution-and-speciation/', views.evolution_and_speciation_hl, name='evolution-and-speciation-hl'),
    path('ib-hub/biology-hl/conservation-of-biodiversity/', views.conservation_of_biodiversity_hl, name='conservation-of-biodiversity-hl'),
    path('ib-hub/biology-hl/carbohydrates-and-lipids/', views.carbohydrates_and_lipids_hl, name='carbohydrates-and-lipids-hl'),
    path('ib-hub/biology-hl/proteins/', views.proteins_hl, name='proteins-hl'),
    path('ib-hub/biology-hl/membranes-and-membrane-transport/', views.membranes_transport_hl, name='membranes-transport-hl'),
    path('ib-hub/biology-hl/organelles-and-compartmentalization/', views.organelles_comperatment_hl, name='organelles-compartment-hl'),
    path('ib-hub/biology-hl/cell-specialization/', views.cell_specialization_hl, name='cell-specialization-hl'),
    path('ib-hub/biology-hl/gas-exchange/', views.gas_exchange_hl, name='gas-exchange-hl'),
    path('ib-hub/biology-hl/transport/', views.transport_hl, name='transport-hl'),
    path('ib-hub/biology-hl/adaptation-to-environment/', views.adaptation_to_environment_hl, name='adaptation-to-environment-hl'),
    path('ib-hub/biology-hl/ecological-niche/', views.ecological_niches_hl, name='ecological-niches-hl'),
    path('ib-hub/biology-hl/enzymes-and-metabolism/', views.enzymes_metabolism_hl, name='enzymes-metabolism-hl'),
    path('ib-hub/biology-hl/cell-respiration/', views.cell_respiration_hl, name='cell-respiration-hl'),
    path('ib-hub/biology-hl/photosynthesis/', views.photosynthesis_hl, name='photosynthesis-hl'),
    path('ib-hub/biology-hl/neural-signaling/', views.neural_signaling_hl, name='neural-signaling-hl'),
    path('ib-hub/biology-hl/integration-of-body-systems/', views.integration_body_systems_hl, name='integration-of-body-systems-hl'),
    path('ib-hub/biology-hl/defence-against-disease/', views.defence_against_disease_hl, name='defence-against-disease-hl'),
    path('ib-hub/biology-hl/population-and-communities/', views.population_and_communities_hl, name='population-communities-hl'),
    path('ib-hub/biology-hl/transfer-of-energy-and-matter/', views.transfer_of_energy_hl, name='transfer-energy-matter-hl'),
    path('ib-hub/biology-hl/origin-of-cells/', views.origin_of_cells_hl, name='origin-of-cells-hl'),
    path('ib-hub/biology-hl/viruses/', views.viruses_hl, name='viruses-hl'),
    path('ib-hub/biology-hl/classification/', views.classification_hl, name='classification-hl'),
    path('ib-hub/biology-hl/muscle-and-motility/', views.muscle_and_motility_hl, name='muscle-and-motility-hl'),
    path('ib-hub/biology-hl/chemical-signaling/', views.chemical_signaling_hl, name='chemical-signaling-hl'),
    path('ib-hub/biology-hl/dna-replication/', views.dna_replication_hl, name='dna-replication-hl'),
    path('ib-hub/biology-hl/protein-synthesis/', views.protein_synthesis_hl, name='protein-synthesis-hl'),
    path('ib-hub/biology-hl/mutations-editing/', views.mutations_editing_hl, name='mutations-editing-hl'),
    path('ib-hub/biology-hl/natural-selection/', views.natural_selection_hl, name='natural-selection-hl'),
    path('ib-hub/biology-hl/inheritance/', views.inheritance_hl, name='inheritance-hl'),
    path('ib-hub/biology-hl/climate-change/', views.climate_change_hl, name='climate-change-hl'),
    path('ib-hub/biology-hl/water-potential/', views.water_potential_hl, name='water-potential-hl'),
    path('ib-hub/biology-hl/cell-division/', views.cell_division_hl, name='cell-division-hl'),
    path('ib-hub/biology-hl/reproduction/', views.reproduction_hl, name='reproduction-hl'),
    path('ib-hub/biology-hl/stability-change/', views.stability_change_hl, name='stability-change-hl'),
    path('ib-hub/biology-hl/homeostasis/', views.homeostasis_hl, name='homeostasis-hl'),
    path('ib-hub/biology-hl/gene-expression/', views.gene_expression_hl, name='gene-expression-hl'),


    # History SL Questionbank
    path('api/history-sl-questions/', views.HistorySLQuestionsListAPIView.as_view(), name='history-sl-questions-list'),
    path('ib-hub/history-sl/', views.history_sl, name='history-sl'),
    path('ib-hub/history-sl/emergence-democratic-states/', views.emergence_democratic_states_sl, name='emergence-democratic-states-sl'),
    path('ib-hub/history-sl/authoritarian-states/', views.authoritarian_states_sl, name='authoritarian-states-sl'),
    path('ib-hub/history-sl/causes-effects-wars/', views.causes_effects_wars_sl, name='causes-effects-wars-sl'),
    path('ib-hub/history-sl/cold-war/', views.cold_war_sl, name='cold-war-sl'),
    path('ib-hub/history-sl/rights-protest/', views.rights_protest_sl, name='rights-protest-sl'),
    path('ib-hub/history-sl/move-global-war/', views.move_global_war_sl, name='move-global-war-sl'),
    path('ib-hub/history-sl/conflict-intervention/', views.conflict_intervention_sl, name='conflict-intervention-sl'),
    path('ib-hub/history-sl/independence-movements/', views.independence_movements_sl, name='independence-movements-sl'),

    # History HL Questionbank
    path('ib-hub/history-hl/', views.history_hl, name='history-hl'),
    
    # History Question Editor
    path('edit-history-questions/', views.edit_history_questions, name='edit-history-questions'),
    path('api/history-question/<int:question_id>/', views.get_history_question, name='get-history-question'),
    path('api/history-question/<int:question_id>/update/', views.update_history_question, name='update-history-question'),


    # Physics SL Questionbank
    path('ib-hub/physics-sl/', views.physics_sl, name='physics-sl'),
    path('api/physics-sl-questions/', views.PhysicsSLQuestionsListAPIView.as_view(), name='physics-sl-questions-list'),
    path('ib-hub/physics-sl/kinematics', views.kinematics_sl, name='kinematics-sl'),
    path('ib-hub/physics-sl/forces-and-momentum', views.forces_momentum_sl, name='forces-momentum-sl'),
    path('ib-hub/physics-sl/work-energy-power', views.work_energy_power_sl, name='work-energy-power-sl'),
    path('ib-hub/physics-sl/thermal-energy-transfer', views.thermal_energy_sl, name='thermal-energy-sl'),
    path('ib-hub/physics-sl/greenhouse-effect', views.greenhouse_effect_sl, name='greenhouse-effect-sl'),
    path('ib-hub/physics-sl/ideal-gas-model', views.ideal_gas_model_sl, name='ideal-gas-model-sl'),
    path('ib-hub/physics-sl/electric-circuits', views.electric_circuits_sl, name='electric-circuits-sl'),
    path('ib-hub/physics-sl/wave-phenomena', views.wave_phenomena_sl, name='wave-phenomena-sl'),
    path('ib-hub/physics-sl/simple-harmonic-motion', views.simple_harmonic_motion_sl, name='simple-harmonic-motion-sl'),
    path('ib-hub/physics-sl/wave-model', views.wave_model_sl, name='wave-model-sl'),
    path('ib-hub/physics-sl/standing-waves', views.standing_waves_sl, name='standing-waves-sl'),
    path('ib-hub/physics-sl/doppler-effect', views.doppler_effect_sl, name='doppler-effect-sl'),
    path('ib-hub/physics-sl/gravitational-fields', views.gravitational_fields_sl, name='gravitational-fields-sl'),
    path('ib-hub/physics-sl/electric-magnetic-fields', views.electric_magnetic_fields_sl, name='electric-magnetic-fields-sl'),
    path('ib-hub/physics-sl/motion-in-fields', views.motion_in_fields_sl, name='motion-in-fields-sl'),
    path('ib-hub/physics-sl/structure-of-the-atom', views.structure_atom_sl, name='structure-atom-sl'),
    path('ib-hub/physics-sl/radioactive-decay', views.radioactive_decay_sl, name='radioactive-decay-sl'),
    path('ib-hub/physics-sl/fission', views.fission_sl, name='fission-sl'),
    path('ib-hub/physics-sl/fusion-and-stars', views.fusion_and_stars_sl, name='fusion-and-stars-sl'),

    # Physics SL Past Papers
    path('past-papers/physics-sl/', views.physics_sl_past_papers, name='physics-sl-past-papers'),
    path('past-papers/physics-sl/may-2021-tz1-p1/', views.physics_sl_may21tz1p1, name='physics-sl-may21tz1p1'),
    path('past-papers/physics-sl/may-2021-tz1-p2/', views.physics_sl_may21tz1p2, name='physics-sl-may21tz1p2'),
    path('past-papers/physics-sl/may-2022-tz1-p1/', views.physics_sl_may22tz1p1, name='physics-sl-may22tz1p1'),
    path('past-papers/physics-sl/may-2022-tz1-p2/', views.physics_sl_may22tz1p2, name='physics-sl-may22tz1p2'),
    path('past-papers/physics-sl/may-2023-tz1-p1/', views.physics_sl_may23tz1p1, name='physics-sl-may23tz1p1'),
    path('past-papers/physics-sl/may-2023-tz1-p2/', views.physics_sl_may23tz1p2, name='physics-sl-may23tz1p2'),
    path('past-papers/physics-sl/may-2024-tz1-p1/', views.physics_sl_may24tz1p1, name='physics-sl-may24tz1p1'),
    path('past-papers/physics-sl/may-2024-tz1-p2/', views.physics_sl_may24tz1p2, name='physics-sl-may24tz1p2'),
    path('past-papers/physics-sl/nov-2020-tz0-p1/', views.physics_sl_nov20tz0p1, name='physics-sl-nov20tz0p1'),
    path('past-papers/physics-sl/nov-2020-tz0-p2/', views.physics_sl_nov20tz0p2, name='physics-sl-nov20tz0p2'),
    path('past-papers/physics-sl/specimen-2025-p1a/', views.physics_sl_specimen2025_p1, name='physics-sl-specimen2025-p1'),
    path('past-papers/physics-sl/specimen-2025-p1b/', views.physics_sl_specimen2025_p1b, name='physics-sl-specimen2025-p1b'),
    path('past-papers/physics-sl/specimen-2025-p2/', views.physics_sl_specimen2025_p2, name='physics-sl-specimen2025-p2'),
    path('past-papers/physics-sl/may-2025-tz1-p1a/', views.physics_sl_may25tz1p1a, name='physics-sl-may25tz1p1a'),
    path('past-papers/physics-sl/may-2025-tz2-p1a/', views.physics_sl_may25tz2p1a, name='physics-sl-may25tz2p1a'),
    path('past-papers/physics-sl/may-2025-tz3-p1a/', views.physics_sl_may25tz3p1a, name='physics-sl-may25tz3p1a'),
    path('past-papers/physics-sl/may-2025-tz1-p1b/', views.physics_sl_may25tz1p1b, name='physics-sl-may25tz1p1b'),
    path('past-papers/physics-sl/may-2025-tz2-p1b/', views.physics_sl_may25tz2p1b, name='physics-sl-may25tz2p1b'),
    path('past-papers/physics-sl/may-2025-tz3-p1b/', views.physics_sl_may25tz3p1b, name='physics-sl-may25tz3p1b'),
    path('past-papers/physics-sl/may-2025-tz1-p2/', views.physics_sl_may25tz1p2, name='physics-sl-may25tz1p2'),
    path('past-papers/physics-sl/may-2025-tz2-p2/', views.physics_sl_may25tz2p2, name='physics-sl-may25tz2p2'),
    path('past-papers/physics-sl/may-2025-tz3-p2/', views.physics_sl_may25tz3p2, name='physics-sl-may25tz3p2'),

    # Physics SL Past Papers Topics
    path('past-papers-topics/physics-sl/', views.physics_sl_past_papers_topics, name='physics-sl-past-papers-topics'),
    path('past-papers-topics/physics-sl/kinematics/', views.physics_sl_kinematics_videos, name='physics-sl-kinematics-videos'),
    path('past-papers-topics/physics-sl/forces-and-momentum/', views.physics_sl_forces_momentum_videos, name='physics-sl-forces-momentum-videos'),
    path('past-papers-topics/physics-sl/work-energy-power/', views.physics_sl_work_energy_power_videos, name='physics-sl-work-energy-power-videos'),
    path('past-papers-topics/physics-sl/forces-and-momentum/', views.physics_sl_forces_momentum_videos, name='physics-sl-forces-momentum-videos'),
    path('past-papers-topics/physics-sl/thermal-energy-transfer/', views.physics_sl_thermal_energy_transfer_videos, name='physics-sl-thermal-energy-transfer-videos'),
    path('past-papers-topics/physics-sl/greenhouse-effect/', views.physics_sl_greenhouse_effect_videos, name='physics-sl-greenhouse-effect-videos'),
    path('past-papers-topics/physics-sl/ideal-gas-model/', views.physics_sl_ideal_gas_model_videos, name='physics-sl-ideal-gas-model-videos'),
    path('past-papers-topics/physics-sl/electric-circuits/', views.physics_sl_electric_circuits_videos, name='physics-sl-electric-circuits-videos'),
    path('past-papers-topics/physics-sl/wave-phenomena/', views.physics_sl_wave_phenomena_videos, name='physics-sl-wave-phenomena-videos'),
    path('past-papers-topics/physics-sl/simple-harmonic-motion/', views.physics_sl_simple_harmonic_motion_videos, name='physics-sl-simple-harmonic-motion-videos'),
    path('past-papers-topics/physics-sl/wave-model/', views.physics_sl_wave_model_videos, name='physics-sl-wave-model-videos'),
    path('past-papers-topics/physics-sl/standing-waves/', views.physics_sl_standing_waves_videos, name='physics-sl-standing-waves-videos'),
    path('past-papers-topics/physics-sl/doppler-effect/', views.physics_sl_doppler_effect_videos, name='physics-sl-doppler-effect-videos'),
    path('past-papers-topics/physics-sl/gravitational-fields/', views.physics_sl_gravitational_fields_videos, name='physics-sl-gravitational-fields-videos'),
    path('past-papers-topics/physics-sl/electric-magnetic-fields/', views.physics_sl_electric_magnetic_fields_videos, name='physics-sl-electric-magnetic-fields-videos'),
    path('past-papers-topics/physics-sl/motion-in-fields/', views.physics_sl_motion_in_fields_videos, name='physics-sl-motion-in-fields-videos'),
    path('past-papers-topics/physics-sl/structure-of-the-atom/', views.physics_sl_structure_of_the_atom_videos, name='physics-sl-structure-of-the-atom-videos'),
    path('past-papers-topics/physics-sl/radioactive-decay/', views.physics_sl_radioactive_decay_videos, name='physics-sl-radioactive-decay-videos'),
    path('past-papers-topics/physics-sl/fission/', views.physics_sl_fission_videos, name='physics-sl-fission-videos'),
    path('past-papers-topics/physics-sl/fusion-and-stars/', views.physics_sl_fusion_and_stars_videos, name='physics-sl-fusion-and-stars-videos'),


    # Physics HL Questionbank
    path('ib-hub/physics-hl/', views.physics_hl, name='physics-hl'),
    path('api/physics-hl-questions/', views.PhysicsHLQuestionsListAPIView.as_view(), name='physics-hl-questions-list'),
    path('ib-hub/physics-hl/kinematics', views.kinematics_hl, name='kinematics-hl'),
    path('ib-hub/physics-hl/forces-and-momentum', views.forces_momentum_hl, name='forces-momentum-hl'),
    path('ib-hub/physics-hl/work-energy-power', views.work_energy_power_hl, name='work-energy-power-hl'),
    path('ib-hub/physics-hl/rigid-body-mechanics', views.rigid_body_mechanics_hl, name='rigid-body-mechanics-hl'),
    path('ib-hub/physics-hl/galilean-and-special-relativity', views.galilean_and_special_relativity_hl, name='galilean-and-special-relativity-hl'),
    path('ib-hub/physics-hl/thermal-energy-transfer', views.thermal_energy_hl, name='thermal-energy-hl'),
    path('ib-hub/physics-hl/galilean-and-special-relativity', views.galilean_and_special_relativity_hl, name='galilean-special-relativity-hl'),
    path('ib-hub/physics-hl/thermodynamics', views.thermodynamics_hl, name='thermodynamics-hl'),
    path('ib-hub/physics-hl/greenhouse-effect', views.greenhouse_effect_hl, name='greenhouse-effect-hl'),
    path('ib-hub/physics-hl/ideal-gas-model', views.ideal_gas_model_hl, name='ideal-gas-model-hl'),
    path('ib-hub/physics-hl/electric-circuits', views.electric_circuits_hl, name='electric-circuits-hl'),
    path('ib-hub/physics-hl/wave-phenomena', views.wave_phenomena_hl, name='wave-phenomena-hl'),
    path('ib-hub/physics-hl/simple-harmonic-motion', views.simple_harmonic_motion_hl, name='simple-harmonic-motion-hl'),
    path('ib-hub/physics-hl/wave-model', views.wave_model_hl, name='wave-model-hl'),
    path('ib-hub/physics-hl/standing-waves', views.standing_waves_hl, name='standing-waves-hl'),
    path('ib-hub/physics-hl/doppler-effect', views.doppler_effect_hl, name='doppler-effect-hl'),
    path('ib-hub/physics-hl/gravitational-fields', views.gravitational_fields_hl, name='gravitational-fields-hl'),
    path('ib-hub/physics-hl/electric-magnetic-fields', views.electric_magnetic_fields_hl, name='electric-magnetic-fields-hl'),
    path('ib-hub/physics-hl/motion-in-fields', views.motion_in_fields_hl, name='motion-in-fields-hl'),
    path('ib-hub/physics-hl/structure-of-the-atom', views.structure_atom_hl, name='structure-atom-hl'),
    path('ib-hub/physics-hl/radioactive-decay', views.radioactive_decay_hl, name='radioactive-decay-hl'),
    path('ib-hub/physics-hl/fission', views.fission_hl, name='fission-hl2'),
    path('ib-hub/physics-hl/fusion-and-stars', views.fusion_and_stars_hl, name='fusion-and-stars-hl'),
    path('ib-hub/physics-hl/induction', views.induction_hl, name='induction-hl'),
    path('ib-hub/physics-hl/quantum-physics', views.quantum_physics_hl, name='quantum-physics-hl'),

    # Physics HL Past Papers Topics
    path('past-papers-topics/physics-hl/', views.physics_hl_past_papers_topics, name='physics-hl-past-papers-topics'),
    path('past-papers-topics/physics-hl/kinematics/', views.physics_hl_kinematics_videos, name='physics-hl-kinematics-videos'),
    path('past-papers-topics/physics-hl/forces-and-momentum/', views.physics_hl_forces_momentum_videos, name='physics-hl-forces-momentum-videos'),
    path('past-papers-topics/physics-hl/work-energy-power/', views.physics_hl_work_energy_power_videos, name='physics-hl-work-energy-power-videos'),
    path('past-papers-topics/physics-hl/rigid-body-mechanics/', views.physics_hl_rigid_body_mechanics_videos, name='physics-hl-rigid-body-mechanics-videos'),
    path('past-papers-topics/physics-hl/galilean-and-special-relativity/', views.physics_hl_galilean_and_special_relativity_videos, name='physics-hl-galilean-and-special-relativity-videos'),
    path('past-papers-topics/physics-hl/thermal-energy-transfer/', views.physics_hl_thermal_energy_transfer_videos, name='physics-hl-thermal-energy-transfer-videos'),
    path('past-papers-topics/physics-hl/greenhouse-effect/', views.physics_hl_greenhouse_effect_videos, name='physics-hl-greenhouse-effect-videos'),
    path('past-papers-topics/physics-hl/ideal-gas-model/', views.physics_hl_ideal_gas_model_videos, name='physics-hl-ideal-gas-model-videos'),
    path('past-papers-topics/physics-hl/thermodynamics/', views.physics_hl_thermodynamics_videos, name='physics-hl-thermodynamics-videos'),
    path('past-papers-topics/physics-hl/electric-circuits/', views.physics_hl_electric_circuits_videos, name='physics-hl-electric-circuits-videos'),
    path('past-papers-topics/physics-hl/wave-phenomena/', views.physics_hl_wave_phenomena_videos, name='physics-hl-wave-phenomena-videos'),
    path('past-papers-topics/physics-hl/simple-harmonic-motion/', views.physics_hl_simple_harmonic_motion_videos, name='physics-hl-simple-harmonic-motion-videos'),
    path('past-papers-topics/physics-hl/wave-model/', views.physics_hl_wave_model_videos, name='physics-hl-wave-model-videos'),
    path('past-papers-topics/physics-hl/standing-waves/', views.physics_hl_standing_waves_videos, name='physics-hl-standing-waves-videos'),
    path('past-papers-topics/physics-hl/doppler-effect/', views.physics_hl_doppler_effect_videos, name='physics-hl-doppler-effect-videos'),
    path('past-papers-topics/physics-hl/gravitational-fields/', views.physics_hl_gravitational_fields_videos, name='physics-hl-gravitational-fields-videos'),
    path('past-papers-topics/physics-hl/electric-magnetic-fields/', views.physics_hl_electric_magnetic_fields_videos, name='physics-hl-electric-magnetic-fields-videos'),
    path('past-papers-topics/physics-hl/motion-in-fields/', views.physics_hl_motion_in_fields_videos, name='physics-hl-motion-in-fields-videos'),
    path('past-papers-topics/physics-hl/structure-of-the-atom/', views.physics_hl_structure_of_the_atom_videos, name='physics-hl-structure-of-the-atom-videos'),
    path('past-papers-topics/physics-hl/radioactive-decay/', views.physics_hl_radioactive_decay_videos, name='physics-hl-radioactive-decay-videos'),
    path('past-papers-topics/physics-hl/fission/', views.physics_hl_fission_videos, name='physics-hl-fission-videos'),
    path('past-papers-topics/physics-hl/fusion-and-stars/', views.physics_hl_fusion_and_stars_videos, name='physics-hl-fusion-and-stars-videos'),
    path('past-papers-topics/physics-hl/induction/', views.physics_hl_induction_videos, name='physics-hl-induction-videos'),
    path('past-papers-topics/physics-hl/quantum-physics/', views.physics_hl_quantum_physics_videos, name='physics-hl-quantum-physics-videos'),

    # Physics HL Past Papers
    path('past-papers/physics-hl/', views.physics_hl_past_papers, name='physics-hl-past-papers'),
    path('past-papers/physics-hl/may-2021-tz1-p1/', views.physics_hl_may21tz1p1, name='physics-hl-may21tz1p1'),
    path('past-papers/physics-hl/may-2021-tz1-p2/', views.physics_hl_may21tz1p2, name='physics-hl-may21tz1p2'),
    path('past-papers/physics-hl/may-2022-tz1-p1/', views.physics_hl_may22tz1p1, name='physics-hl-may22tz1p1'),
    path('past-papers/physics-hl/may-2022-tz1-p2/', views.physics_hl_may22tz1p2, name='physics-hl-may22tz1p2'),
    path('past-papers/physics-hl/may-2023-tz1-p1/', views.physics_hl_may23tz1p1, name='physics-hl-may23tz1p1'),
    path('past-papers/physics-hl/may-2023-tz1-p2/', views.physics_hl_may23tz1p2, name='physics-hl-may23tz1p2'),
    path('past-papers/physics-hl/may-2024-tz1-p1/', views.physics_hl_may24tz1p1, name='physics-hl-may24tz1p1'),
    path('past-papers/physics-hl/may-2024-tz1-p2/', views.physics_hl_may24tz1p2, name='physics-hl-may24tz1p2'),
    path('past-papers/physics-hl/nov-2020-tz0-p1/', views.physics_hl_nov20tz0p1, name='physics-hl-nov20tz0p1'),
    path('past-papers/physics-hl/nov-2020-tz0-p2/', views.physics_hl_nov20tz0p2, name='physics-hl-nov20tz0p2'),
    path('past-papers/physics-hl/specimen-2025-p1/', views.physics_hl_specimen2025_p1, name='physics-hl-specimen2025-p1'),
    path('past-papers/physics-hl/specimen-2025-p1b/', views.physics_hl_specimen2025_p1b, name='physics-hl-specimen2025-p1b'),
    path('past-papers/physics-hl/specimen-2025-p2/', views.physics_hl_specimen2025_p2, name='physics-hl-specimen2025-p2'),
    path('past-papers/physics-hl/may-2025-tz1-p1a/', views.physics_hl_may25tz1p1a, name='physics-hl-may25tz1p1a'),
    path('past-papers/physics-hl/may-2025-tz2-p1a/', views.physics_hl_may25tz2p1a, name='physics-hl-may25tz2p1a'),
    path('past-papers/physics-hl/may-2025-tz3-p1a/', views.physics_hl_may25tz3p1a, name='physics-hl-may25tz3p1a'),
    path('past-papers/physics-hl/may-2025-tz1-p1b/', views.physics_hl_may25tz1p1b, name='physics-hl-may25tz1p1b'),
    path('past-papers/physics-hl/may-2025-tz2-p1b/', views.physics_hl_may25tz2p1b, name='physics-hl-may25tz2p1b'),
    path('past-papers/physics-hl/may-2025-tz3-p1b/', views.physics_hl_may25tz3p1b, name='physics-hl-may25tz3p1b'),
    path('past-papers/physics-hl/may-2025-tz1-p2/', views.physics_hl_may25tz1p2, name='physics-hl-may25tz1p2'),
    path('past-papers/physics-hl/may-2025-tz2-p2/', views.physics_hl_may25tz2p2, name='physics-hl-may25tz2p2'),
    path('past-papers/physics-hl/may-2025-tz3-p2/', views.physics_hl_may25tz3p2, name='physics-hl-may25tz3p2'),

    # Chemistry SL Past Papers
    path('past-papers/chemistry-sl/', views.chemistry_sl_past_papers, name='chemistry-sl-past-papers'),

    # Chemistry SL Questionbank
    path('api/chemistry-sl-questions/', views.ChemistrySLQuestionsListAPIView.as_view(), name='chemistry-sl-questions-list'),
    path('ib-hub/chemistry-sl/', views.chemistry_sl, name='chemistry-sl'),
    path('ib-hub/chemistry-sl/introduction-particulate-matter', views.introduction_particulate_matter, name='introduction-particulate-matter'),
    path('ib-hub/chemistry-sl/nuclear-atom', views.nuclear_atom, name='nuclear-atom'),
    path('ib-hub/chemistry-sl/electron-configurations', views.electron_configurations, name='electron-configurations'),
    path('ib-hub/chemistry-sl/counting-particles-mole', views.counting_particles_mole, name='counting-particles-mole'),
    path('ib-hub/chemistry-sl/ideal-gases', views.ideal_gases, name='ideal-gases'),
    path('ib-hub/chemistry-sl/ionic-model', views.ionic_model, name='ionic-model'),
    path('ib-hub/chemistry-sl/covalent-model', views.covalent_model, name='covalent-model'),
    path('ib-hub/chemistry-sl/metallic-model', views.metallic_model, name='metallic-model'),
    path('ib-hub/chemistry-sl/models-to-materials', views.models_to_materials, name='models-to-materials'),
    path('ib-hub/chemistry-sl/periodic-table', views.periodic_table, name='periodic-table'),
    path('ib-hub/chemistry-sl/functional-groups', views.functional_groups, name='functional-groups'),
    path('ib-hub/chemistry-sl/measuring-enthalpy', views.measuring_enthalpy, name='measuring-enthalpy'),
    path('ib-hub/chemistry-sl/energy-cycles', views.energy_cycles, name='energy-cycles'),
    path('ib-hub/chemistry-sl/energy-from-fuels', views.energy_from_fuels, name='energy-from-fuels'),
    path('ib-hub/chemistry-sl/amount-chemical-change', views.amount_chemical_change, name='amount-chemical-change'),
    path('ib-hub/chemistry-sl/rate-chemical-change', views.rate_chemical_change, name='rate-chemical-change'),
    path('ib-hub/chemistry-sl/extent-chemical-change', views.extent_chemical_change, name='extent-chemical-change'),
    path('ib-hub/chemistry-sl/proton-transfer', views.proton_transfer, name='proton-transfer'),
    path('ib-hub/chemistry-sl/electron-transfer', views.electron_transfer, name='electron-transfer'),
    path('ib-hub/chemistry-sl/electron-sharing', views.electron_sharing, name='electron-sharing'),
    path('ib-hub/chemistry-sl/electron-pair-sharing', views.electron_pair_sharing, name='electron-pair-sharing'),


    # Chemistry HL Questionbank
    path('api/chemistry-hl-questions/', views.ChemistryHLQuestionsListAPIView.as_view(), name='chemistry-hl-questions-list'),
    path('ib-hub/chemistry-hl/', views.chemistry_hl, name='chemistry-hl'),
    path('ib-hub/chemistry-hl/introduction-particulate-matter', views.introduction_particulate_matter_hl, name='introduction-particulate-matter-hl'),
    path('ib-hub/chemistry-hl/nuclear-atom', views.nuclear_atom_hl, name='nuclear-atom-hl'),
    path('ib-hub/chemistry-hl/electron-configurations', views.electron_configurations_hl, name='electron-configurations-hl'),
    path('ib-hub/chemistry-hl/counting-particles-mole', views.counting_particles_mole_hl, name='counting-particles-mole-hl'),
    path('ib-hub/chemistry-hl/ideal-gases', views.ideal_gases_hl, name='ideal-gases-hl'),
    path('ib-hub/chemistry-hl/ionic-model', views.ionic_model_hl, name='ionic-model-hl'),
    path('ib-hub/chemistry-hl/covalent-model', views.covalent_model_hl, name='covalent-model-hl'),
    path('ib-hub/chemistry-hl/metallic-model', views.metallic_model_hl, name='metallic-model-hl'),
    path('ib-hub/chemistry-hl/models-to-materials', views.models_to_materials_hl, name='models-to-materials-hl'),
    path('ib-hub/chemistry-hl/periodic-table', views.periodic_table_hl, name='periodic-table-hl'),
    path('ib-hub/chemistry-hl/functional-groups', views.functional_groups_hl, name='functional-groups-hl'),
    path('ib-hub/chemistry-hl/measuring-enthalpy', views.measuring_enthalpy_hl, name='measuring-enthalpy-hl'),
    path('ib-hub/chemistry-hl/energy-cycles', views.energy_cycles_hl, name='energy-cycles-hl'),
    path('ib-hub/chemistry-hl/energy-from-fuels', views.energy_from_fuels_hl, name='energy-from-fuels-hl'),
    path('ib-hub/chemistry-hl/entropy-spontaneity', views.entropy_spontaneity_hl, name='entropy-spontaneity-hl'),
    path('ib-hub/chemistry-hl/amount-chemical-change', views.amount_chemical_change_hl, name='amount-chemical-change-hl'),
    path('ib-hub/chemistry-hl/rate-chemical-change', views.rate_chemical_change_hl, name='rate-chemical-change-hl'),
    path('ib-hub/chemistry-hl/extent-chemical-change', views.extent_chemical_change_hl, name='extent-chemical-change-hl'),
    path('ib-hub/chemistry-hl/proton-transfer', views.proton_transfer_hl, name='proton-transfer-hl'),
    path('ib-hub/chemistry-hl/electron-transfer', views.electron_transfer_hl, name='electron-transfer-hl'),
    path('ib-hub/chemistry-hl/electron-sharing', views.electron_sharing_hl, name='electron-sharing-hl'),
    path('ib-hub/chemistry-hl/electron-pair-sharing', views.electron_pair_sharing_hl, name='electron-pair-sharing-hl'),


    # Computer Science SL Questionbank
    path('api/comp-sci-sl-questions/', views.CompSciSLQuestionsListAPIView.as_view(), name='comp-sci-sl-questions-list'),
    path('ib-hub/computer-science-sl/', views.comp_sci_sl, name='comp-sci-sl'),
    path('ib-hub/computer-science-sl/system-fundamentals', views.system_fundamentals_sl, name='system-fundamentals-sl'),
    path('ib-hub/computer-science-sl/computer-organisation', views.computer_organisation_sl, name='computer-organisation-sl'),
    path('ib-hub/computer-science-sl/networks', views.networks_sl, name='networks-sl'),
    path('ib-hub/computer-science-sl/computational-thinking', views.computational_thinking_sl, name='computational-thinking-sl'),
    path('ib-hub/computer-science-sl/variables-and-input', views.variables_and_input_sl, name='variables-and-input-sl'),
    path('ib-hub/computer-science-sl/if-statements', views.if_statements_sl, name='if-statements-sl'),
    path('ib-hub/computer-science-sl/loops', views.loops_sl, name='loops-sl'),
    path('ib-hub/computer-science-sl/arrays', views.arrays_sl, name='arrays-sl'),
    path('ib-hub/computer-science-sl/methods', views.methods_sl, name='methods-sl'),
    path('ib-hub/computer-science-sl/constructors', views.constructors_sl, name='constructors-sl'),
    path('ib-hub/computer-science-sl/oop', views.oop_sl, name='oop-sl'),

    # Computer Science SL Past Papers
    path('past-papers/computer-science-sl/', views.comp_sci_sl_past_papers, name='comp-sci-sl-past-papers'),
    path('past-papers/computer-science-sl/may-2023-tz1-p1/', views.comp_sci_sl_may23tz1p1, name='comp-sci-sl-may23tz1p1'),
    path('past-papers/computer-science-sl/may-2022-tz1-p1/', views.comp_sci_sl_may22tz1p1, name='comp-sci-sl-may22tz1p1'),
    path('past-papers/computer-science-sl/may-2024-tz1-p2/', views.comp_sci_sl_may24tz1p2, name='comp-sci-sl-may24tz1p2'),

    # Computer Science HL Questionbank
    path('api/comp-sci-hl-questions/', views.CompSciHLQuestionsListAPIView.as_view(), name='comp-sci-hl-questions-list'),
    path('ib-hub/computer-science-hl/', views.comp_sci_hl, name='comp-sci-hl'),
    path('ib-hub/computer-science-hl/system-fundamentals', views.system_fundamentals_hl, name='system-fundamentals-hl'),
    path('ib-hub/computer-science-hl/computer-organisation', views.computer_organisation_hl, name='computer-organisation-hl'),
    path('ib-hub/computer-science-hl/arrays', views.arrays_hl, name='arrays-hl'),
    path('ib-hub/computer-science-hl/methods', views.methods_hl, name='methods-hl'),
    path('ib-hub/computer-science-hl/constructors', views.constructors_hl, name='constructors-hl'),
    path('ib-hub/computer-science-hl/networks', views.networks_hl, name='networks-hl'),
    path('ib-hub/computer-science-hl/computational-thinking', views.computational_thinking_hl, name='computational-thinking-hl'),
    path('ib-hub/computer-science-hl/variables-and-input', views.variables_and_input_hl, name='variables-and-input-hl'),
    path('ib-hub/computer-science-hl/if-statements', views.if_statements_hl, name='if-statements-hl'),
    path('ib-hub/computer-science-hl/loops', views.loops_hl, name='loops-hl'),
    path('ib-hub/computer-science-hl/resource-management', views.resource_management_hl, name='resource-management-hl'),
    path('ib-hub/computer-science-hl/abstract-data-structures', views.abstract_data_structures_hl, name='abstract-data-structures-hl'),
    path('ib-hub/computer-science-hl/oop', views.oop_hl, name='oop-hl'),
    
    # Tutor Admin Panel URLs
    path('tutor-admin/', views.tutor_admin, name='tutor-admin'),
    path('tutor-management-admin/', views.tutor_management_admin, name='tutor-management-admin'),
    path('tutor-admin/delete-session/<int:session_id>/', views.delete_tutor_session, name='delete-tutor-session'),
    path('tutor-admin/update-session/<int:session_id>/', views.update_session_status, name='update-session-status'),
    path('api/apex/confirm-teacher/', views.confirm_apex_teacher, name='confirm-apex-teacher'),
    path('api/apex/bulk-confirm-teachers/', views.bulk_confirm_apex_teachers, name='bulk-confirm-apex-teachers'),
    path('api/apex/bulk-delete-teachers/', views.bulk_delete_apex_teachers, name='bulk-delete-apex-teachers'),
    path('api/apex/delete-teacher/', views.delete_apex_teacher, name='delete-apex-teacher'),

    # Student Admin Panel URLs
    path('student-admin/', views.student_admin, name='student-admin'),
    path('student-admin-v2/', views.student_admin_v2, name='student-admin-v2'),
    path('logistics-dashboard/', views.logistics_dashboard, name='logistics-dashboard'),
    path('revision-engine/class-transcript-analysis/<int:session_id>/', views.transcript_analysis, name='transcript-analysis'),
    path('revision-engine/learning-path/<int:analysis_id>/', views.learning_path, name='learning-path'),
    path('revision-engine/lp-practice/<slug:skill_slug>/', views.learning_path_practice, name='learning-path-practice'),
    path('export-questions/', views.export_questions, name='export-questions'),
    path('export-questions/print/', views.export_questions_print, name='export-questions-print'),
    path('api/accept-tutoring-rules/', views.accept_tutoring_rules, name='accept-tutoring-rules'),
    
    # Parent Panel URLs
    path('parent-admin/', views.parent_admin, name='parent-admin'),
    
    # Admin Student Management URLs
    path('admin-student-management/', views.admin_student_management, name='admin-student-management'),
    path('admin-student-management/delete-student/<int:student_id>/', views.delete_managed_student, name='delete-managed-student'),
    path('admin-student-management/student-preview/<int:student_id>/', views.student_preview_ajax, name='student-preview-ajax'),
    
    # Remove Users from Database
    path('remove-users-db/', views.remove_users_db, name='remove-users-db'),
    
    # Add Premium Members
    path('add-premium-members/', views.add_premium_members, name='add-premium-members'),

    # Question Status API
    path('api/question-status/update/', views.update_question_status, name='update-question-status'),
    path('api/question-status/get/', views.get_question_status, name='get-question-status'),
    path('api/question-report/', views.report_question_problem, name='report-question-problem'),

    # Revision Engine
    path('revision-engine/ib-paper-preview/', views.ib_paper_may2023_preview, name='ib-paper-preview'),
    path('revision-engine/paper-upload/', views.ib_paper_upload, name='ib-paper-upload'),
    path(
        'revision-engine/paper-upload/<uuid:upload_id>/',
        views.ib_paper_upload_view,
        name='ib-paper-upload-view',
    ),
    path(
        'revision-engine/paper-upload/<uuid:upload_id>/save-html/',
        views.ib_paper_upload_save_question_html,
        name='ib-paper-upload-save-html',
    ),
    path(
        'revision-engine/ib-paper-ai-cleanup-html/',
        views.ib_paper_ai_cleanup_question_html,
        name='ib-paper-ai-cleanup-html',
    ),
    path('revision-engine/', views.revision_engine_home, name='revision-engine'),
    path('revision-engine/practice/<slug:skill_slug>/', views.revision_engine_practice, name='revision-engine-practice'),
    path('revision-engine/tag-questions/', views.revision_engine_tag_questions, name='revision-engine-tag-questions'),
    path('revision-engine/tag-subquestions/', views.revision_engine_tag_subquestions, name='revision-engine-tag-subquestions'),
    path('api/revision-engine/save-subquestion-tags/', views.revision_engine_save_subquestion_tags, name='revision-engine-save-subquestion-tags'),
    path('revision-engine/edit-mcq/<int:question_id>/', views.revision_engine_edit_mcq, name='revision-engine-edit-mcq'),
    path('revision-engine/mcq-review/', views.revision_engine_mcq_review, name='revision-engine-mcq-review'),
    path('api/revision-engine/submit/', views.revision_engine_submit, name='revision-engine-submit'),
    path('api/revision-engine/save-tags/', views.revision_engine_save_tags, name='revision-engine-save-tags'),
    path('api/revision-engine/save-subquestion/', views.revision_engine_save_subquestion, name='revision-engine-save-subquestion'),
    path('api/revision-engine/delete-subquestion/', views.revision_engine_delete_subquestion, name='revision-engine-delete-subquestion'),
    path('api/revision-engine/reorder-subquestions/', views.revision_engine_reorder_subquestions, name='revision-engine-reorder-subquestions'),
    path('api/tutor/run-analysis/', views.tutor_run_analysis, name='tutor-run-analysis'),
    path('api/tutor/save-analysis/', views.tutor_save_analysis, name='tutor-save-analysis'),
    path('api/revision-engine/submit-mcq/', views.revision_engine_submit_mcq, name='revision-engine-submit-mcq'),

    # Staff impersonation
    path('staff/impersonate/<int:user_id>/', views.impersonate_user, name='impersonate-user'),
    path('staff/stop-impersonating/', views.stop_impersonating, name='stop-impersonating'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
